Repository owncloud/ocis, pull requests merged in 2020-08, with the labels that each got.

#427 [Tests-Only] Implement EXPECTED_FAILURES_FILE for API acceptance tests
  .codacy.yml
  .drone.star
  .gitignore
  Makefile
  composer.json
  docs/testing.md
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures.txt
  tests/acceptance/features/apiOcisSpecific/ocsDELETEAuth.feature
  tests/acceptance/features/apiOcisSpecific/ocsGETAuth.feature
  tests/acceptance/features/apiOcisSpecific/ocsPOSTAuth.feature
  tests/acceptance/features/apiOcisSpecific/ocsPUTAuth.feature
  tests/acceptance/features/bootstrap/RevaContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  vendor-bin/behat/composer.json
Labels: qa-team

#456 [Tests-Only] Bump core commit for API tests 2020-08-15
  .drone.star
Labels: qa-team

#409 Update deps 2020 07 22
  .drone.star
  changelog/unreleased/simplify-tracing.md
  docker-compose.yml
  docs/eos.md
  go.mod
  go.sum
  pkg/command/store.go
  pkg/config/config.go
  pkg/runtime/runtime.go
  tests/acceptance/expected-failures.txt
  tests/acceptance/features/apiOcisSpecific/apiAuthOcs-ocsDELETEAuth.feature
  tests/acceptance/features/apiOcisSpecific/apiAuthOcs-ocsGETAuth.feature
  tests/acceptance/features/apiOcisSpecific/apiAuthOcs-ocsPOSTAuth.feature
  tests/acceptance/features/apiOcisSpecific/apiAuthOcs-ocsPUTAuth.feature
  tests/acceptance/features/apiOcisSpecific/apiShareManagementBasic-createShare.feature
  tests/acceptance/features/apiOcisSpecific/apiShareUpdate-updateShare.feature
  tests/acceptance/features/apiOcisSpecific/apiWebdavPreviews-previews.feature
Labels: enhancement

#392 set missing env vars
  changelog/unreleased/add-missing-env-vars.md
  docker-compose.yml
Labels: bug

#466 Update Reva and Proxy
  changelog/unreleased/update-extensions-reva-and-proxy.md
  go.mod
  go.sum
Labels: enhancement

#469 add REVA_LDAP_IDP to docker compose
  docker-compose.yml
Labels: bug

#263 update to current path
  docs/basic-remote-setup.md
Labels: documentation

#482 [Tests-Only] Expected failures in apiTrashbin
  .drone.star
  tests/acceptance/expected-failures-on-OC-storage.txt
Labels: qa-team

#481 Adjust testing docs to run tests without ldap server
  docs/testing.md
Labels: qa-team

#489 [Tests-Only] Add api trashbin tests
  .gitignore
  tests/acceptance/expected-failures-on-OC-storage.txt
  tests/acceptance/features/apiOcisSpecific/apiTrashbin-trashbinDelete.feature
  tests/acceptance/features/apiOcisSpecific/apiTrashbin-trashbinFilesFolders.feature
Labels: qa-team

#484 use eos driver for /eos namespace
  docker-compose.yml
  docs/eos.md
Labels: documentation

#508 [Tests-Only] Delete passing apiTrashbin test from bug demonstration
  tests/acceptance/features/apiOcisSpecific/apiTrashbin-trashbinFilesFolders.feature
Labels: qa-team

#509 [Tests-Only] Run latest phoenix webUI tests
  .drone.star
Labels: qa-team
