Repository owncloud/ocis, pull requests merged in 2020-10, with the labels that each got.

#648 Add autoprovision accounts flag
  proxy/changelog/unreleased/add-autoprovision-accounts-flag.md
  proxy/pkg/command/server.go
  proxy/pkg/config/config.go
  proxy/pkg/flagset/flagset.go
  proxy/pkg/middleware/account_uuid.go
  proxy/pkg/middleware/options.go
Labels: enhancement

#649 add glauth fallback backend
  changelog/unreleased/glauth-fallback-option.md
  docs/extensions/glauth/_index.md
  docs/extensions/glauth/getting-started.md
  glauth/go.mod
  glauth/go.sum
  glauth/pkg/command/server.go
  glauth/pkg/config/config.go
  glauth/pkg/flagset/flagset.go
  glauth/pkg/server/glauth/chain.go
  glauth/pkg/server/glauth/ocis.go
  glauth/pkg/server/glauth/option.go
  glauth/pkg/server/glauth/server.go
  ocis/go.mod
  ocis/go.sum
  ocis/pkg/command/glauth.go
Labels: bug

#683 [docs-only] fix edit path
  docs/ocis/deployment/_index.md
  docs/ocis/deployment/basic-remote-setup.md
  docs/ocis/deployment/bridge.md
  docs/ocis/development/_index.md
  docs/ocis/development/building-docs.md
  docs/ocis/development/building.md
  docs/ocis/development/debugging.md
  docs/ocis/development/getting-started.md
  docs/ocis/development/testing.md
  docs/ocis/development/tracing.md
  docs/ocis/eos.md
  docs/ocis/extensions.md
  docs/ocis/getting-started.md
  docs/ocis/license.md
  docs/ocis/login-flow.md
  docs/ocis/public-upload-flow.md
  docs/ocis/request-flow.md
Labels: documentation

#679 [Tests-Only] update issues in expected failure file for owncloud storage
  ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
  ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Labels: enhancement

#735 [docs-only] fix documentation because OCIS is now the default storage
  docs/extensions/storage/testing.md
  docs/ocis/development/testing.md
Labels: documentation

#745 Fix id or username query handling
  accounts/pkg/service/v0/accounts.go
  changelog/unreleased/fix-id-or-username-query-handling.md
Labels: bug

#752 [tests-only] bug demonstration scenario for #751
  ocis/tests/acceptance/features/apiOcisSpecific/apiShareManagementBasic-deleteShare.feature
  ocis/tests/acceptance/features/apiOcisSpecific/apiShareWebdavOperations-propfind.feature
Labels: QA-Team

#778 [tests-only] expected failures of favourites tests
  .drone.star
  ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
  ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Labels: QA-Team

#784 [tests-only] adjust expected failures list after owncloud/core/pull/38056
  .drone.star
  ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
  ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Labels: QA-Team
