Repository owncloud/ocis, pull requests merged in 2020-05, with the labels that each got.

#236 add simple remote setup to docs
  docs/basic-remote-setup.md
  docs/configuration.md
Labels: documentation, enhancement

#245 Update bridge documentation
  docs/bridge.md
Labels: documentation

#246 update login and request flow diagrams
  docs/login-flow.md
  docs/request-flow.md
Labels: documentation

#247 Use latest eos docker image
  Makefile
Labels: QA-Team, enhancement

#256 fix typo
  docs/eos.md
Labels: QA-Team

#275 [Tests-only] Create test-skeleton files while creating user
  .drone.star
Labels: QA-Team

#276 [Tests-only] Fix skeleton directory path
  .drone.star
Labels: QA-Team

#274 Add basic docs for tracing
  docs/tracing.md
Labels: documentation

#288 [Tests-Only] fix configuration variables for ui test in CI
  .drone.star
Labels: QA-Team
