Repository owncloud/ocis, pull requests merged in 2020-11, with the labels that each got.

#802 [Tests-Only] update core commitid for test runner
  .drone.star
  ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
  ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Labels: QA-Team

#882 fix redis address variable name
  docs/ocis/deployment/basic-remote-setup.md
Labels: QA-Team

#853 [tests-only] Add group tests on expected failure file
  .drone.star
  ocis/tests/acceptance/expected-failures-on-OCIS-storage.txt
  ocis/tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Labels: QA-Team

#886 Show basic_auth warning only on startup
  changelog/unreleased/dont-nag-about-basicauth.md
  proxy/pkg/middleware/basic_auth.go
Labels: enhancement

#907 [tests-only] Bump core commit id for API tests
  .drone.star
  ocis/vendor-bin/behat/composer.json
Labels: QA-Team

#813 Enable dynamic client registration
  changelog/unreleased/enable-dynamic-client-registration.md
  konnectd/pkg/flagset/flagset.go
Labels: OCIS-Fastlane

#906 [CI] enable nightly test runs
  .drone.star
Labels: QA-Team

#922 [tests-only] bump phoenix commit id for tests and add new suites
  .drone.star
Labels: QA-Team

#926 delete comment about resharing in drone
  .drone.star
Labels: QA-Team

#936 [CI] fix pipelines names in ci
  .drone.star
Labels: QA-Team

#970 [tests-only] Bump core commit id for API tests
  .drone.star
  tests/acceptance/expected-failures-on-OCIS-storage.txt
Labels: QA-Team

#977 [tests-only] Bump core commit for API tests
  .drone.star
Labels: QA-Team

#982 [Tests-Only] Add failing Tus test to expected failure file
  .drone.star
  tests/acceptance/expected-failures-on-OCIS-storage.txt
  tests/acceptance/expected-failures-on-OWNCLOUD-storage.txt
Labels: QA-Team
