Repository owncloud/ocis, pull requests merged in 2020-03, with the labels that each got.

#138 Start proxy with ocis server command
  changelog/unreleased/start-proxy-with-server.md
  go.mod
  go.sum
  pkg/command/proxy.go
  pkg/config/config.go
  pkg/micro/runtime/runtime.go
Labels: enhancement

#145 replace devldap with glauth
  go.mod
  go.sum
  pkg/command/devldap.go
  pkg/command/glauth.go
  pkg/config/config.go
  pkg/micro/runtime/runtime.go
Labels: enhancement

#161 Split getting-started and configuration in docs
  docs/.gitignore
  docs/configuration.md
  docs/getting-started.md
Labels: documentation

#166 [Tests-Only] run API tests from oC 10 in CI
  .drone.star
Labels: QA-Team
