Repository owncloud/ocis, pull requests merged in 2020-04, with the labels that each got.

#158 do not strip debug data for debug build
  Makefile
Labels: bug

#181 [Tests-Only] Run phoenix webui acceptance tests
  .drone.star
  tests/config/drone/identifier-registration.yml
  tests/config/drone/ocis-config.json
Labels: QA-Team

#206 Added config.json inside phoenix dist
  .drone.star
Labels: QA-Team

#204 remove identifier-registration.yaml during make clean
  Makefile
Labels: enhancement

#176 partially fix simple build
  docs/building.md
  pkg/command/server_simple.go
Labels: bug

#217 make ocis on eos great again
  Makefile
  go.mod
  go.sum
Labels: bug

#220 [Tests-only] remove need to authorize phoenix in kopano
  tests/config/drone/identifier-registration.yml
Labels: QA-Team

#221 [Tests-only] add slash at the end of redirect_uri to allow correct logout
  tests/config/drone/identifier-registration.yml
Labels: QA-Team

#218 [Tests-only] document how to use oC10 API tests for BDD in ocis
  docs/testing.md
Labels: QA-Team, documentation

#237 use correct hint markdown
  docs/extensions.md
Labels: documentation
