Repository owncloud/ocis, pull requests merged in 2020-07, with the labels that each got.

#348 [CI] Split phoenix tests into multiple pipelines
  .drone.star
Labels: QA-Team, drone

#357 update extensions 2020-07-01
  .drone.star
  changelog/unreleased/update-extensions-01_07_2020
  go.mod
  go.sum
Labels: p2-high

#363 [Docs] Add doc for cloning testing app for running tests
  docs/testing.md
Labels: QA-Team, documentation

#364 [Docs] Add skeleton dir path env variable in test run
  docs/testing.md
Labels: QA-Team, documentation

#369 add config for datagateway and silent redirect
  docs/basic-remote-setup.md
Labels: documentation, enhancement

#349 initial docker-compose.yml for developers
  config/eos-docker.env
  docker-compose.yml
  docs/development.md
  docs/eos.md
Labels: documentation, enhancement

#398 [Tests-only] use built in phoenix to run ui tests
  .drone.star
Labels: drone

#416 Use alpine:latest instead of alpine:edge in docker builds
  changelog/unreleased/use-alpine-latest.md
  docker/Dockerfile.linux.amd64
  docker/Dockerfile.linux.arm
  docker/Dockerfile.linux.arm64
Labels: bug

#399 [docs] Add docs about running tests in CI
  docs/testing.md
Labels: documentation

#415 [Tests-Only] Update phoenix acceptance test commit id
  .drone.star
Labels: QA-Team

#421 Add public upload flow to docs
  docs/public-upload-flow.md
  docs/static/src/tus-public-upload.drawio
  docs/static/tus-public-upload.svg
Labels: documentation

#420 Add docs how to work with hugo
  docs/building-docs.md
Labels: documentation
