Repository owncloud/ocis, pull requests merged in 2021-09, with the labels that each got.

#2473 [tests-only]Bump core commit id
  .drone.env
Labels: QA:team

#2494 [docs-only] Docs storage backend cephfs
  docs/ocis/migration.md
  docs/ocis/storage-backends/cephfs.md
Labels: Topic:Documentation

#2490 [full-ci][tests-only] Bump commit ids for tests
  .drone.env
Labels: QA:team

#2511 use proper url path decode on the username
  changelog/unreleased/fix-username-encoding.md
  ocs/pkg/middleware/requireselforadmin.go
Labels: Type:Bug

#2518 [full-ci] [tests-only] Bump commit ids for tests
  .drone.env
Labels: QA:team

#2492 Allow reva to use safer TLS defaults for LDAP
  changelog/unreleased/reva-ldap-tls.md
  storage/pkg/command/authbasic.go
  storage/pkg/command/groups.go
  storage/pkg/command/users.go
  storage/pkg/config/config.go
  storage/pkg/flagset/ldap.go
Labels: Topic:Security, Category:Enhancement

#2533 [tests-only] [full-ci] Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#2557 fix the account resolver middleware
  changelog/unreleased/fix-account-resolver.md
  proxy/pkg/middleware/account_resolver.go
Labels: Status:Needs-Review
