Repository owncloud/ocis, pull requests merged in 2021-12, with the labels that each got.

#2864 fix formatting
  docs/extensions/graph/spaces.md
Labels: QA:team

#2858 graph update
  changelog/unreleased/update-libregraph-api.md
  go.mod
  go.sum
  graph/pkg/service/v0/drives.go
  graph/pkg/service/v0/errorcode/errorcode.go
Labels: Type:Technical-Debt, Category:Nonfunctional, Topic:API

#2871 [tests-only][full-ci]Bump commit id for tests
  .drone.env
Labels: QA:team

#2869 Graph api rest
  changelog/unreleased/update-spaces-handle-non-existent.md
  docs/extensions/storage/spaces.md
  docs/ocis/adr/0007-api-for-spaces.md
  go.mod
  go.sum
  graph/pkg/service/v0/drives.go
  graph/pkg/service/v0/service.go
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Estimation:S(2), Type:Technical-Debt, Category:Change, Topic:API

#2875 [tests-only] [full-ci] Bump core commit id to include new group name tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2874 [tests-only] Minor local API test changes
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/ArchiverContext.php
  tests/acceptance/features/bootstrap/RevaContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#2881 [tests-only][full-ci]Remove a test scenario from expected to fail file
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2901 [tests-only] [full-ci] Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2904 [tests-only] Reword Spaces API scenario descriptions
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/shareSpaces.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
Labels: QA:team

#2897 [tests-only][full-ci] Added parallel deployment testing setup
  .drone.star
  Makefile
  tests/parallelDeployAcceptance/.gitignore
  tests/parallelDeployAcceptance/config/behat.yml
  tests/parallelDeployAcceptance/config/ldap_users_groups.ldif
  tests/parallelDeployAcceptance/drone/ldap/ldif/10_owncloud_schema.ldif
  tests/parallelDeployAcceptance/drone/oc10/10-custom-config.sh
  tests/parallelDeployAcceptance/drone/oc10/ldap-config.tmpl.json
  tests/parallelDeployAcceptance/drone/oc10/oidc.config.php
  tests/parallelDeployAcceptance/drone/ocis/proxy.json
  tests/parallelDeployAcceptance/expected-failures-API.md
  tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
  tests/parallelDeployAcceptance/features/apiWebdavOperations/downloadFile.feature
  tests/parallelDeployAcceptance/features/bootstrap/ParallelContext.php
  tests/parallelDeployAcceptance/features/bootstrap/bootstrap.php
Labels: QA:team

#2911 [tests-only] Refactor SpacesContext
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#2910 Add ocis storage-auth-machine subcommand
  changelog/unreleased/add-missing-machineauth-ocis-subcommand.md
  ocis/pkg/command/storageauthmachine.go
Labels: Type:Bug

#2909 update getting started
  docs/ocis/getting-started/_index.md
Labels: Topic:Documentation

#2912 [tests-only] [full-ci] Bump core commit id for tests and use core master
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: Category:Nonfunctional, QA:team

#2895 [full-ci] Bump web to v4.8.0
  .drone.env
  changelog/unreleased/update-web-4.8.0.md
  settings/ui/tests/acceptance/features/settings.feature
  settings/ui/tests/acceptance/helpers/language.js
  settings/ui/tests/acceptance/pageobjects/filesPageSettingsContext.js
  tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
  web/Makefile
Labels: Platform:Web, Status:On-Hold

#2921 [tests-only][full-ci] Bump core commit id for tests
  .drone.env
Labels: QA:team
