Repository owncloud/ocis, pull requests merged in 2021-08, with the labels that each got.

#2341 [tests-only][full-ci]remove api bug demonstration scenarios that are covered by exected-to…
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsDELETEAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsGETAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsPOSTAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsPUTAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthWebDav-webDavLOCKAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthWebDav-webDavMOVEAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiCapabilities-capabilitiesWithNormalUser.feature
  tests/acceptance/features/apiBugDemonstration/apiMain-main.feature
  tests/acceptance/features/apiBugDemonstration/apiShareManagementBasic-createShare.feature
  tests/acceptance/features/apiBugDemonstration/apiShareOperations-gettingShares.feature
  tests/acceptance/features/apiBugDemonstration/apiSharePublicLink2-copyFromPublicLink.feature
  tests/acceptance/features/apiBugDemonstration/apiShareUpdate-updateShare.feature
  tests/acceptance/features/apiBugDemonstration/apiTrashbin-trashbinDelete.feature
  tests/acceptance/features/apiBugDemonstration/apiVersions-fileVersions.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavMove1-moveFolder.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavMove1-moveFolderToBlacklistedName.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavMove2-moveFile.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavMove2-moveFileToBlacklistedName.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavOperations-refuseAccess.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavProperties1-createFolder.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavProperties2-getFileProperties.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavUpload1-uploadFile.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavUploadTUS-optionsRequest.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavUploadTUS-uploadFile.feature
Labels: QA:team

#2345 [tests-only] Bump core commit to include more previews tests
  .drone.env
  .drone.star
  docs/ocis/development/testing.md
  tests/acceptance/config/behat.yml
  tests/acceptance/docker/Makefile
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
  tests/acceptance/features/apiBugDemonstration/apiWebdavPreviews-previews.feature
Labels: QA:team

#2370 [tests-only] [full-ci] Bump commit ids for tests
  .drone.env
Labels: QA:team

#2377 [docs-only] docs: Fix some dangling links
  CONTRIBUTING.md
Labels: Type:Bug, Topic:Documentation

#2375 [full-ci] [tests-only] Bump commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2388 Fix naming of the user- and groupprovider services
  ocis/pkg/runtime/service/service.go
  storage/pkg/command/groups.go
  storage/pkg/command/users.go
Labels: Type:Bug

#2407 [docs-only] Add missing changelog entry
  changelog/unreleased/user-group-provider-naming.md
Labels: Topic:Documentation

#2412 [full-ci] [tests-only] Sort out expected-failures for share expiration date
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2414 [full-ci] [tests-only] Remove ocsGETAuth.feature:243 from expected to fail and update commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2419 [tests-only] [full-ci] core id bump
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2429 Move to go-chi/chi v5
  .bingo/Variables.mk
  .bingo/protoc-gen-microweb.mod
  .bingo/variables.env
  accounts/pkg/proto/v0/accounts.pb.web.go
  accounts/pkg/server/http/server.go
  changelog/unreleased/update-chi-v5.md
  go.mod
  go.sum
  graph-explorer/pkg/server/http/server.go
  graph-explorer/pkg/service/v0/service.go
  graph/pkg/server/http/server.go
  graph/pkg/service/v0/errorcode/errorcode.go
  graph/pkg/service/v0/graph.go
  graph/pkg/service/v0/groups.go
  graph/pkg/service/v0/service.go
  graph/pkg/service/v0/users.go
  idp/pkg/server/http/server.go
  idp/pkg/service/v0/service.go
  ocis-pkg/middleware/logger.go
  ocis-pkg/service/debug/service.go
  ocs/pkg/middleware/requireselforadmin.go
  ocs/pkg/server/http/server.go
  ocs/pkg/service/v0/groups.go
  ocs/pkg/service/v0/response/version.go
  ocs/pkg/service/v0/service.go
  ocs/pkg/service/v0/users.go
  proxy/pkg/command/server.go
  proxy/pkg/middleware/accesslog.go
  proxy/pkg/proxy/proxy.go
  settings/pkg/proto/v0/settings.pb.web.go
  settings/pkg/server/http/server.go
  web/pkg/server/http/server.go
  web/pkg/service/v0/service.go
  webdav/pkg/dav/requests/thumbnail.go
  webdav/pkg/server/http/server.go
  webdav/pkg/service/v0/service.go
Labels: Topic:Dependencies

#2443 [tests-only] [full-ci]Adjust expected to fail for file target issue
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team
