Repository owncloud/ocis, pull requests merged in 2021-01, with the labels that each got.

#1172 [tests-only] bump core commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.txt
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.txt
Labels: QA-Team

#1189 [tests-only] Bump core commit id for API tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.txt
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.txt
Labels: QA-Team

#1196 [tests-only] Update WEB_COMMITID for tests
  .drone.env
  tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.txt
Labels: QA-Team

#1206 [tests-only] Bump core and web commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.txt
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.txt
  tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.txt
Labels: QA-Team

#1208 [tests-only] Bump WEB commit id
  .drone.env
Labels: QA-Team

#1211 Introduce github templates
  .codacy.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/stale.yml
Labels: Category:Feature

#1213 [tests-only] Bump core and web commit for tests
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.txt
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.txt
  tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.md
  tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.txt
Labels: QA-Team

#1221 Add onlyoffice mount on docker-compose setup
  ocis/docker-compose.yml
Labels: Storage:EOS, Topic:Docker

#1368 [tests-only] Add nightwatch-vrt to accounts package.json
  accounts/package.json
  accounts/yarn.lock
Labels: QA-Team

#1348 [Tests-Only] Convert expected failure file to markdown
  .drone.env
  .drone.star
  tests/acceptance/docker/src/run-tests.sh
  tests/acceptance/expected-failures-API-on-EOS-storage.md
  tests/acceptance/expected-failures-API-on-EOS-storage.txt
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OCIS-storage.txt
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.txt
  tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.md
Labels: QA-Team

#1369 [tests-only] Bump commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.md
Labels: QA-Team

#1371 [tests-only] do not let someone accidentally commit a local .drone.yml
  .gitignore
Labels: QA-Team

#1383 [tests-only] Bump commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA-Team

#1384 [tests-only] Bump core commit id to include tests in core PR 38325
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA-Team

#1480 [tests-only] Pin behat/gherkin because of Gherkin issue 187
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
  vendor-bin/behat/composer.json
Labels: QA-Team

#1485 [Tests-Only] Adjust the links in the expected-failures file
  tests/acceptance/expected-failures-API-on-EOS-storage.md
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
  tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.md
Labels: QA-Team

#1488 [Tests-Only] Remove test scenarios that now have correct behavior
  tests/acceptance/features/apiBasic/addUser.feature
  tests/acceptance/features/apiBasic/uploadFile.feature
  tests/acceptance/features/apiBasic/webDavPUTAuthInvalid.feature
  tests/acceptance/features/apiOcisSpecific/apiFavorites-favorites.feature
  tests/acceptance/features/apiOcisSpecific/apiVersions-fileVersions.feature
  tests/acceptance/features/apiOcisSpecific/apiWebdavMove2-moveFile.feature
  tests/acceptance/features/apiOcisSpecific/apiWebdavOperations-downloadFile.feature
  tests/acceptance/features/apiOcisSpecific/apiWebdavProperties1-setFileProperties.feature
  tests/acceptance/features/apiOcisSpecific/apiWebdavProperties2-getFileProperties.feature
  tests/acceptance/features/apiOcisSpecific/apiWebdavUpload1-uploadFile.feature
Labels: QA-Team

#1534 [tests-only] Adjust some text in expected-failures to match cs3org/reva
  tests/acceptance/expected-failures-API-on-EOS-storage.md
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA-Team

#1536 update docs to use latest ocis
  docs/ocis/getting-started.md
Labels: Status:Needs-Review

#1540 [tests-only] Bump behat/gherkin to 4.7.1
  vendor-bin/behat/composer.json
Labels: QA-Team

#1543 [tests-only] Restore test files removed in PR #1488
  .drone.star
  docs/ocis/development/testing.md
  tests/acceptance/config/behat.yml
  tests/acceptance/docker/Makefile
  tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature
  tests/acceptance/features/apiAccountsHashDifficulty/webDavPUTAuthInvalid.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsDELETEAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsGETAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsPOSTAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsPUTAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthWebDav-webDavLOCKAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiAuthWebDav-webDavMOVEAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiCapabilities-capabilitiesWithNormalUser.feature
  tests/acceptance/features/apiBugDemonstration/apiMain-main.feature
  tests/acceptance/features/apiBugDemonstration/apiShareCreateSpecial2-createShareWithInvalidPermissions.feature
  tests/acceptance/features/apiBugDemonstration/apiShareManagementBasic-createShare.feature
  tests/acceptance/features/apiBugDemonstration/apiShareOperations-gettingShares.feature
  tests/acceptance/features/apiBugDemonstration/apiSharePublicLink2-copyFromPublicLink.feature
  tests/acceptance/features/apiBugDemonstration/apiShareUpdate-updateShare.feature
  tests/acceptance/features/apiBugDemonstration/apiTrashbin-trashbinDelete.feature
  tests/acceptance/features/apiBugDemonstration/apiVersions-fileVersions.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavMove1-moveFolder.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavMove1-moveFolderToBlacklistedName.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavMove2-moveFile.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavMove2-moveFileToBlacklistedName.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavOperations-refuseAccess.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavPreviews-previews.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavProperties1-createFolder.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavProperties2-getFileProperties.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavUpload1-uploadFile.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavUploadTUS-optionsRequest.feature
  tests/acceptance/features/apiBugDemonstration/apiWebdavUploadTUS-uploadFile.feature
Labels: QA-Team

#1535 [tests-only] Bump commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA-Team

#1545 [docs-only] Update CONFIGURATION.tmpl
  accounts/templates/CONFIGURATION.tmpl
  docs/extensions/onlyoffice/getting-started.md
  glauth/templates/CONFIGURATION.tmpl
  konnectd/templates/CONFIGURATION.tmpl
  ocis/templates/CONFIGURATION.tmpl
  ocs/templates/CONFIGURATION.tmpl
  onlyoffice/templates/CONFIGURATION.tmpl
  proxy/templates/CONFIGURATION.tmpl
  storage/templates/CONFIGURATION.tmpl
  store/templates/CONFIGURATION.tmpl
  thumbnails/templates/CONFIGURATION.tmpl
  web/templates/CONFIGURATION.tmpl
  webdav/templates/CONFIGURATION.tmpl
Labels: Topic:Documentation

#1548 [tests-only] Categorize expected-failures files
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA-Team

#1565 Update JS dependencies
  accounts/go.sum
  accounts/package.json
  accounts/pkg/assets/embed.go
  accounts/yarn.lock
  onlyoffice/go.sum
  onlyoffice/pkg/assets/embed.go
  onlyoffice/yarn.lock
  settings/go.sum
  settings/pkg/assets/embed.go
  settings/yarn.lock
Labels: Topic:Security, dependencies
