Repository owncloud/ocis, pull requests merged in 2021-03, with the labels that each got.

#1746 [tests-only] Bump commit id for API tests
  .drone.env
Labels: QA:team

#1760 [Tests-only] bump web and core commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
  tests/acceptance/expected-failures-webUI-on-OWNCLOUD-storage.md
  tests/acceptance/features/apiBugDemonstration/apiAuthOcs-ocsGETAuth.feature
  tests/acceptance/features/apiBugDemonstration/apiShareOperations-gettingShares.feature
Labels: QA:team

#1788 merge back release 1.3.0
  changelog/1.3.0_2021-03-09/accounts-init-regression.md
  changelog/1.3.0_2021-03-09/add-missing-gatewaysvc-config.md
  changelog/1.3.0_2021-03-09/fix-accounts-service-initialization.md
  changelog/1.3.0_2021-03-09/fix-tokencache-ttl.md
  changelog/1.3.0_2021-03-09/remove-log-secret.md
  changelog/1.3.0_2021-03-09/update-go-micro-to-0f0ace1a.md
  changelog/1.3.0_2021-03-09/update-reva-to-53f39499762e.md
  changelog/1.3.0_2021-03-09/update-web-2.0.1.md
  changelog/1.3.0_2021-03-09/update-web-2.0.2.md
  changelog/1.3.0_2021-03-09/use-registry-interface.md
Labels: Status:Needs-Review

#1813 Replace special character in login page title with a regular minus
  changelog/unreleased/enhancement-adjust-login-page-title.md
  idp/pkg/assets/embed.go
  idp/ui/public/index.html
Labels: Category:Enhancement

#1818 [tests-only] Bump core and web commit ids
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA-Team

#1823 [tests-only] Bump commit id for tests
  .drone.env
Labels: QA:team

#1832 [tests-only] bump commit id for api tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#1841 [tests-only] updated latest core commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#1855 [tests-only] Bump core commit id 2020 03 25
  .drone.env
  tests/acceptance/expected-failures-API-on-EOS-storage.md
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#1862 [tests-only] bumped core commit id for API tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team
