Repository owncloud/ocis, pull requests merged in 2021-07, with the labels that each got.

#2238 [Tests-Only] bump the web commit id for ci tests with expected failure files
  .drone.env
  tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#2006 [docs-only] Configuration ADR
  docs/ocis/adr/0008-configuration.md
Labels: Topic:Documentation

#2234 [Tests-Only] update core commitid for tests
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team, Status:Needs-Review

#2264 [full-ci] [tests-only] Remove closed sharing issues
  .drone.env
  tests/acceptance/expected-failures-API-on-EOS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#2262 [full-ci] bump core commit id to run new versions tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#2270 [full-ci] [tests-only] Always run minimal web UI test pipeline
  .drone.star
Labels: QA:team

#2168 [docs-only] draft an adr for extension templates
  docs/ocis/adr/0008-extension-template.md
Labels: Interaction:Discussion

#2283 [docs-only] update testing docs to include STORAGE_DRIVER env var
  docs/ocis/development/testing.md
Labels: QA:team

#2278 [tests-only] [full-ci] Bump commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-EOS-storage.md
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#2281 [tests-only] [full-ci] Bump commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#2286 [Tests-Only] Link issues in expected failure file
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#2287 [tests-only] [full-ci] Update web id 20210712
  .drone.env
  tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#2295 Scope and lw account changes and update reva to v1.10.0
  accounts/go.mod
  accounts/go.sum
  accounts/pkg/storage/cs3.go
  changelog/unreleased/update-reva-v1.10.0.md
  glauth/go.sum
  graph-explorer/go.sum
  graph/go.mod
  graph/go.sum
  idp/go.sum
  ocis-pkg/go.mod
  ocis-pkg/go.sum
  ocis/go.sum
  ocs/go.mod
  ocs/go.sum
  ocs/pkg/server/http/svc_test.go
  ocs/pkg/service/v0/users.go
  onlyoffice/go.sum
  proxy/go.mod
  proxy/go.sum
  proxy/pkg/middleware/account_resolver.go
  proxy/pkg/user/backend/cs3.go
  settings/go.sum
  settings/pkg/service/v0/validator.go
  storage/go.mod
  storage/go.sum
  store/go.sum
  thumbnails/go.mod
  thumbnails/go.sum
  web/go.sum
  webdav/go.sum
Labels: Early-Adopter:CERN

#2304 [tests-only] [full-ci] Bump commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#2311 [full-ci][tests-only] Bump commit ids for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#2316 [full-ci][tests-only]bump core and web commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#2320 [tests-only] [full-ci] Enable SEND_SCENARIO_LINE_REFERENCES to send X-Request-Id header in API tests
  .drone.star
Labels: QA:team

#2321 [tests-only] [full-ci] Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#2331 [tests-only][full-ci]Bump commit id 20210728
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md
Labels: QA:team

#2307 [docs-only] add how to theme idp
  docs/extensions/idp/theming.md
Labels: Topic:Documentation
