Repository owncloud/ocis, pull requests merged in 2022-10, with the labels that each got.

#4723 bring back CORS env vars
  ocis-pkg/config/config.go
  ocis-pkg/shared/shared_types.go
  services/frontend/pkg/config/config.go
  services/graph/pkg/config/cachestore.go
  services/ocs/pkg/config/cachestore.go
  services/ocs/pkg/config/http.go
  services/search/pkg/config/config.go
  services/settings/pkg/config/http.go
  services/sharing/pkg/config/config.go
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/webdav/pkg/config/http.go
Labels: bug

#4767 [tests-only][full-ci]Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4805 [full-ci] [tests-only] Removed lines from expected failures
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#4831 [tests-only][full-ci]Bump middleware version to v1.8.2
  .drone.star
Labels: QA:team

#4837 refactor antivir templates
  services/notifications/pkg/email/templates/antivir/virusdetected.email.body.tmpl
  services/notifications/pkg/email/templates/antivir/virusdetected.email.subject.tmpl
  services/notifications/pkg/service/service.go
Labels: hacktoberfest-accepted

#4713 [tests-only][full-ci]Refactor expected-failure-api-on-ocis-file
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4862 [tests-only][full-ci] bump ownCloud core commit ID for the tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4718 [full-ci][tests-only]Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4920 Proxy env var description rephrasing
  services/proxy/pkg/config/config.go
Labels: Topic:Documentation

#4927 [tests-only][full-ci] Bump core commit id for tests
  .drone.env
Labels: QA:team

#4934 Update ADOC.tmpl
  docs/templates/ADOC.tmpl
Labels: Topic:Documentation

#4935 Add REVA_ env description for WebDav
  services/webdav/pkg/config/config.go
Labels: bug

#4938 fix typo in beta testplan
  docs/ocis/development/beta-testplan.md
Labels: QA:team
