Repository owncloud/ocis, pull requests merged in 2022-12, with the labels that each got.

#5166 [tests-only][full-ci]Bump commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5174 [tests-only]Update the expected to fail to use correct issue link
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5151 [tests-only][full-ci] Extend API contract tests for GET drives/spaces
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5192 Update storagedrivers.md
  docs/ocis/storage/storagedrivers.md
Labels: Status:Needs-Review

#5182 [tests-only][full-ci]Added test for `space` public link
  tests/acceptance/features/apiSpaces/publicLink.feature
Labels: QA:team

#5023 [full-ci] [tests-only] Added api test for sharing spaces to group
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5150 [full-ci] [tests-only] Added api test for edit user using graph API
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/RoleAssignmentContext.php
Labels: QA:team

#5228 [tests-only][full-ci] Bump core commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5230 [tests-only][fulll-ci] Bump core commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5226 [full-ci] [tests-only] Port api test
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/RoleAssignmentContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5187 [tests-only][full-ci] Add CORS API tests
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiCors/cors.feature
Labels: QA:team

#5236 [tests-only][full-ci] Add CORS API tests (#5187)
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiCors/cors.feature
Labels: QA:team

#5237 [tests-only][full-ci] Fix stable2 nightly CI trigger
  .drone.star
Labels: QA:team

#5220 [tests-only][full-ci] Bump commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5239 [tests-only][full-ci]Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5235 [tests-only][full-ci]Extended public link tests to have more checks
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
Labels: QA:team

#5232 [tests-only][full-ci]Add api tests public link folder download
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5241 [tests-only][full-ci]Bump commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5265 [tests-only][full-ci]Bump commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5274 Update README.md
  docs/helpers/README.md
Labels: Topic:Documentation

#5266 [tests-only] [full-ci] Refactor the response should contain
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/report.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5277 Fix the description of the postprocessing service
  services/postprocessing/pkg/config/config.go
Labels: Topic:Documentation

#5290 Add a toc to readme.md
  README.md
Labels: Topic:Documentation

#5291 Fix TOC because codacy
  README.md
Labels: Topic:Documentation

#5292 Improve extended env var description
  docs/helpers/extended_vars.yaml
  docs/templates/ADOC_global.tmpl
Labels: Topic:Documentation

#5294 Add blank comment lines
  protogen/gen/ocis/messages/settings/v0/settings.pb.go
  protogen/gen/ocis/services/thumbnails/v0/thumbnails.pb.go
Labels: Topic:Documentation

#5296 Update extended envvar yaml file
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#5298 Create extended_configvars.adoc
  services/_includes/adoc/extended_configvars.adoc
Labels: Topic:Documentation

#5252 [tests-only][full-ci]Extend Propfind of space to space-member
  tests/acceptance/features/apiContract/propfind.feature
Labels: QA:team

#5302 [tests-only][full-ci]Port api test for propfind to master
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/report.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5304 [tests-only][full-ci] Bump middleware v1.8.3
  .drone.star
Labels: QA:team

#5307 [tests-only][full-ci] Bump middleware version to v1.8.3
  .drone.star
Labels: QA:team

#5305 [tests-only][full-ci]Backport response should contain refactor to `master` branch
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/report.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5303 [tests-only][full-ci]Bump core latest commit id on ocis
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5308 [tests-only][full-ci]Backport expand propfind test for spacemember
  tests/acceptance/features/apiContract/propfind.feature
Labels: QA:team

#5238 [tests-only][full-ci]Bump commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5268 [full-ci][tests-only] Enable async uploads
  .drone.star
  go.mod
  go.sum
Labels: QA:team

#5312 [full-ci] Bump libre-graph-api-go and drive group permissions
  .drone.star
  changelog/unreleased/bump-libregraph.md
  changelog/unreleased/drive-group-permissions.md
  go.mod
  go.sum
  services/graph/pkg/service/v0/drives.go
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review

#5149 [tests-only][full-ci]Added test for getting user information by admin or normal user using Graph API
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team
