Repository owncloud/ocis, pull requests merged in 2022-11, with the labels that each got.

#4939 delete reference to issue 2131
  docs/ocis/development/beta-testplan.md
Labels: QA:team

#4944 [full-ci] [tests-only] Bump core commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4947 [full-ci] [tests-only] Refactored inter scenarios space
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature
  tests/acceptance/features/apiAccountsHashDifficulty/webDavPUTAuthInvalid.feature
  tests/acceptance/features/apiGraph/changeOwnPassword.feature
  tests/acceptance/features/apiGraph/createGroupCaseSensitive.feature
  tests/acceptance/features/apiSpaces/search.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/createFileFolderWhenSharesSpaceExist.feature
  tests/acceptance/features/apiSpacesShares/etagPropagation.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
Labels: QA:team

#4953 [full-ci] [tests-only] Bump core commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4978 [tests-only][full-ci] Remove passing copy-private-link test from expected failure
  tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md
Labels: QA:team

#4981 [docs-only] Auth basic readme fix env var rename
  changelog/unreleased/rename-authprovider.md
  services/auth-basic/README.md
  services/auth-basic/pkg/config/config.go
Labels: bug

#5007 [docs-only] update readme
  README.md
Labels: Topic:Documentation

#4992 [tests-only][full-ci] Add API tests for creating groups (graph API)
  .drone.env
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/createGroup.feature
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5046 [tests-only][full-ci]Bump core commit 2022-11-14
  .drone.env
Labels: QA:team

#5048 [full-ci] [tests-only] Added api test for sharing disabled space
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
Labels: QA:team

#5047 [full-ci] [tests-only] Added api test for sharing spaces with/out manager permission
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
Labels: QA:team

#5005 [tests-only][full-ci] Add API tests for getting groups and group members (graph API)
  .drone.env
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/createGroup.feature
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5051 Make permission and role ids unique
  services/settings/pkg/service/v0/service.go
  services/settings/pkg/service/v0/settings.go
  services/settings/pkg/store/defaults/defaults.go
Labels: bug

#5075 [tests-only][full-ci]Bump core latest commit-id
  .drone.env
Labels: QA:team

#5093 [tests-only][full-ci] Add API tests for adding user to group (graph API)
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5100 [full-ci] [tests-only] Share test expanded for permission 0, internal
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
Labels: QA:team

#5088 [tests-only][full-ci]Add api tests for changing role of a space
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5076 [tests-only][full-ci] Add API tests for deleting groups (graph API)
  .drone.env
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/deleteGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5109 Fix some env descriptions
  services/app-provider/pkg/config/config.go
  services/idp/pkg/config/config.go
  services/nats/pkg/config/config.go
  services/proxy/pkg/config/config.go
Labels: Topic:Documentation

#5101 [tests-only][full-ci] Add API tests for editing group displayName (graph API)
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/editGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5128 Update the docker-compose example for wopi
  deployments/examples/ocis_wopi/docker-compose.yml
Labels: Topic:Documentation

#5118 bump libre graph API to v1.0.0
  go.mod
  go.sum
Labels: Category:Nonfunctional, Topic:API

#5104 [tests-only][full-ci] Add API tests for removing user from groups (graph API)
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5084 [tests-only][full-ci]Added test to get user information with GraphAPI
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/getUserOwnInformation.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5155 [Docs] Fix minor typo
  docs/ocis/development/deprecating-variables.md
Labels: Topic:Documentation

#5102 [full-ci] [tests-only] Added api test for delete user using graph API
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team
