Repository owncloud/ocis, pull requests merged in 2022-02, with the labels that each got.

#3026 Adjust UserGroupFilter default to match latest reva changes
  storage/pkg/config/defaultconfig.go
Labels: Status:Needs-Review

#3044 [full-ci][tests-only] update expected failures after tus upload using spaces
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3083 [tests-only] [full-ci] bump core commit id to include 39743 feature name changes
  .drone.env
Labels: QA:team

#3080 Delete group memberships when deleting a user
  changelog/unreleased/fix-ldap-del-usermembership.md
  graph/pkg/identity/ldap.go
Labels: Status:Needs-Review

#3090 [tests-only] Fix sharing tests in parallel deployment tests
  .drone.star
  tests/parallelDeployAcceptance/expected-failures-API.md
  tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
Labels: QA:team

#3091 [tests-only] [full-ci] Fix expected-failures references
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#3089 [tests-only][full-ci]Add expected failure for spaces tests on apiWebDavEtagpropagation2 suite
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3105 [tests-only] [full-ci] bump commit id for core dav spaces refactor 39746
  .drone.env
Labels: QA:team

#3082 Use decorator pattern and allow more methods to be decorated
  thumbnails/pkg/server/grpc/server.go
  thumbnails/pkg/service/v0/decorators/base.go
  thumbnails/pkg/service/v0/decorators/instrument.go
  thumbnails/pkg/service/v0/decorators/logging.go
  thumbnails/pkg/service/v0/decorators/tracing.go
  thumbnails/pkg/service/v0/service.go
Labels: Status:Needs-Review

#3108 [full-ci][tests-only] Bump core commit id for tests
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3129 [docs-only] Add doc on running parallel deployment tests locally
  deployments/examples/oc10_ocis_parallel/.env
  deployments/examples/oc10_ocis_parallel/config/oc10/11-testing-app.sh
  deployments/examples/oc10_ocis_parallel/docker-compose.yml
  deployments/examples/oc10_ocis_parallel/testing/docker-compose-additions.yml
  deployments/examples/ocis_hello/docker-compose.yml
  deployments/examples/ocis_ldap/docker-compose.yml
  deployments/examples/ocis_s3/docker-compose.yml
  deployments/examples/ocis_traefik/docker-compose.yml
  deployments/examples/ocis_wopi/docker-compose.yml
  docs/ocis/development/testing.md
Labels: QA:team

#3143 [tests-only][full-ci] bump core commit to the latest upto `2022-02-10`
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3153 [tests-only] [full-ci] Bump CORE_COMMITID to include expected-failures linter
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#3148 [tests-only][full-ci]Adjust expected failure for api move suites
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3171 [tests-only][full-ci] bump core commit to the latest upto `2022-02-15`
  .drone.env
Labels: QA:team

#3168 Create space with description
  changelog/unreleased/change-use-description-during-space-creation.md
  go.mod
  go.sum
  graph/pkg/service/v0/drives.go
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review

#3172 [full-ci][tests-only] bump core commit id to the latest upto `2022-02-16`
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3186 [tests-only] [full-ci] Bump core commit id to include PR 39793 getPersonalSpaceIdForUser changes
  .drone.env
Labels: QA:team

#3185 [full-ci] Unify id format
  changelog/unreleased/unify-file-ids.md
  go.mod
  go.sum
  graph/pkg/service/v0/driveitems.go
  graph/pkg/service/v0/drives.go
  graph/pkg/service/v0/graph_test.go
Labels: Category:Change

#3194 [tests-only][full-ci]Bump core commit latest up to date 2022-02-18
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3201 add orderby name and lastModifiedDateTime
  changelog/unreleased/add-ordering-list-drives.md
  graph/pkg/service/v0/drives.go
  graph/pkg/service/v0/drives_test.go
  graph/pkg/service/v0/graph_test.go
  graph/pkg/service/v0/ordering.go
  sonar-project.properties
Labels: Status:Needs-Review

#3213 [tests-only]Bump core commit id to include PR 39812
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3215 [tests-only] [full-ci] Bump CORE_COMMITID to include core PR 39813
  .drone.env
Labels: QA:team

#3222 [tests-only] Bump core commit id on ocis to match latest
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3229 allow requesting capabilities from password protected links
  changelog/unreleased/fix-capabilities-for-public-links.md
  proxy/pkg/middleware/basic_auth.go
  proxy/pkg/middleware/basic_auth_test.go
Labels: Early-Adopter:CERN

#3217 Enh: First version of the notifications service
  changelog/unreleased/notifications-service.md
  notifications/cmd/notifications/main.go
  notifications/pkg/channels/channels.go
  notifications/pkg/command/health.go
  notifications/pkg/command/root.go
  notifications/pkg/command/server.go
  notifications/pkg/command/version.go
  notifications/pkg/config/config.go
  notifications/pkg/config/debug.go
  notifications/pkg/config/defaultconfig.go
  notifications/pkg/config/log.go
  notifications/pkg/config/parser/parse.go
  notifications/pkg/config/service.go
  notifications/pkg/logging/logging.go
  notifications/pkg/service/service.go
  ocis-pkg/config/config.go
  ocis-pkg/config/defaultconfig.go
  ocis/pkg/command/notifications.go
  ocis/pkg/runtime/service/service.go
Labels: Status:Needs-Review

#3219 support thumbnails in spaces
  changelog/unreleased/spaces-thumbnails.md
  thumbnails/pkg/service/v0/service.go
  thumbnails/pkg/thumbnail/imgsource/cs3.go
  webdav/pkg/dav/requests/thumbnail.go
  webdav/pkg/service/v0/service.go
Labels: Status:Needs-Review
