Repository owncloud/ocis, pull requests merged in 2022-01, with the labels that each got.

#2963 [tests-only][full-ci]Bump the commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2947 Add support for user creation and deletion to GraphAPI (LDAP backend)
  graph/pkg/config/config.go
  graph/pkg/config/defaultconfig.go
  graph/pkg/identity/backend.go
  graph/pkg/identity/cs3.go
  graph/pkg/identity/ldap.go
  graph/pkg/identity/ldap/reconnect.go
  graph/pkg/service/v0/instrument.go
  graph/pkg/service/v0/logging.go
  graph/pkg/service/v0/service.go
  graph/pkg/service/v0/tracing.go
  graph/pkg/service/v0/users.go
Labels: Status:Needs-Review

#2943 [tests-only][full-ci] adjust expected failures (apiFavorites)
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#2962 Read additional graph drive prop from space.yaml
  .bingo/Variables.mk
  .bingo/mockery.mod
  .bingo/mockery.sum
  .bingo/mutagen.sum
  .bingo/variables.env
  go.mod
  go.sum
  graph/Makefile
  graph/mocks/gateway_client.go
  graph/mocks/http_client.go
  graph/pkg/config/config.go
  graph/pkg/config/defaultconfig.go
  graph/pkg/service/v0/driveitems.go
  graph/pkg/service/v0/drives.go
  graph/pkg/service/v0/graph.go
  graph/pkg/service/v0/graph_suite_test.go
  graph/pkg/service/v0/graph_test.go
  graph/pkg/service/v0/instrument.go
  graph/pkg/service/v0/logging.go
  graph/pkg/service/v0/net/headers.go
  graph/pkg/service/v0/option.go
  graph/pkg/service/v0/service.go
  graph/pkg/service/v0/tracing.go
Labels: Category:Enhancement

#2978 add GetSingleDrive handler
  changelog/unreleased/single-space-enpoint.md
  graph/pkg/service/v0/drives.go
  graph/pkg/service/v0/graph.go
  graph/pkg/service/v0/service.go
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review

#3007 [full-ci] Shares folder should always be displayed
  .drone.env
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#3016 [tests-only] [full-ci] Bump core commit id for tests
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3051 [tests-only] [full-ci] Bump core commit id to include core PR 39728 test changes
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team
