Repository owncloud/ocis, pull requests merged in 2022-07, with the labels that each got.

#4085 [full-ci][tests-only]cache yarn dependencies for web UI tests
  .drone.star
Labels: QA:team

#4115 [full-ci] update reva to e2232b5a63df
  changelog/unreleased/update-reva-beta.5.md
  go.mod
  go.sum
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
  tests/parallelDeployAcceptance/expected-failures-API.md
Labels: Category:Enhancement

#4109 [tests-only] [full-ci] Do not skip tests for issue-3023
  .drone.star
Labels: QA:team

#4107 [tests-only] [full-ci] cache core repos for testing
  .drone.star
Labels: QA:team

#4170 [tests-only] [full-ci] Bump CORE_COMMITID for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4148 [full-ci] use spaceID
  .drone.star
  changelog/unreleased/space-id.md
  go.mod
  go.sum
  protogen/gen/ocis/messages/search/v0/search.pb.go
  protogen/gen/ocis/services/search/v0/search.swagger.json
  protogen/proto/ocis/messages/search/v0/search.proto
  services/audit/pkg/service/service_test.go
  services/graph/pkg/service/v0/driveitems.go
  services/graph/pkg/service/v0/drives.go
  services/graph/pkg/service/v0/graph_test.go
  services/search/pkg/search/index/index.go
  services/search/pkg/search/index/index_test.go
  services/search/pkg/search/provider/events.go
  services/search/pkg/search/provider/searchprovider.go
  services/webdav/pkg/dav/requests/thumbnail.go
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review, Topic:API

#4174 [tests-only] add tests for etag propagation on copy operation using spaces DAV
  tests/acceptance/features/apiSpaces/etagPropagation.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4205 [tests-only][full-ci]Bump CORE_COMMITID for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4112 [full-ci] [tests-only] Do not run full-ci on tagging
  .drone.star
Labels: QA:team

#4220 [tests-only] [full-ci] Remove tests related to issue-1328,1310,2249 from expected to fail
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#4243 [tests-only] [full-ci] Bump CORE_COMMITID for API tests
  .drone.env
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#4126 [tests-only][full-ci]Added test scenarios for copy Request
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/copySpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4238 [tests-only][full-ci]Cache web repo for tests
  .drone.star
Labels: QA:team

#4247 [tests-only] [full-ci] Do not fetch the retry script in CI
  .drone.star
Labels: QA:team

#4246 [full-ci][tests-only] Add retry option
  .drone.star
Labels: QA:team

#4264 [tests-only] [full-ci] Bump CORE_COMMITID for API tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4179 [tests-only][full-ci]Added implementation and Scenarios for `MOVE` request operation
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/moveSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4124 [full-ci] [tests-only] Using `plugins/s3-cache:1` instead of `meltwater/drone-cache:v1`
  .drone.star
Labels: QA:team

#4284 [tests-only][full-ci]Add Tests for creating Files and Folder When Space Shares Jail exists for core PR 40239
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/createFileFolderWhenSharesSpaceExist.feature
Labels: QA:team

#4292 [tests-only] remove closed issue #3167 from the list of expected failures
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4295 [tests-only] [full-ci] Bump commit id for core API tests
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4298 [tests-only] Enhance getSpaceByNameManager test code
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team
