Repository owncloud/ocis, pull requests merged in 2022-04, with the labels that each got.

#3435 Add owncloudsql config to authbasic
  changelog/unreleased/add-owncloudsql-config-to-authbasic.md
  storage/pkg/command/authbasic.go
Labels: Type:Bug

#3439 Fix golang api docs
  changelog/unreleased/fix-docs.md
  ocis-pkg/log/option.go
Labels: Type:Bug, Topic:Documentation

#3440 Make config dir configurable via `OCIS_CONFIG_DIR` env var
  changelog/unreleased/make-config-dir-configurable.md
  ocis-pkg/config/helpers.go
Labels: Category:Enhancement

#3384 [docs-only] manual testplan for ocis beta
  docs/ocis/development/beta-testplan.md
Labels: QA:team

#3469 [tests-only][full-ci] Bump core commit id for tests
  .drone.env
Labels: QA:team

#3471 [docs-only] IDP documentation for the beta testplan
  docs/ocis/development/beta-testplan.md
Labels: QA:team

#3473 [tests-only][full-ci] Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3328 [docs-only] ADR: Search query language, Indexing and API
  docs/ocis/adr/0018-file-search-api.md
  docs/ocis/adr/0019-file-search-index.md
  docs/ocis/adr/0020-file-search-query-language.md
Labels: Platform:oCIS, Category:Research, Status:Proposal, Interaction:Needs-Concept, Interaction:Discussion, Topic:API, Priority:p2-high, Topic:Dependencies

#3474 [full-ci] set demo users to default off
  .drone.star
  .vscode/launch.json
  accounts/pkg/config/defaults/defaultconfig.go
  changelog/unreleased/no-demo-users.md
  deployments/examples/oc10_ocis_parallel/.env
  deployments/examples/oc10_ocis_parallel/docker-compose.yml
  deployments/examples/ocis_hello/.env
  deployments/examples/ocis_hello/docker-compose.yml
  deployments/examples/ocis_individual_services/.env
  deployments/examples/ocis_individual_services/docker-compose.yml
  deployments/examples/ocis_keycloak/.env
  deployments/examples/ocis_keycloak/docker-compose.yml
  deployments/examples/ocis_ldap/.env
  deployments/examples/ocis_ldap/docker-compose.yml
  deployments/examples/ocis_s3/.env
  deployments/examples/ocis_s3/docker-compose.yml
  deployments/examples/ocis_traefik/.env
  deployments/examples/ocis_traefik/docker-compose.yml
  deployments/examples/ocis_wopi/.env
  deployments/examples/ocis_wopi/docker-compose.yml
  docs/ocis/deployment/_index.md
  docs/ocis/getting-started/_index.md
  docs/ocis/getting-started/demo-users.md
  idm/pkg/config/defaults/defaultconfig.go
Labels: Topic:Security, Category:Change, Status:Needs-Review

#3510 [full-ci][tests-only] Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#3553 Remove jarnaiz/behat-junit-formatter from acceptance tests
  composer.json
  tests/acceptance/config/behat.yml
  tests/parallelDeployAcceptance/config/behat.yml
  vendor-bin/behat/composer.json
Labels: QA:team

#3560 [tests-only][full-ci] Remove passing test from expected to fail
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#3518 [test-only]apiTest: create public link to file with edit permissions
  tests/acceptance/features/apiSpaces/shareSpaces.feature
  tests/acceptance/features/apiSpaces/shareSubItemOfSpaceViaPublicLink.feature
Labels: Status:Needs-Review

#3576 [tests-only] [full-ci] Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-graphAPI-on-OCIS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#3609 [tests-only] bump owncloud-test-middleware version to v1.5.0
  .drone.star
Labels: QA:team
