Repository owncloud/ocis, pull requests merged in 2022-09, with the labels that each got.

#4499 [full-ci][tests-only]Bump commit id for tests
  .drone.env
Labels: QA:team

#4502 [tests-only] Hardcode header in GraphHelper::deleteSpace
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4373 [tests-only][full-ci]Add `/Shares` related copy tests on ocis which are removed from core
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/copySpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4492 [tests-only][full-ci]Reuse code from code for `favorites.feature` in ocis
  .drone.env
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4510 [tests-only][full-ci]Reuse locking method from core
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4463 [tests-only] Api test. fix search test
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/search.feature
Labels: Status:Needs-Review

#4440 [tests-only] Add api tests for tus upload when quota is set
  .drone.env
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
  tests/acceptance/features/bootstrap/TusContext.php
  tests/acceptance/filesForUpload/example.gif
  tests/acceptance/filesForUpload/qrcode.png
  tests/acceptance/filesForUpload/testavatar.jpg
Labels: QA:team

#4531 [tests-only]Add context in behat.yml
  tests/acceptance/config/behat.yml
Labels: QA:team

#4527 [full-ci][tests-only]Refactor expected-failure file
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4519 [tests-only][full-ci]Add coding standard php pipeline
  .drone.star
  .php-cs-fixer.dist.php
  Makefile
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
Labels: QA:team

#4535 [full-ci][tests-only]Refactor and Reuse code from core
  tests/acceptance/features/apiSpaces/favorite.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4536 [tests-only][full-ci]Reuse code from core
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4400 [tests-only][full-ci]Add /Shares related move tests on ocis which are removed from core
  tests/acceptance/features/apiSpaces/moveSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4546 [tests-only][full-ci]Remove lock on folder tests for spaces
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/lockSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4538 [tests-only][full-ci]Reuse code from core for `shareOperation`
  tests/acceptance/features/apiSpaces/shareOperations.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4549 [tests-only][full-ci] Bump Core commit for 2022-09-09
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4556 [tests-only][full-ci]Skip ocis specific tests in reva
  tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature
  tests/acceptance/features/apiAccountsHashDifficulty/webDavPUTAuthInvalid.feature
Labels: QA:team

#4438 enable a 300sec in memory cache for resource infos when listing shares on the ocs API
  services/frontend/pkg/config/config.go
  services/frontend/pkg/config/defaults/defaultconfig.go
  services/frontend/pkg/revaconfig/config.go
Labels: Type:Bug

#4566 [tests-only][full-ci]Bump core commit id for tests
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4579 fix search report webdav permissions
  changelog/unreleased/fix-search-webdav-permissions.md
  services/search/pkg/search/provider/searchprovider.go
Labels: bug

#4580 [tests-only][full-ci]Check for the undefined steps after update on core
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4562 [docs-only] update sharing docs
  docs/services/frontend/_index.md
  docs/services/sharing/_index.md
Labels: Topic:Documentation

#4577 [tests-only][full-ci]Reuse the core code
  .drone.env
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/copySpaces.feature
  tests/acceptance/features/apiSpaces/createFileFolderWhenSharesSpaceExist.feature
  tests/acceptance/features/apiSpaces/download.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/moveSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/apiSpaces/search.feature
  tests/acceptance/features/apiSpaces/shareSpaces.feature
  tests/acceptance/features/apiSpaces/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpaces/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpaces/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4609 [Docs] Fixing the adoc template
  docs/templates/ADOC.tmpl
Labels: Topic:Documentation

#4613 [tests-only][full-ci]Bump core commit id
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4470 [full-ci] [tests-only] Move tests from `core` to `oCIS` related to `/Shares` of TUS upload
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/shareUploadTUS.feature
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
Labels: QA:team

#4639 Update Notification Service eMail Template env var description
  services/notifications/pkg/config/config.go
Labels: Category:Enhancement

#4614 [tests-only][full-ci]Check for issue not mentioned to a test
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Labels: QA:team

#4665 [docs] Add a blank to type and default value pass thru
  docs/templates/ADOC.tmpl
Labels: Topic:Documentation

#4560 [full-ci][tests-only]Run ocis tests without testing-app
  .drone.env
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#4655 [ci] fix restore for web cache
  .drone.star
  tests/config/drone/check_web_cache.sh
Labels: QA:team

#4689 update reva to 20220926161629
  go.mod
  go.sum
Labels: bug

#4696 [tests-only][full-ci]Refactor download archive related scenario
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiArchiver/downloadByPath.feature
Labels: QA:team

#4708 [docs-only]Improve the documentation for NFS share
  docs/ocis/storage-backends/dcfsnfs.md
Labels: Topic:Documentation

#4707 [full-ci] [tests-only] `share` related tests separated to `apiSpacesShares` suite
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
  tests/acceptance/features/apiSpacesShares/checksum.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/createFileFolderWhenSharesSpaceExist.feature
  tests/acceptance/features/apiSpacesShares/etagPropagation.feature
  tests/acceptance/features/apiSpacesShares/favorite.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
Labels: QA:team

#4709 [docs-only] Fix path name in ocis_s3 docs
  docs/ocis/deployment/ocis_s3.md
Labels: Topic:Documentation

#4710 [tests-only] Remove the propfind method
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#4721 [tests-only][full-ci]Bump core commit id for tests
  .drone.env
Labels: QA:team
