Repository owncloud/ocis, pull requests merged in 2023-08, with the labels that each got.

#6923 Replacing implicit grpc client initialization with explicit package local variables
  ocis-pkg/service/grpc/client.go
  ocis-pkg/service/grpc/service.go
  ocis/pkg/command/server.go
  services/eventhistory/pkg/command/server.go
  services/eventhistory/pkg/config/config.go
  services/eventhistory/pkg/server/grpc/server.go
  services/graph/pkg/command/server.go
  services/graph/pkg/service/v0/application_test.go
  services/graph/pkg/service/v0/approleassignments_test.go
  services/graph/pkg/service/v0/driveitems_test.go
  services/graph/pkg/service/v0/educationclasses_test.go
  services/graph/pkg/service/v0/educationschools_test.go
  services/graph/pkg/service/v0/educationuser_test.go
  services/graph/pkg/service/v0/groups_test.go
  services/graph/pkg/service/v0/users_test.go
  services/notifications/pkg/service/service_test.go
  services/policies/pkg/command/server.go
  services/search/pkg/command/server.go
  services/search/pkg/config/config.go
  services/search/pkg/server/grpc/server.go
  services/settings/pkg/command/server.go
  services/settings/pkg/config/config.go
  services/settings/pkg/server/grpc/server.go
  services/store/pkg/command/server.go
  services/store/pkg/config/config.go
  services/store/pkg/server/grpc/server.go
Labels: Status:Needs-Review

#6931 [tests-only][full-ci] Fix preview test scenario
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/fixtures/unicode-fixture.png
  tests/config/drone/NotoSans.ttf
  tests/config/drone/fontsMap.json
Labels: QA:team

#6665 [tests-only][full-ci] added scenarios for disabling frontend_enable_resharing
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiReshare/disableReshare.feature
Labels: QA:team

#6932 [tests-only][full-ci] Fix preview test scenario (#6931)
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/fixtures/unicode-fixture.png
  tests/config/drone/NotoSans.ttf
  tests/config/drone/fontsMap.json
Labels: QA:team

#6936 [tests-only][full-ci] move resharing.feature from apiSpaces to apiReshare
  tests/acceptance/features/apiReshare/resharing.feature
Labels: QA:team

#6937 [tests-only][full-ci] added scenarios for disabling frontend_enable_resharing (#6665)
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiReshare/disableReshare.feature
Labels: QA:team

#6940 [tests-only][full-ci] Update local test docker-compose setup to allow unicode preview tests
  docs/ocis/development/testing.md
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/ocis-base.yml
Labels: QA:team

#6943 [tests-only][full-ci] Update local test docker-compose setup to allow unicode preview tests (#6940)
  docs/ocis/development/testing.md
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/ocis-base.yml
Labels: QA:team

#6942 [tests-only][full-ci] move resharing.feature from apiSpaces to apiReshare (#6936)
  tests/acceptance/features/apiReshare/resharing.feature
Labels: QA:team

#6930 [tests-only][full-ci] refactored acceptance test code to store response data related to public shares on single store
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#6959 [tests-only][full-ci] Remove `@skipOnStable2.0` tag
  tests/acceptance/features/apiGraph/assignRole.feature
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getApplications.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
Labels: QA:team

#6963 [tests-only][full-ci] Remove `@skipOnStable2.0` tag
  tests/acceptance/features/apiGraph/assignRole.feature
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getApplications.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
Labels: QA:team

#6853 [tests-only][full-ci]add api test for search files using tag in project spaces
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiGraph/fullSearch.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6941 Convert webfinger to use service trace provider.
  services/webfinger/pkg/command/server.go
  services/webfinger/pkg/config/tracing.go
  services/webfinger/pkg/service/v0/tracing.go
  services/webfinger/pkg/tracing/tracing.go
Labels: Status:Needs-Review

#6969 [tests-only][full-ci]Backport search project space files using context
  tests/acceptance/features/apiGraph/fullSearch.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6972 [tests-only][full-ci] added test scenario for searching inside folder in space
  tests/acceptance/features/apiSpaces/search.feature
  tests/acceptance/features/bootstrap/SearchContext.php
Labels: QA:team

#6980 [tests-only][full-ci] Backport searching inside folder in personal space(#6949)
  tests/acceptance/features/apiGraph/fullSearch.feature
  tests/acceptance/features/bootstrap/SearchContext.php
Labels: QA:team

#6974 [tests-only][full-ci]add test for search version restored files by tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6968 [tests-only][full-ci]add test for search project folders by tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6988 Add missing tracing initialization for graph service
  services/graph/pkg/command/server.go
  services/graph/pkg/server/http/server.go
  services/webdav/pkg/command/server.go
  services/webdav/pkg/config/tracing.go
  services/webdav/pkg/server/http/option.go
  services/webdav/pkg/server/http/server.go
  services/webdav/pkg/service/v0/option.go
  services/webdav/pkg/service/v0/service.go
  services/webdav/pkg/service/v0/tracing.go
  services/webdav/pkg/tracing/tracing.go
Labels: Status:Needs-Review

#6984 [tests-only][full-ci] Backport add test for search version restored files by tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6957 [tests-only][full-ci] removed api tag from antivirus test
  Makefile
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/run.sh
Labels: QA:team

#6970 [tests-only][full-ci]add test for search version restored files by content
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6996 [tests-only][full-ci]Backport search folder by tag in project space
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#7004 [docs-only] Add mdns as supported value in MICRO_REGISTRY envvar description
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#6987 [tests-only][full-ci]add test for search project space files by content
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6806 Disabled revokeRefreshToken in Keycloak config
  deployments/examples/ocis_keycloak/config/keycloak/ocis-realm.dist.json
Labels: Status:Needs-Review

#7015 ci: do not skip sonarcloud and codacy even if golint and unit-tests are skipped
  .drone.star
Labels: QA:team

#7011 Remove unused reva tracing initialization.
  ocis-pkg/tracing/tracing.go
Labels: Status:Needs-Review

#7030 [tests-only][full-ci]Backport search version restored files by content
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#7037 [tests-only][full-ci]backport of add test for search project space files by content
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6982 [tests-only][full-ci] added test scenario for searching inside folder in shares
  tests/acceptance/features/apiSpaces/search.feature
Labels: QA:team

#7039 [tests-only][full-ci]add test for sharee searches project spaces files by content
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#7053 [tests-only][full-ci] removing the scenario and adding a example table
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
Labels: QA:team

#7054 [tests-only][full-ci]backport add test for sharee searches project spaces files by content
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#7055 ci: do not skip sonar and codacy in ci (#7015)
  .drone.star
Labels: QA:team

#7059 [tests-only][full-ci] Run apiAccountsHashDifficulty test suite with default hash difficulty
  .drone.star
Labels: QA:team

#7058 [tests-only][full-ci] Backport search inside folder shares and spaces
  tests/acceptance/features/apiSpaces/search.feature
  tests/acceptance/features/bootstrap/SearchContext.php
Labels: QA:team

#6958 [test-only][full-ci] added tests for reading content of a file by fileId using WebDav API
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7036 [tests-only][full-ci]add test for sharee searches project spaces files using a tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#7064 [tests-only] [full-ci] Backport access file using file id
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7066 [tests-only][full-ci]backport add test for sharee searches project spaces files using a tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#7065 [tests-only][full-ci] adding test for deprovisioning notification using different date format
  tests/acceptance/features/apiNotification/deprovisioningNotification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#7051 [tests-only][full-ci]refactoring the tag creating step using data table
  tests/acceptance/features/apiGraph/fullSearch.feature
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#7070 [tests-only][full-ci] adding test for deprovisioning notification
  tests/acceptance/features/apiNotification/deprovisioningNotification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#7074 [tests-only][full-ci]Backport refactoring the tag creating step using data table
  tests/acceptance/features/apiGraph/fullSearch.feature
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#7075 Partially revert removal of believed unused reva tracing initialization.
  ocis-pkg/tracing/tracing.go
Labels: Status:Needs-Review

#7076 [tests-only][full-ci] removed a scenario and added a example table
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
Labels: QA:team

#7014 Update sharing and ocdav tracing.
  ocis-pkg/tracing/tracing.go
  services/ocdav/pkg/command/server.go
  services/ocdav/pkg/config/config.go
  services/ocdav/pkg/config/tracing.go
  services/ocdav/pkg/tracing/tracing.go
  services/sharing/pkg/command/server.go
  services/sharing/pkg/config/config.go
  services/sharing/pkg/config/tracing.go
  services/sharing/pkg/revaconfig/config.go
  services/sharing/pkg/tracing/tracing.go
Labels: Status:Needs-Review

#7081 [tests-only]Update expected to fail file to link failing tests to correct issue
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#7080 Re-enable commented out tracing in frontend.
  services/frontend/pkg/command/server.go
Labels: Status:Needs-Review

#6826 Raised default wopiserver version to 10.1.0
  .drone.star
  deployments/examples/ocis_wopi/docker-compose.yml
Labels: Status:Needs-Review

#7078 [tests-only][full-ci]add `skipOnStable3.0` and single step for creating tag on files
  tests/acceptance/features/apiFullTextSearch/search.feature
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#7073 [tests-only][full-ci] refactored the test and added skipOnStable 3.0 tag on deprovisioning notification test
  tests/acceptance/features/apiNotification/deprovisioningNotification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
  tests/acceptance/features/bootstrap/SettingsContext.php
Labels: QA:team

#7086 [tests-only][full-ci]Backport adding skip on stable3.0
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#7090 [tests-only] Backport/7081
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#7095 [tests-only] Fix the test step keyword ordering
  tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature
Labels: QA:team

#7101 [tests-only][backport] Fix the test step ordering
  tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature
Labels: QA:team

#7110 Add missing tracing references to multiple services.
  services/eventhistory/pkg/server/grpc/server.go
  services/graph/pkg/server/http/server.go
  services/graph/pkg/service/v0/service.go
  services/ocdav/pkg/command/server.go
  services/proxy/pkg/command/server.go
  services/search/pkg/server/grpc/server.go
  services/search/pkg/service/grpc/v0/option.go
  services/search/pkg/service/grpc/v0/service.go
  services/storage-users/pkg/command/server.go
  services/store/pkg/command/server.go
  services/store/pkg/config/tracing.go
  services/store/pkg/server/grpc/option.go
  services/store/pkg/server/grpc/server.go
  services/store/pkg/tracing/tracing.go
  services/thumbnails/pkg/command/server.go
  services/thumbnails/pkg/server/grpc/server.go
  services/thumbnails/pkg/server/http/option.go
  services/thumbnails/pkg/server/http/server.go
  services/thumbnails/pkg/service/http/v0/option.go
  services/thumbnails/pkg/service/http/v0/service.go
  services/thumbnails/pkg/service/http/v0/tracing.go
  services/userlog/pkg/server/http/server.go
  services/web/pkg/server/http/server.go
  services/webdav/pkg/server/http/server.go
  services/webdav/pkg/service/v0/service.go
  services/webfinger/pkg/command/server.go
  services/webfinger/pkg/server/http/option.go
  services/webfinger/pkg/server/http/server.go
Labels: Status:Needs-Review

#6990 [tests-only][full-ci] added test to update file using file id
  tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#7116 Add tracing to policies service
  services/policies/pkg/command/server.go
  services/policies/pkg/config/config.go
  services/policies/pkg/config/defaults/defaultconfig.go
  services/policies/pkg/config/tracing.go
  services/policies/pkg/service/event/service.go
Labels: Status:Needs-Review

#7130 [tests-only][full-ci] Backport added test to update file using file id
  tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#7131 [docs-only] Update deprecating-variables.md
  docs/ocis/development/deprecating-variables.md
Labels: Topic:Documentation

#7133 Forgotten wrong deprecation version fix (3.1 --> 4.0.0)
  ocis-pkg/config/config.go
  ocis-pkg/shared/shared_types.go
Labels: Topic:Documentation

#7134 Update app icon example URL's
  docs/services/app-registry/apps.md
Labels: Status:Needs-Review

#7139 [tests-only][full-ci] move files in `apiFullTextSearch` suites and renamed suites as `apiSearch`
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSearch/apiSpaceSearch.feature
  tests/acceptance/features/apiSearch/contentSearch.feature
  tests/acceptance/features/apiSearch/tagSearch.feature
Labels: QA:team
