Repository owncloud/ocis, pull requests merged in 2023-11, with the labels that each got.

#7619 [tests-only][full-ci]Add tests for searching for resources with whitespace chars in its name
  tests/acceptance/features/apiSearch/apiSpaceSearch.feature
Labels: QA:team

#7628 [test-only] [full-ci] Backport lock tests
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/lockFiles.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#7627 [tests-only][full-ci] Add test for copy file between personal space and share space using fileID
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#7642 [tests-only][full-ci] Backport add test on copy between file id share space and personal space
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#7645 [tests-only][full-ci]Move lock related tests to new suites
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiLocks/lockFiles.feature
Labels: QA:team

#7639 [tests-only][full-ci]Added script to check the deleted suites in the expected to failure
  .drone.star
  tests/acceptance/check-deleted-suites-in-expected-failure.sh
Labels: QA:team

#7650 [tests-only][full-ci]Backport of check for deleted scenarios in expected to failure file
  .drone.star
  tests/acceptance/check-deleted-suites-in-expected-failure.sh
Labels: QA:team

#7655 [docs-only] Update search README.md
  services/search/README.md
Labels: Topic:Documentation

#7647 [tests-only][full-ci] Add test for copy file between project spaces
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#7488 [docs-only] Fix web service envvar text
  services/web/pkg/config/options.go
Labels: Topic:Documentation

#7654 [docs-only] Text fix for thumbnail README.md
  services/thumbnails/README.md
Labels: Topic:Documentation

#7640 [tests-only ][full-ci] backport all graphapi related featurefile wording
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiContract/copy.feature
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/spacesReport.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/apiDownloads/spaceDownload.feature
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/apiNotification/spaceNotification.feature
  tests/acceptance/features/apiReshare/resharing.feature
  tests/acceptance/features/apiSearch/apiSpaceSearch.feature
  tests/acceptance/features/apiSearch/contentSearch.feature
  tests/acceptance/features/apiSearch/tagSearch.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/lockFiles.feature
  tests/acceptance/features/apiSpaces/publicLink.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/trashBin.feature
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#7665 [tests-only][full-ci] Backport add test on copy between spaces in project spaces
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#7688 [docs-only] Fix some Audit envvar description texts
  services/audit/pkg/config/config.go
Labels: Topic:Documentation

#7690 [docs-only] Fix envvars with a duration.
  services/eventhistory/pkg/config/config.go
  services/frontend/pkg/config/config.go
  services/gateway/pkg/config/config.go
  services/graph/pkg/config/application.go
  services/graph/pkg/config/cache.go
  services/policies/pkg/config/config.go
  services/postprocessing/pkg/config/config.go
  services/proxy/pkg/config/config.go
  services/settings/pkg/config/config.go
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/userlog/pkg/config/config.go
  services/web/pkg/config/options.go
Labels: Topic:Documentation

#7699 [docs-only] Fix envvars with a array slice ([]string)
  services/auth-basic/pkg/config/config.go
  services/eventhistory/pkg/config/config.go
  services/frontend/pkg/config/config.go
  services/gateway/pkg/config/config.go
  services/graph/pkg/config/cache.go
  services/graph/pkg/config/config.go
  services/idp/pkg/config/config.go
  services/invitations/pkg/config/http.go
  services/ocdav/pkg/config/config.go
  services/ocs/pkg/config/http.go
  services/postprocessing/pkg/config/config.go
  services/proxy/pkg/config/config.go
  services/settings/pkg/config/config.go
  services/settings/pkg/config/http.go
  services/sse/pkg/config/config.go
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/thumbnails/pkg/config/config.go
  services/userlog/pkg/config/config.go
  services/web/pkg/config/http.go
  services/web/pkg/config/options.go
  services/webdav/pkg/config/http.go
  services/webfinger/pkg/config/config.go
  services/webfinger/pkg/config/http.go
Labels: Topic:Documentation

#7704 [docs-only] fix changelog template for the date field
  changelog/CHANGELOG.tmpl
Labels: Topic:Documentation

#7710 [docs-only] Fix ocm service envvar descriptions
  services/ocm/pkg/config/config.go
Labels: Topic:Documentation

#7714 allow configuring loadUserInfo for web
  services/web/pkg/config/config.go
  services/web/pkg/config/defaults/defaultconfig.go
Labels: Category:Enhancement

#7719 [docs-only] Typo fix in OCM service example
  services/ocm/README.md
Labels: Topic:Documentation

#7707 [tests-only] wait for few seconds before listing tags
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#7728 fix typo in test
  tests/acceptance/features/apiNotification/notification.feature
Labels: QA:team

#7722 [docs-only] Add WOPI image to dev docs
  docs/ocis/deployment/ocis_and_wopi_drawio.svg
  docs/ocis/deployment/ocis_wopi.md
Labels: Topic:Documentation

#7733 [tests-only] wait 5 seconds before performing search
  tests/acceptance/features/bootstrap/SearchContext.php
Labels: QA:team

#7745 [tests-only][full-ci] bump test-middleware to 1.8.7
  .drone.star
Labels: QA:team

#7755 [tests-only] unskip lastmonth date search API test
  tests/acceptance/features/apiSearch/dateSearch.feature
Labels: QA:team

#7698 [tests-only][full-ci] Add test for unlocking project space file
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#7606 [tests-only][full-ci] Add tests for move file within shares using file-id
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7759 [tests-only] stop ocis server with sigint to allow gracefull shutdown
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#7769 [tests-only][full-ci] move tests `coreApiWebdavLocksUnlock/unlockSharingToShares.feature` from to local api
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
Labels: QA:team

#7735 [tests-only] Retry listing roles if the response body is invalid
  tests/acceptance/features/bootstrap/SettingsContext.php
Labels: QA:team

#7771 [docs-only] Add documentation for proxy routes
  services/proxy/README.md
Labels: Topic:Documentation

#7777 [tests-only][full-ci]tests: add tests for lock expiration
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#7779 [full-ci] [tests-only] Added @env-config tags
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
Labels: QA:team

#7637 [tests-only][full-ci] Add test for rename and move the file between personal and share space using fileid
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7751 enhancement: make use of unified role for the graph invitation endpoint
  changelog/5.0.0_2023-11-22/enhancement-sharing-ng.md
  services/graph/pkg/service/v0/driveitems.go
  services/graph/pkg/service/v0/driveitems_test.go
  services/graph/pkg/unifiedrole/unifiedrole.go
  services/graph/pkg/unifiedrole/unifiedrole_test.go
  services/graph/pkg/validate/libregraph.go
  services/graph/pkg/validate/libregraph_test.go
  services/graph/pkg/validate/validate.go
  services/graph/pkg/validate/validate_suite_test.go
Labels: Status:Needs-Review

#7786 [full-ci] [tests-only] Skip test that won't run for reva-edge
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#7780 [tests-only]tests: add tests for unlocking using file id
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#7653 [tests-only][full-ci] Add test for move and rename file between space in project-space
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7776 [tests-only][full-ci] Backport add step move for shares with file
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7646 [tests-only][full-ci] removing the setResponse() in given/then step in GraphContext
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#7806 [tests-only] Unskip share test
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
Labels: QA:team

#7397 [tests-only] Extended test coverage for depth:infinity enabled config
  tests/acceptance/features/apiDepthInfinity/propfind.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#7807 [tests-only][full-ci]add tests for move rename file between personal and project space with file id
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7789 [tests-only][full-ci]tests: add test for lock/unlock in public link share
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#7813 [tests-only][full-ci] Backport add test for rename and move the file between personal and share space using fileid
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7816 [tests-only][full-ci] Backport add test for move and rename file between space in project-space
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7817 [tests-only][full-ci] tests: add api tests for changing system language using graph api
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiNotification/deprovisioningNotification.feature
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/apiNotification/spaceNotification.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/SettingsContext.php
Labels: QA:team

#7822 [tests-only][full-ci] removing the setResponse() and $this->response in given/then step in FeatureContext file
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#7380 [tests-only][full-ci] refactoring user remove from group test code
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
Labels: QA:team

#7835 [tests-only][full-ci]tests: refactor send profind request to space function
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#7836 [tests-only][full-ci]add tests for search files using media type
  tests/acceptance/features/apiSearch/mediaTypeSearch.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team
