Repository owncloud/ocis, pull requests merged in 2023-06, with the labels that each got.

#6430 [tests-only][full-ci]Use `traits` in correct way for `JsonAssertion`
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/NotificationContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6405 [tests-only][full-ci] Add acceptance tests for antivirus
  .drone.star
  docs/ocis/development/testing.md
  tests/TestHelpers/HttpRequestHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiAsyncUpload/delayPostprocessing.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
  tests/acceptance/filesForUpload/filesWithVirus/eicar.com
  tests/acceptance/filesForUpload/filesWithVirus/eicar_com.zip
  tests/acceptance/filesForUpload/filesWithVirus/eicarcom2.zip
Labels: QA:team

#6408 [tests-only] [full-ci] Adjust test method tryToDeleteFileFromTrashbin
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: QA:team

#6402 [tests-only][full-ci]Add step to set quota with env `OCIS_SPACES_MAX_QUOTA`
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/bootstrap/OcisConfigContext.php
Labels: QA:team

#6458 [docs-only] GRAPH_APPLICATION_ID envvar text fix
  services/graph/pkg/config/application.go
Labels: Topic:Documentation

#6467 [tests-only] Skip antivirus related tests in reva
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6468 [docs-only]fix path in documentation
  docs/ocis/deployment/ocis_s3.md
Labels: QA:team

#6442 [tests-only] [full-ci]refactoring feature files
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
  tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
  tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
  tests/acceptance/features/coreApiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties1/createFileFolder.feature
  tests/acceptance/features/coreApiWebdavProperties1/getQuota.feature
  tests/acceptance/features/coreApiWebdavProperties1/setFileProperties.feature
  tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/creationWithUploadExtension.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/lowLevelCreationExtension.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/lowLevelUpload.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/optionsRequest.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
Labels: QA:team

#6434 [tests-only] [full-ci] Test comma-separated list of tags
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6424 [tests-only] [full-ci] refactored feature files
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavDelete/deleteFolderContents.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/restoreFromTrash.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/restoreVersion.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/coreApiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/coreApiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/coreApiWebdavLocks2/independentLocks.feature
  tests/acceptance/features/coreApiWebdavLocks2/independentLocksShareToShares.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
Labels: QA:team

#6372 [tests-only][full-ci]Extend tests scenario for space notification
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/apiNotification/spaceNotification.feature
  tests/acceptance/features/apiSpaces/notification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6454 [tests-only][full-ci]add test for antivirus public link
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6488 [docs-only] Fix some envvar descriptions
  services/auth-basic/pkg/config/config.go
  services/frontend/pkg/config/config.go
  services/graph/pkg/config/config.go
  services/groups/pkg/config/config.go
  services/idp/pkg/config/config.go
  services/invitations/pkg/config/config.go
  services/invitations/pkg/config/http.go
  services/ocdav/pkg/config/config.go
  services/ocs/pkg/config/http.go
  services/settings/pkg/config/http.go
  services/storage-users/pkg/config/config.go
  services/userlog/pkg/config/config.go
  services/users/pkg/config/config.go
  services/web/pkg/config/http.go
  services/webdav/pkg/config/http.go
  services/webfinger/pkg/config/http.go
Labels: Topic:Documentation

#6489 [docs-only] Fix adoc global template
  docs/templates/ADOC_global.tmpl
Labels: Topic:Documentation

#6439 [tests-only]Add configuration for antivirus in docker compose for tests
  docs/ocis/development/testing.md
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/antivirus.yml
  tests/acceptance/docker/src/ocis-base.yml
Labels: QA:team

#6499 [tests-only] [full-ci] Update PHP API test dependencies
  composer.json
  vendor-bin/behat/composer.json
Labels: QA:team

#6463 [tests-only][full-ci]add test for antivirus user group sharing
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6485 [tests-only][full-ci]Add test for antivirus project spaces
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6484 [tests-only][full-ci]add tests setting ANTIVIRUS_MAX_SCAN_SIZE env
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/filesForUpload/filesWithVirus/eicarcom2.zip
Labels: QA:team

#6527 [tests-only][full-ci]Back port spaces max quota feature
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/bootstrap/OcisConfigContext.php
Labels: QA:team

#6506 [tests-only][full-ci]update public sharing test for zip virus file
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6508 [tests-only][full-ci]Backport/tests related to antivirus service
  docs/ocis/development/testing.md
  tests/acceptance/config/behat.yml
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/antivirus.yml
  tests/acceptance/docker/src/ocis-base.yml
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/filesForUpload/filesWithVirus/eicarcom2.zip
Labels: QA:team

#6450 [tests-only][full-ci]Added scenarios for quota exceed with API
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6523 [tests-only][full-ci]Test/antivirus testnotificationlanguage
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6521 [tests-only][full-ci]add test for creating a version file with virus content
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6532 [tests-only][full-ci]Throw proper ocis-wrapper connection error message
  tests/TestHelpers/OcisConfigHelper.php
Labels: QA:team

#6535 [tests-only][full-ci]add test for creating a version file with virus …
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6543 Fix nullpointer problems
  services/notifications/pkg/command/server.go
  services/notifications/pkg/config/config.go
Labels: Status:Needs-Review

#6534 [tests-only] [full-ci]Added antivirus notification tests for different languages (#6523)
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6569 Update APP_PROVIDER_SERVICE_NAME description
  services/app-provider/pkg/config/config.go
Labels: Topic:Documentation

#6573 [tests-only][full-ci] use tcp for antivirus service in ci
  .drone.star
  tests/acceptance/docker/src/antivirus.yml
  tests/acceptance/docker/src/ocis-base.yml
Labels: QA:team

#6585 [tests-only][full-ci]Backport/antivirus refactoring pr
  .drone.star
  docs/ocis/development/testing.md
  tests/acceptance/docker/src/antivirus.yml
  tests/acceptance/docker/src/ocis-base.yml
Labels: QA:team

#6498 [tests-only]Add test for ANTIVIRUS_INFECTED_FILE_HANDLING
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6471 Add missing span kind for tracing.
  services/idp/pkg/middleware/static.go
  services/invitations/pkg/service/v0/tracing.go
  services/ocs/pkg/middleware/logtrace.go
  services/thumbnails/pkg/service/grpc/v0/decorators/tracing.go
  services/webfinger/pkg/service/v0/tracing.go
Labels: Status:Needs-Review

#6588 [tests-only] Use different image of clamav in docker compose
  tests/acceptance/docker/src/antivirus.yml
Labels: QA:team

#6409 [tests-only] [full-ci] API test for enforce password config and update the public share to edit permission
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
Labels: QA:team

#6592 [tests-only]Backport/use different clamav image docker compose
  tests/acceptance/docker/src/antivirus.yml
Labels: QA:team

#6598 [tests-only][full-ci] Backport enforce password test scenarios
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
Labels: QA:team

#6586 [tests-only][full-ci]added scenario for overwrite file with virus content in a public link
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6600 [tests-only][full-ci] test for overwriting a file with virus content in group share
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6609 [tests-only][full-ci]Add tests for checking response of REPORT request in project spaces
  tests/acceptance/features/apiContract/spacesReport.feature
Labels: QA:team

#6607 [tests-only] added scenarios for overwrite file with virus content in user share
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6615 [tests-only][full-ci] added antivirus test for overwriting the .space/readme.md file
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6610 [tests-only][full-ci] Back port PR's related to antivirus service api tests
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6622 [tests-only][full-ci]Add tests for checking response of REPORT request in project spaces
  tests/acceptance/features/apiContract/spacesReport.feature
Labels: QA:team

#6627 [full-ci][tests-only] Check id file owner in response
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review

#6639 [tests-only][full-ci] Back port PR's related to antivirus service api tests
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#6597 [full-ci][tests-only] Implement validation code while request for user app role id in `Then` step
  tests/acceptance/features/bootstrap/SettingsContext.php
Labels: QA:team

#6633 [tests-only][full-ci] Test for mail notification to group members if a space is shared
  tests/acceptance/features/apiNotification/emailNotification.feature
Labels: QA:team

#6638 [tests-only] [full-ci] added different roles for sharee
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
Labels: QA:team

#6635 [tests-only] [full-ci] added different roles for sharee
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
Labels: QA:team

#6647 [docs-only] Fix webdav envvar description
  services/webdav/pkg/config/config.go
Labels: Topic:Documentation

#6644 [tests-only] [full-ci] Test for mail notification to group members if a space is shared
  tests/acceptance/features/apiNotification/emailNotification.feature
Labels: QA:team

#6643 [tests-only] [full-ci] check response for download file as user
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6553 [tests-only][full-ci] implement DRY principle
  tests/acceptance/features/bootstrap/ArchiverContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#6650 [tests-only][full-ci] Backport implementing code refactoring
  tests/acceptance/features/bootstrap/ArchiverContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#6641 [tests-only][full-ci]Add api test for search file through tag
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6608 [tests-only] [full-ci] Refactoring unshare step definition code
  tests/TestHelpers/SharingHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#6655 [tests-only][full-ci] added test for mail notification in diffrent languages when shared to group
  tests/acceptance/features/apiNotification/emailNotification.feature
Labels: QA:team

#6653 [tests-only] [full-ci] Added API test to search shared files by sharee using tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6680 [tests-only] [full-ci] Do not register space context for reva
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#6682 [docs-only] Update userlog README.md
  services/userlog/README.md
Labels: Topic:Documentation
