Repository owncloud/ocis, pull requests merged in 2023-10, with the labels that each got.

#7347 [tests-only] removing the setresponse in given/when/then step in ocs and webdavlocking context
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#7334 [tests-only] Run tests with default propfind depth infinity config
  .drone.star
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#7318 [tests-only]Added test for the `move` with file-id in `web-dav-url`
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7395 [tests-only] Added tests with depth:infinity enabled
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiDepthInfinity/propfind.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#7396 [tests-only] Remove AppConfigurationContext file
  tests/acceptance/config/behat-core.yml
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#7402 [tests-only][full-ci]Backport move byfileid
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7368 [tests-only] removing the setresponse in given/when/then step in webdavproperties context
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiWebdavProperties1/createFileFolder.feature
  tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#7415 [tests-only] [full-ci] backport refactor set response in given/when/then step in webdavproperties context
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiWebdavProperties1/createFileFolder.feature
  tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#7425 [tests-only] Fix share creation methods
  tests/TestHelpers/HttpRequestHelper.php
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#7398 [tests-only][full-ci]add test for copy with fileID
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#7421 [tests-only][full-ci]add test for move with fileID in project space
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7327 [tests-only][full-ci] refactor profind response
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavOperations/search.feature
Labels: QA:team

#7442 [tests-only][full-ci] Backport add test for copy with fileID (#7398)
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#7407 [tests-only] Removed unused steps from AuthContext
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/coreApiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavSpecialURLs.feature
Labels: QA:team

#7451 [tests-only] Removed unused steps from AuthContext
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/coreApiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavSpecialURLs.feature
Labels: QA:team

#7450 [tests-only][full-ci] Backport refactor profind response (#7327)
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavOperations/search.feature
Labels: QA:team

#7443 [tests-only][full-ci] Backport add test for move with fileID in project space (#7421)
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#7457 [tests-only] Fix API test steps
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/coreApiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/coreApiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/coreApiAuthOcs/ocsPUTAuth.feature
Labels: QA:team

#7372 [tests-only] [full-ci] refactored feature file related to GraphAPI steps
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#7234 [tests-only][full-ci] added test for previewing shared resource using spaces dav version
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
Labels: QA:team

#7447 [tests-only] [full-ci] removing the setresponse in given/then step in spacestus context
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
Labels: QA:team

#7472 [tests-only][full-ci] Forwardport added test coverage for previewing shared resources using spaces dav path
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
Labels: QA:team

#7475 [tests-only] Fix API test steps (#7457)
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/coreApiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/coreApiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/coreApiAuthOcs/ocsPUTAuth.feature
Labels: QA:team

#7371 [tests-only] Log requests and responses for the failing tests
  .drone.star
  tests/TestHelpers/HttpLogger.php
  tests/TestHelpers/HttpRequestHelper.php
  tests/acceptance/.gitignore
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#7482 [docs-only] Update README.md of the settings service
  services/settings/README.md
Labels: Topic:Documentation

#7485 [docs-only] Update frontend service README.md
  services/frontend/README.md
Labels: Topic:Documentation

#7480 [tests-only][full-ci] Backport refactoring webdav context removing setresponse() in given/then step
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
Labels: QA:team

#7439 [tests-only] [full-ci] removing the setresponse in given/then step in publicwebdav context
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
Labels: QA:team

#7492 [tests-only] [full-ci] backport refactor publicwebdav context removing setresponse in given/then steps
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
Labels: QA:team

#7493 [tests-only] Add query params to the API calls log
  tests/TestHelpers/HttpLogger.php
Labels: QA:team

#7474 [tests-only] [full-ci] refactored feature file related to GraphAPI steps
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#7494 [tests-only] Log requests and responses for the failing tests
  .drone.star
  tests/TestHelpers/HttpLogger.php
  tests/TestHelpers/HttpRequestHelper.php
  tests/acceptance/.gitignore
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#7360 [tests-only][full-ci] refactoring user addition to group to graphapi
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: QA:team

#7496 [tests-only] [full-ci] removing the setresponse in given/then step in spaces context
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6648 Removed outdated docker-compose example and added link to examples
  docs/services/app-registry/apps.md
Labels: Status:Needs-Review

#7409 feature(thumbnails): add the ability to define custom image processors
  changelog/unreleased/thumbnail-processors.md
  protogen/gen/ocis/services/thumbnails/v0/thumbnails.pb.go
  protogen/proto/ocis/services/thumbnails/v0/thumbnails.proto
  services/thumbnails/README.md
  services/thumbnails/pkg/service/grpc/v0/service.go
  services/thumbnails/pkg/thumbnail/encoding.go
  services/thumbnails/pkg/thumbnail/generator.go
  services/thumbnails/pkg/thumbnail/processor.go
  services/thumbnails/pkg/thumbnail/processor_test.go
  services/thumbnails/pkg/thumbnail/storage/filesystem.go
  services/thumbnails/pkg/thumbnail/storage/filesystem_test.go
  services/thumbnails/pkg/thumbnail/storage/inmemory.go
  services/thumbnails/pkg/thumbnail/storage/inmemory_test.go
  services/thumbnails/pkg/thumbnail/storage/storage.go
  services/thumbnails/pkg/thumbnail/thumbnail.go
  services/thumbnails/pkg/thumbnail/thumbnail_test.go
  services/webdav/pkg/dav/requests/thumbnail.go
  services/webdav/pkg/service/v0/service.go
Labels: Category:Enhancement

#7506 [tests-only] [full-ci] backport refactor spaces context remove setting response in given/then steps
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7521 [tests-only] Retry space listing if required space is not found
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7495 [tests-only][full-ci]add test for copy file between project and personal space
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#7536 [docs-only] Use semicolon instead of comma separating envvars
  services/frontend/pkg/config/config.go
  services/notifications/pkg/config/config.go
Labels: Topic:Documentation

#7530 [tests-only][full-ci]Adds test for getting share jail space information of the user when user has pending share
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7542 [full-ci] run linter and unit test from top-level
  .drone.star
  Makefile
  sonar-project.properties
Labels: QA:team

#7549 [ci][full-ci] use drone http proxy where go-image is used
  .drone.star
Labels: QA:team

#7550 [tests-only][full-ci] Backport copy file between personal and project space with file
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#7544 [tests-only][full-ci] added test for previewing shared resource inside project space
  tests/TestHelpers/SharingHelper.php
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7588 [tests-only][full-ci] backport added test for previewing shared resource inside project space
  tests/TestHelpers/SharingHelper.php
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7591 [tests-only] skip sharing tests in reva
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SettingsContext.php
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/coreApiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/coreApiWebdavLocks2/independentLocksShareToShares.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties1/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/coreApiWebdavProperties1/getQuota.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
Labels: QA:team

#7593 [tests-only][full-ci] add tests for copy file within shares using file-id
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7605 [tests-only][full-ci] Backport add tests for copy file within shares using file-id
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#7020 [tests-only][full-ci] refactoring the user delete code from ocs to graphapi
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
Labels: QA:team

#7545 [tests-only] [full-ci] backporting the PR related to user addition to group to graphapi
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: QA:team

#7399 [tests-only][full-ci] removing the `setResponse()` in given/then step in GraphContext
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#7631 [tests-only] skip search by last month test
  tests/acceptance/features/apiSearch/dateSearch.feature
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
Labels: QA:team
