Repository owncloud/ocis, pull requests merged in 2023-12, with the labels that each got.

#7649 Add example config for 3rd party WebDAV client Cyberduck (and Mountain Duck)
  deployments/examples/ocis_keycloak/config/keycloak/clients/cyberduck.json
Labels: Status:Needs-Review

#7828 [tests-only][full-ci] tests: add api tests for deleting public link password
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
Labels: QA:team

#7853 [docs-only] Adding thumbnail query parameters to thumbnail README.md
  services/thumbnails/README.md
Labels: Status:Needs-Review

#7857 [tests-only] adding skip on reva tag (#7856)
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#7861 feature: add beta drive listing endpoints to the graph api
  go.mod
  go.sum
  services/graph/pkg/errorcode/errorcode.go
  services/graph/pkg/service/v0/drives.go
  services/graph/pkg/service/v0/graph.go
  services/graph/pkg/service/v0/graph_test.go
  services/graph/pkg/service/v0/service.go
  services/graph/pkg/unifiedrole/unifiedrole.go
  services/graph/pkg/unifiedrole/unifiedrole_test.go
  vendor/github.com/owncloud/libre-graph-api-go/README.md
  vendor/github.com/owncloud/libre-graph-api-go/api_drives_get_drives.go
  vendor/github.com/owncloud/libre-graph-api-go/api_me_drives.go
  vendor/github.com/owncloud/libre-graph-api-go/model_unified_role_permission.go
  vendor/modules.txt
Labels: Status:In-Progress

#7894 [tests-only][full-ci]tests: add tests for update public link to delete password (permission `0`)
  tests/TestHelpers/SharingHelper.php
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
Labels: QA:team

#7896 [tests-only][ci] separate k6 tests pipeline
  .drone.star
Labels: QA:team

#7875 [tests-only][full-ci] tests: update tests related to deletion of public link password to use ocsv2 as well
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
Labels: QA:team

#7910 [docs-only] Adding Ubernauten Deployment Howto
  docs/ocis/deployment/ubernauten.md
  docs/ocis/deployment/ubernauten_media/001-OCIS-in-50-seconds-2023-10-17.mkv
  docs/ocis/deployment/ubernauten_media/login.png
Labels: Topic:Documentation

#7903 [tests-only] remove unnecessary checks
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#7889 [tests-only][full-ci] removing the setResponse() and $this->response in given/then step in Sharing file
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#7929 [DOCS-ONLY] certificates and updates with supervisorctl
  docs/ocis/deployment/ubernauten.md
Labels: Topic:Documentation

#7943 [docu-only] Added Supervisord URL, removed deprecated $THUMBNAIL advice
  docs/ocis/deployment/ubernauten.md
Labels: Topic:Documentation

#7922 [tests-only][full-ci] Revert wrapper cleanup #7903
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#7966 [docs-only] TUS - incorporate feedback from #7882
  docs/apis/http/tus_upload.md
Labels: Status:Needs-Review

#7829 [tests-only][full-ci] Added API tests to check file versions of shared file from project space by a sharee
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
Labels: QA:team

#7965 [docs-only] Fix inconsistency in unauthenticated WebFinger example response
  services/webfinger/README.md
Labels: Status:Needs-Review

#7974 [tests-only][full-ci] wait for ocis server with timeout (5 mins timeout)
  .drone.star
Labels: QA:team

#7969 [tests-only][full-ci] Added API tests to check file versions of a file inside a shared space
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
Labels: QA:team

#7955 [tests-only]tests: skip tests in reva
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
Labels: QA:team

#7981 [tests-only][full-ci] wait for ocis server with timeout (5 mins timeout)
  .drone.star
Labels: QA:team

#7980 [tests-only][full-ci] Added API tests to check file versions of a file in a project space
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
Labels: QA:team

#7997 [full-ci][tests-only] Close channel after log scanner has completed
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#7991 [docs-only] Set special internal extended envvars to not-show state
  docs/helpers/README.md
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#7864 [tests-only][full-CI] Remove OCS endpoint for group creation
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#7984 [full-ci] [tests-only] Added test for sending share invitation to user with role
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8024 [docs-only] fix envvar where a semicolon was a remnant
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#8031 [docs-only] Fixes the extended-envvars.yaml because of changes in MICRO_REGISTRY
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#8032 [docs-only] Fixing the description text of MICRO_REGISTRY
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#7982 [tests-only][full-ci]Added tests for creating link for a resource
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/createLink.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8009 [full-ci] [tests-only] Added test for sending share invitation to group with role
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8036 [tests-only][full-ci]Added tests for the expirydate with displaName for share link
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/createLink.feature
Labels: QA:team

#8043 [tests-only][full-ci][backport] Remove OCS endpoint for group creation
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#8040 [tests-only][full-ci]Added tests for create link share without password
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/createLink.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8046 [full-ci] [tests-only] Added test for sending share invitation to user with permissions
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8047 [full-ci] [tests-only] Added test for sending share invitation to group with permissions
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8078 [full-ci] [tests-only] Backport PR 8046, 8047
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8082 [tests-only][ci] Run k6 tests only for master branch
  .drone.star
Labels: QA:team
