Repository owncloud/ocis, pull requests merged in 2023-02, with the labels that each got.

#5424 [test-only][full-ci] ApiTest. creating a shared resource with an expiration date
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiContract/spacesReport.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/search.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/TagContext.php
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/coreApiSharePublicLink3/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShareOc10Issue37653.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
Labels: Status:Needs-Review

#5485 [full-ci] [tests-only] Remove core bug demonstration scenarios
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedMultipleWaysIssue39347.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareOc10Issue37605.feature
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLinkOc10Issue37683.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShareOc10Issue37653.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDateOc10Issue37013.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFoldersOc10Issue23151.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestoreOc10Issue35974.feature
  tests/acceptance/features/coreApiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/coreApiWebdavLocks/exclusiveLocksOc10Issue34358.feature
  tests/acceptance/features/coreApiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/coreApiWebdavLocks/requestsWithTokenOc10Issue34338.feature
  tests/acceptance/features/coreApiWebdavLocks/requestsWithTokenOc10Issue34360.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockOc10Issue34302.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunkingOc10Issue36645.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToExcludedDirectoryUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToExcludedDirectoryUsingOldChunkingOc10Issue36645.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileUsingOldChunkingOc10Issue36115.feature
Labels: QA:team

#5489 [full-ci] [tests-only] Removed core bug demonstration scenarios
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedMultipleWaysIssue39347.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareOc10Issue37605.feature
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLinkOc10Issue37683.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShareOc10Issue37653.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDateOc10Issue37013.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFoldersOc10Issue23151.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestoreOc10Issue35974.feature
  tests/acceptance/features/coreApiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/coreApiWebdavLocks/exclusiveLocksOc10Issue34358.feature
  tests/acceptance/features/coreApiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/coreApiWebdavLocks/requestsWithTokenOc10Issue34338.feature
  tests/acceptance/features/coreApiWebdavLocks/requestsWithTokenOc10Issue34360.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockOc10Issue34302.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunkingOc10Issue36645.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToExcludedDirectoryUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToExcludedDirectoryUsingOldChunkingOc10Issue36645.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileUsingOldChunkingOc10Issue36115.feature
Labels: QA:team

#5462 [test-only]ApiTest. tests for spaceManagement
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review

#5479 [tests-only][full-ci] Test scenarios for relative quota amount of personal space
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5518 [docs-only] Replace the legacy Extensions with Services
  docs/_index.md
  docs/ocis/_index.md
  docs/ocis/deployment/basic-remote-setup.md
  docs/ocis/deployment/monitoring-tracing.md
  docs/ocis/getting-started/_index.md
  docs/services/port-ranges.md
  docs/services/settings/_index.md
  docs/services/settings/bundles.md
  docs/services/settings/glossary.md
Labels: Topic:Documentation

#5524 [tests-only][full-ci] Forward-port of relative quota amount of personal space tests
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5508 [tests-only][full-ci]Forward-port Refactor share permission related scenario
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToRoot.feature
  tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
  tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesOldDav.feature
Labels: QA:team

#5526 [full-ci] [tests-only] Remove dav tech preview step
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
Labels: QA:team

#5530 [tests-only][full-ci]Forward port remove DAV tech preview steps
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
Labels: QA:team

#5540 [docs-only] Improve the description of the OCIS_ADMIN_USER_ID envvar
  ocis-pkg/config/config.go
  ocis-pkg/shared/shared_types.go
  services/idm/pkg/config/config.go
  services/settings/pkg/config/config.go
Labels: Topic:Documentation

#5537 [full-ci][tests-only]Add api test to delete the expiration date from a share subitem of space
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
Labels: QA:team

#5545 [tests-only][full-ci]fix flaky test apiSpacesShares/shareSpaces.feature:42
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5444 [docs-only]Update testing docs
  docs/ocis/development/testing.md
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/acceptance.yml
  tests/acceptance/docker/src/ocis-base.yml
  tests/acceptance/docker/src/run-tests.sh
Labels: QA:team

#5529 [test-only] Api test. get applications list.
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/getApplications.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: Status:Needs-Review

#5502 [tests-only][full-ci]Refactor share permission related scenario in coreApiSharePublicLink3
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiSharePublicLink3/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature
Labels: QA:team

#5373 minimal webfinger
  docs/services/webfinger/_index.md
  docs/services/wellknown/_index.md
  ocis-pkg/config/config.go
  ocis-pkg/config/defaultconfig.go
  ocis-pkg/middleware/oidc.go
  ocis-pkg/middleware/options.go
  ocis/pkg/command/webfinger.go
  ocis/pkg/runtime/service/service.go
  services/proxy/pkg/config/defaults/defaultconfig.go
  services/webfinger/.dockerignore
  services/webfinger/Makefile
  services/webfinger/README.md
  services/webfinger/TODO.md
  services/webfinger/cmd/webfinger/main.go
  services/webfinger/pkg/command/health.go
  services/webfinger/pkg/command/root.go
  services/webfinger/pkg/command/server.go
  services/webfinger/pkg/command/version.go
  services/webfinger/pkg/config/config.go
  services/webfinger/pkg/config/debug.go
  services/webfinger/pkg/config/defaults/defaultconfig.go
  services/webfinger/pkg/config/http.go
  services/webfinger/pkg/config/log.go
  services/webfinger/pkg/config/parser/parse.go
  services/webfinger/pkg/config/service.go
  services/webfinger/pkg/config/tracing.go
  services/webfinger/pkg/logging/logging.go
  services/webfinger/pkg/metrics/metrics.go
  services/webfinger/pkg/metrics/options.go
  services/webfinger/pkg/relations/openid_discovery.go
  services/webfinger/pkg/relations/openid_discovery_test.go
  services/webfinger/pkg/relations/owncloud_instance.go
  services/webfinger/pkg/relations/owncloud_instance_test.go
  services/webfinger/pkg/server/debug/option.go
  services/webfinger/pkg/server/debug/server.go
  services/webfinger/pkg/server/http/option.go
  services/webfinger/pkg/server/http/server.go
  services/webfinger/pkg/service/v0/errors.go
  services/webfinger/pkg/service/v0/instrument.go
  services/webfinger/pkg/service/v0/logging.go
  services/webfinger/pkg/service/v0/option.go
  services/webfinger/pkg/service/v0/service.go
  services/webfinger/pkg/service/v0/tracing.go
  services/webfinger/pkg/tracing/tracing.go
  services/webfinger/pkg/webfinger/webfinger.go
  services/webfinger/reflex.conf
Labels: Category:Enhancement

#5494 [full-ci][tests-only]Refactor share permission in coreApiSharePublicLinkShare
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#5490 [full-ci][tests-only]Forward-port refactor share permission in coreApiSharePublicLinkShare
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#5561 [tests-only][full-ci]Forward-port refactor share permission related scenario
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiSharePublicLink3/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature
Labels: QA:team

#5562 [test-only][full-ci] ApiTest. share space with expiration date
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/deleteSpaces.feature
  tests/acceptance/features/apiSpaces/download.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review

#5588 graph: Add accountEnabled flag to ldap backend.
  services/graph/pkg/config/config.go
  services/graph/pkg/config/defaults/defaultconfig.go
  services/graph/pkg/identity/ldap.go
  services/graph/pkg/identity/ldap_education_class_test.go
  services/graph/pkg/identity/ldap_education_school_test.go
  services/graph/pkg/identity/ldap_group_test.go
  services/graph/pkg/identity/ldap_test.go
Labels: Status:Needs-Review

#5520 [full-ci] [tests-only] Remove scenarios tagged skiponocis
  .drone.star
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareWhenExcludedFromSharing.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiTranslation/translation.feature
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsExactSizing.feature
  tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#5598 [tests-only] allow plain acceptance test output
  tests/acceptance/lint-expected-failures.sh
  tests/acceptance/run.sh
Labels: QA:team

#5611 [full-ci] [tests-only] Remove scenarios tagged skiponocis master
  .drone.star
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareWhenExcludedFromSharing.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiTranslation/translation.feature
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsExactSizing.feature
  tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#5619 [docs-only] improve eventhistory service readme
  services/eventhistory/README.md
Labels: Topic:Documentation

#5605 [full-ci][tests-only]Api tests for updating the expiration date of a space
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5606 [tests-only][full-ci]Api tests for deleting the expiration date of a space
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5615 [docs-only] Add a basic storage-users readme only containing cli commands
  services/storage-users/README.md
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#5624 [tests-only] Fix command format in tests/acceptance/run.sh
  tests/acceptance/run.sh
Labels: QA:team

#5626 [tests-only] Fix command format in tests/acceptance/run.sh
  tests/acceptance/run.sh
Labels: QA:team

#5631 [full-ci] [tests-only] Remove occ related steps from occ context
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiSpacesShares/checksum.feature
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareToShares.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/coreApiWebdavLocks2/independentLocksShareToShares.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties1/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
  tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
Labels: QA:team

#5634 [docs-only] Update quota related texts and descriptions
  services/frontend/pkg/config/config.go
  services/proxy/README.md
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#5635 [full-ci] [tests-only] Remove occ related steps from occ context master
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiSpacesShares/checksum.feature
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareToShares.feature
  tests/acceptance/features/coreApiSharePublicLink3/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShareOc10Issue37653.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/coreApiWebdavLocks2/independentLocksShareToShares.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties1/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
  tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
Labels: QA:team

#5632 [full-ci] [tests-only] Remove invokecommand related steps from occ context
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
Labels: QA:team

#5640 [full-ci] [tests-only] Remove invokecommand related steps from occ context master
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
Labels: QA:team

#5579 [tests-only][full-ci]Add api tests to assign role using graph api
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/assignRole.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/RoleAssignmentContext.php
Labels: QA:team

#5658 Forward port `getallgroupmemberswithallmembers` to master
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5621 [tests-only][full-ci] Json drill for `coreApiCapabilities` Suite using library
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
  vendor-bin/behat/composer.json
Labels: QA:team

#5633 [full-ci] [tests-only] Remove systemconfigkey related steps from occ context
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/coreApiSharees/sharees.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolderToExcludedDirectory.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFileToBlacklistedName.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFileToExcludedDirectory.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavUpload1/uploadFileToBlacklistedName.feature
  tests/acceptance/features/coreApiWebdavUpload1/uploadFileToExcludedDirectory.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToExcludedDirectoryUsingOldChunking.feature
Labels: QA:team

#5543 [tests-only] Cache go/bin as a long term cache
  .drone.star
  Makefile
  tests/config/drone/check_go_bin_cache.sh
Labels: QA:team

#5670 fix: make ldap example use share for certs
  deployments/examples/ocis_ldap/config/ldap/docker-entrypoint-override.sh
  deployments/examples/ocis_ldap/docker-compose.yml
Labels: Status:Needs-Review

#5652 Benchmark cli
  docs/clients/rclone/webdav-sync-oidc.md
  ocis/pkg/command/benchmark.go
Labels: Category:Enhancement

#5643 [full-ci] [tests-only] Remove systemconfigkey related steps from occ context master
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/coreApiSharees/sharees.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolderToExcludedDirectory.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFileToBlacklistedName.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFileToExcludedDirectory.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavUpload1/uploadFileToBlacklistedName.feature
  tests/acceptance/features/coreApiWebdavUpload1/uploadFileToExcludedDirectory.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileToExcludedDirectoryUsingOldChunking.feature
Labels: QA:team

#5672 [tests-only][full-ci] Json drill for coreApiCapabilities Suite (port #5621)
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
  vendor-bin/behat/composer.json
Labels: QA:team

#5680 Add a global variable for the metadata backend
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
Labels: Category:Enhancement
