Repository owncloud/ocis, pull requests merged in 2023-01, with the labels that each got.

#5311 [tests-only][full-ci]Added test for getting user information by admin or normal user using Graph API (stable-2.0)
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5314 Update makefile
  Makefile
Labels: Topic:Documentation

#5316 [tests-only][full-ci] Bump core commitid (stable)
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5320 [tests-only][full-ci]Adds tests for sending PATCH request to other user's space
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5321 [tests-only][full-ci] Forward port send invalid UUID master
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5322 [tests-only][full-ci] Bump core commitid (master)
  .drone.env
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#5325 [tests-only][full-ci]Adds tests for sending PATCH request to other user's space - porting from stable to master
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5333 [tests-only] [full-ci] Apitest. check Copy response headers test
  tests/acceptance/features/apiContract/copy.feature
Labels: QA:team

#5332 [tests-only] [full-ci] Add api tests public link folder download master
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5334 [tests-only] [full-ci] Remove accidental HEAD line from expected-failures
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
Labels: QA:team

#5335 [tests-only] [full-ci] Extended public link tests to have more checks
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
Labels: QA:team

#5328 [tests-only][full-ci] Add tests with explicit delay post-processing enabled
  .drone.star
  tests/TestHelpers/HttpRequestHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiAsyncUpload/delayPostprocessing.feature
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#5338 [tests-only][full-ci] Add PROPFIND tests for public link endpoint
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#5345 Complete description of STORAGE_USERS_DRIVER
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#5352 Backport of STORAGE_USERS_DRIVER description changes to docs-stable-2.0
  services/_includes/adoc/storage-users_configvars.adoc
Labels: Topic:Documentation

#5350 [tests-only][full-ci] Port async upload php codes
  tests/TestHelpers/HttpRequestHelper.php
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#5343 Disassociate users from schools on school delete.
  changelog/unreleased/bugfix-disassociate-users-from-deleted-school.md
  services/graph/pkg/service/v0/educationschools.go
  services/graph/pkg/service/v0/educationschools_test.go
Labels: Status:Needs-Review

#5379 [tests-only][full-ci] Added tests for checking version of file uploaded with same mtime twice
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#5383 [tests-only][full-ci] Added tests for checking version of file uploaded with same mtime twice
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#5393 [docs-only] Properly describe docs/helpers and processes
  docs/helpers/README.md
Labels: Topic:Documentation

#5396 drop superflous /me in test urls
  services/graph/pkg/service/v0/graph_test.go
  services/graph/pkg/service/v0/groups_test.go
  services/graph/pkg/service/v0/users_test.go
Labels: Type:Technical-Debt

#5394 Remove Staticcheck warnings
  docs/helpers/extendedEnv.go
  ocis-pkg/config/envdecode/envdecode_test.go
  ocis-pkg/log/stream.go
  ocis-pkg/store/store.go
  services/graph/pkg/identity/ldap_education_school_test.go
  services/graph/pkg/identity/ldap_education_user_test.go
  services/graph/pkg/identity/ldap_test.go
  services/graph/pkg/service/v0/educationclasses_test.go
  services/graph/pkg/service/v0/graph_test.go
  services/graph/pkg/service/v0/groups_test.go
  services/graph/pkg/service/v0/password_test.go
  services/ocs/pkg/middleware/requireselforadmin.go
  services/proxy/pkg/command/server.go
  services/proxy/pkg/middleware/accesslog.go
  services/proxy/pkg/server/http/server.go
  services/proxy/pkg/user/backend/cs3.go
  services/search/pkg/service/grpc/v0/service.go
Labels: Type:Technical-Debt

#5401 [tests-only][full-ci] Adds tests for checking href of the public link share
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#5409 [tests-only][full-ci] Adds tests for checking href of the public link share - master
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#5403 graph: Allow provisioning users with legacy names (#5255)
  services/graph/pkg/config/config.go
  services/graph/pkg/config/defaults/defaultconfig.go
  services/graph/pkg/config/parser/parse.go
  services/graph/pkg/service/v0/educationuser.go
  services/graph/pkg/service/v0/users.go
  services/graph/pkg/service/v0/users_test.go
Labels: Status:Needs-Review

#5425 [tests-only][full-ci] Added version author tests
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiVersions/fileVersionsSharingToShares.feature
Labels: QA:team

#5415 [tests-only][full-ci] Add tests scenarios for updating role of public link to internal
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
Labels: QA:team

#5430 [docs-only] Change Testing section in the doc
  .drone.star
  Makefile
  docs/ocis/development/testing.md
Labels: QA:team

#5438 [tests-only][full-ci] Added version author tests (port #5425)
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiVersions/fileVersionsSharingToShares.feature
Labels: QA:team

#5440 [tests-only][full-ci] Backport test scenarios for changing role of public link to internal to stable-2.0
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
Labels: QA:team

#5417 [test-only] ApiTest. deleteTag test. increase coverage
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/bootstrap/TagContext.php
Labels: Status:Needs-Review

#5448 [docs-only] Fix formatting in the docs related to testing
  docs/ocis/development/testing.md
Labels: QA:team

#5456 [tests-only][full-ci] Test scenarios for search/REPORT response for personal shares
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesReport.feature
Labels: QA:team

#5472 [tests-only][full-ci] Forward-port search/report response test scenarios for personal shares
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesReport.feature
Labels: QA:team

#5459 Add line number and file to log messages when at debug level.
  ocis-pkg/log/log.go
Labels: Status:Needs-Review
