Repository owncloud/ocis, pull requests merged in 2023-04, with the labels that each got.

#5965 [tests-only][full-ci]Forwardport json drill apispacesshares
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5993 graph: Add strict json decoding to return errors when receiving unknown parameters
  services/graph/pkg/service/v0/approleassignments.go
  services/graph/pkg/service/v0/drives.go
  services/graph/pkg/service/v0/educationclasses.go
  services/graph/pkg/service/v0/educationschools.go
  services/graph/pkg/service/v0/educationuser.go
  services/graph/pkg/service/v0/groups.go
  services/graph/pkg/service/v0/password.go
  services/graph/pkg/service/v0/tags.go
  services/graph/pkg/service/v0/users.go
  services/graph/pkg/service/v0/utils.go
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
Labels: Status:Needs-Review

#5979 [tests-only][full-ci] Api test for user trying to set own personal space quota
  services/graph/pkg/service/v0/drives.go
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/setQuota.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
Labels: QA:team

#6002 idp: Change name of environment variable to be more consistent.
  services/idp/pkg/config/config.go
Labels: Status:Needs-Review

#6003 [docs-only] Rename / Deprecate userlog and eventhistory envvars
  services/eventhistory/README.md
  services/eventhistory/pkg/config/config.go
  services/idp/pkg/config/config.go
  services/userlog/README.md
  services/userlog/pkg/config/config.go
Labels: Topic:Documentation

#6005 [docs-only] Fixing the service name in the text used in readme.md
  services/gateway/README.md
  services/graph/README.md
  services/ocs/README.md
Labels: Topic:Documentation

#5989 [tests-only][full-ci]Json assertion apigraph `master` branch
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiGraph/getUserOwnInformation.feature
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#6009 Introduced global OCIS_EVENTS_ENDPOINT and OCIS_EVENTS_CLUSTER #5901
  services/antivirus/pkg/config/config.go
  services/audit/pkg/config/config.go
  services/eventhistory/pkg/config/config.go
  services/graph/pkg/config/config.go
  services/notifications/pkg/config/config.go
  services/policies/pkg/config/config.go
  services/postprocessing/pkg/config/config.go
  services/search/pkg/config/search.go
  services/sharing/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/userlog/pkg/config/config.go
Labels: Status:Needs-Review

#6008 Deprecating and renaming many environment variables
  .drone.star
  ocis-pkg/config/config.go
  ocis-pkg/shared/shared_types.go
  services/auth-basic/pkg/config/config.go
  services/frontend/pkg/config/config.go
  services/gateway/pkg/config/config.go
  services/graph/pkg/config/config.go
  services/groups/pkg/config/config.go
  services/idm/pkg/config/config.go
  services/idp/pkg/config/config.go
  services/notifications/pkg/config/config.go
  services/postprocessing/pkg/config/config.go
  services/search/pkg/config/reva.go
  services/search/pkg/config/search.go
  services/sharing/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/thumbnails/pkg/config/config.go
  services/userlog/pkg/config/config.go
  services/users/pkg/config/config.go
  services/webdav/pkg/config/config.go
Labels: Status:Needs-Review

#6021 [docs-only] Update new-service-checklist.md
  docs/services/new-service-checklist.md
Labels: Topic:Documentation

#6020 [docs-only] Update Graph README.md to properly show the image in owcloud.dev
  services/graph/README.md
Labels: Topic:Documentation

#6013 [tests-only][full-ci]Clean up old JSON assertion step
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6054 [docs-only] Fix typo in audit service readme
  services/audit/README.md
Labels: Topic:Documentation

#6070 [docs-only] Fixing ADOC.tmpl typo
  docs/templates/ADOC.tmpl
Labels: Topic:Documentation

#6043 [tests-only][full-ci]Added test to search when share is no accepted yet
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
Labels: QA:team

#6033 [tests-only] [full-ci] Refactor api endpoint for adding group to group
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#6047 reva/frontend: Add capabilities to indicate attributes that are read-only
  go.mod
  go.sum
  services/frontend/README.md
  services/frontend/pkg/config/config.go
  services/frontend/pkg/revaconfig/config.go
Labels: Status:Needs-Review

#6077 [docs-only] update the deprecation description (removal version rule)
  docs/ocis/development/deprecating-variables.md
Labels: Topic:Documentation

#6086 [docs-only] Improve special envvar description
  ocis-pkg/config/config.go
Labels: Topic:Documentation

#6079 [docs-only] Correct the removal version according semver to 4.0.0
  services/auth-basic/pkg/config/config.go
  services/eventhistory/pkg/config/config.go
  services/frontend/pkg/config/config.go
  services/gateway/pkg/config/config.go
  services/graph/pkg/config/config.go
  services/groups/pkg/config/config.go
  services/idp/pkg/config/config.go
  services/notifications/pkg/config/config.go
  services/postprocessing/pkg/config/config.go
  services/search/pkg/config/reva.go
  services/search/pkg/config/search.go
  services/sharing/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/thumbnails/pkg/config/config.go
  services/userlog/pkg/config/config.go
  services/users/pkg/config/config.go
  services/webdav/pkg/config/config.go
Labels: Topic:Documentation

#6083 [docs-only] Add supported values at FRONTEND_READONLY_USER_ATTRIBUTES envvar
  services/frontend/README.md
  services/frontend/pkg/config/config.go
Labels: Topic:Documentation

#6090 [docs-only] Fix notification readme and translation comments
  services/notifications/README.md
  services/notifications/pkg/email/templates.go
Labels: Topic:Documentation

#6094 [tests-only][full-ci]Add skip on reva instead
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature
Labels: QA:team

#6063 [tests-only][full-ci]Refactor the syntax of the scenarios in local API tests
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiAccountsHashDifficulty/webDavPUTAuthInvalid.feature
  tests/acceptance/features/apiAsyncUpload/delayPostprocessing.feature
  tests/acceptance/features/apiContract/copy.feature
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/changeOwnPassword.feature
  tests/acceptance/features/apiGraph/createGroup.feature
  tests/acceptance/features/apiGraph/createGroupCaseSensitive.feature
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getApplications.feature
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/createSpace.feature
  tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
  tests/acceptance/features/apiSpaces/download.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/notification.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/resharing.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/apiSpaces/search.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
  tests/acceptance/features/apiSpacesShares/checksum.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/etagPropagation.feature
  tests/acceptance/features/apiSpacesShares/favorite.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#6073 Try to fix problems with unescaping values.
  services/graph/pkg/service/v0/graph.go
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
Labels: Status:Needs-Review

#6107 [tests-only] tidy up acceptance tests
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/TestHelpers/SharingHelper.php
  tests/TestHelpers/UploadHelper.php
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/notification.feature
  tests/acceptance/features/apiSpaces/resharing.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/etagPropagation.feature
  tests/acceptance/features/apiSpacesShares/favorite.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/RoleAssignmentContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiWebdavOperations/search.feature
  tests/acceptance/features/coreApiWebdavProperties1/setFileProperties.feature
Labels: QA:team

#6018 [tests-only][full-ci] api test to get personal drive information of other users
  services/graph/pkg/service/v0/users.go
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#6112 [docs-only] Fix texts and typos in README.md files
  docs/helpers/README.md
  docs/services/frontend/_index.md
  services/antivirus/README.md
  services/eventhistory/README.md
  services/frontend/README.md
  services/gateway/README.md
  services/graph/README.md
  services/ocs/README.md
  services/policies/README.md
  services/postprocessing/README.md
  services/proxy/README.md
  services/storage-system/README.md
  services/storage-users/README.md
  services/userlog/README.md
Labels: Topic:Documentation

#6113 [tests-only] Fix invalid acceptance test step
  tests/acceptance/features/apiGraph/getApplications.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: QA:team

#6119 [docs-only] Add caching/storing info to services where missing
  services/eventhistory/README.md
  services/frontend/README.md
  services/gateway/README.md
  services/graph/README.md
  services/ocs/README.md
  services/proxy/README.md
  services/storage-system/README.md
  services/storage-users/README.md
  services/userlog/README.md
Labels: Topic:Documentation

#6135 [tests-only][full-ci]Bump web commit id
  .drone.env
  .drone.star
Labels: QA:team

#6138 [tests-only][full-ci]Refactor feature files to add proper description
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiAuth/webDavAuth.feature
  tests/acceptance/features/coreApiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/coreApiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/coreApiAuthOcs/ocsPOSTAuth.feature
  tests/acceptance/features/coreApiAuthOcs/ocsPUTAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavCOPYAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavDELETEAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavLOCKAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavMKCOLAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavMOVEAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavPOSTAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavPROPFINDAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavPROPPATCHAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavPUTAuth.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavSpecialURLs.feature
Labels: QA:team

#6144 [docs-only] Update envvar-scopes.md (owncloud.dev)
  docs/services/general-info/envvar-scopes.md
Labels: Topic:Documentation

#6106 [tests-only]Added GDPR export. check events when user is created
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6159 [tests-only]Gdpr upload file1
  tests/acceptance/features/apiGraph/userGDPRExport.feature
Labels: QA:team

#6180 [docs-only] Update IDP README.md
  services/idp/README.md
Labels: Topic:Documentation

#6169 [docs-only] Fix that envvars use messagepack instead of ini as supported values.
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#6187 Read quota from opaque
  services/graph/pkg/service/v0/drives.go
Labels: Type:Bug, Topic:Performance
