Repository owncloud/ocis, pull requests merged in 2023-03, with the labels that each got.

#5642 [full-ci] [tests-only] Remove depthinfinity related steps from occ context
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#5679 [full-ci] [tests-only] Remove depthinfinity related steps from occ context master
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#5688 update litmus to maintained container in ci
  .drone.star
Labels: QA:team

#5612 [full-ci] [tests-only] Remove occ related codes
  tests/acceptance/config/behat-core.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/parallelDeployAcceptance/config/behat.yml
Labels: QA:team

#5678 [full-ci][tests-only] Extend tests coverage for adding users in a group with single request
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/createGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5698 [docs-only] Add build-essentials as prerequisite to README.md
  README.md
Labels: Topic:Documentation

#5718 [docs-only] Alingning the graph service readme with content of the admin docs
  services/graph/README.md
  services/graph/images/mermaid-graph.svg
Labels: Topic:Documentation

#5719 [docs-only] Update graph service readme
  services/graph/README.md
Labels: Topic:Documentation

#5584 [tests-only][full-ci]Extend tests related to assign role
  tests/acceptance/features/apiGraph/assignRole.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5703 [ci] Enable Github comment for e2e tracing results on failure
  .drone.star
Labels: QA:team

#5717 [ci][ci] Enable Github comment for e2e tracing results on failure (stable-2)
  .drone.star
Labels: QA:team

#5724 [ci] Cache the go/bin content as a single archive file
  .drone.star
  tests/config/drone/check_go_bin_cache.sh
Labels: QA:team

#5706 [ci] Cache the go/bin content as a single archive file
  .drone.star
  tests/config/drone/check_go_bin_cache.sh
Labels: QA:team

#5671 [tests-only][full-ci] Backport test PRs
  .drone.star
  tests/TestHelpers/GraphHelper.php
  tests/TestHelpers/TagsHelper.php
  tests/acceptance/config/behat-core.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/spacesReport.feature
  tests/acceptance/features/apiGraph/assignRole.feature
  tests/acceptance/features/apiGraph/getApplications.feature
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/deleteSpaces.feature
  tests/acceptance/features/apiSpaces/download.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/apiSpaces/search.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/RoleAssignmentContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/TagContext.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavOperations/search.feature
Labels: QA:team

#5695 graph: Move token middleware and return proper JSON response on error.
  ocis-pkg/service/debug/service.go
  services/graph/pkg/middleware/token.go
  services/graph/pkg/middleware/token_test.go
  services/graph/pkg/server/http/server.go
Labels: Status:Needs-Review

#5625 graph: Allow disabling user by adding to local group
  services/graph/pkg/command/server.go
  services/graph/pkg/config/config.go
  services/graph/pkg/config/defaults/defaultconfig.go
  services/graph/pkg/identity/ldap.go
  services/graph/pkg/identity/ldap_test.go
  services/graph/pkg/service/v0/service.go
Labels: Status:Needs-Review

#5736 [docs-only] Small description text fixes for envvars
  services/graph/pkg/config/config.go
  services/groups/pkg/config/config.go
  services/userlog/pkg/config/config.go
Labels: Topic:Documentation

#5733 [tests-only][full-ci]Seperate test steps for positive and negative cases
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5744 [tests-only][full-ci] Backport extend assign role test coverage
  tests/acceptance/features/apiGraph/assignRole.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5743 [tests-only][full-ci]Forward-port add users to a group at once
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/createGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5641 [tests-only][full-ci] test for getting details of single group
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
Labels: QA:team

#5745 [tests-only][full-ci]Refactor test function for handeling errors
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#5770 [docs-only] Update getting-started.md (for owncloud.dev)
  docs/ocis/development/getting-started.md
Labels: Topic:Documentation

#5766 [docs-only] Fix descriptions of envvars in the frontend service
  services/frontend/pkg/config/config.go
Labels: Topic:Documentation

#5705 [full-ci] [tests-only] Remove `isTestingOnOcisOrReva` method
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/LoggingHelper.php
  tests/TestHelpers/OcisHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#5773 [tests-only][full-ci]Seperate test steps for positive and negative cases
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#5777 [full-ci] [tests-only] Remove `isTestingOnOcisOrReva`
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/LoggingHelper.php
  tests/TestHelpers/OcisHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#5748 [tests-only][full-ci]Test for getting group with utf8 characters in name
  tests/acceptance/features/apiGraph/getGroup.feature
Labels: QA:team

#5775 [full-ci][tests-only]Refactor test for updating the share
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5782 Bump libre-graph-api-go to latest main
  go.mod
  go.sum
Labels: Status:Needs-Review

#5722 [full-ci] [tests-only] Remove `isTestingOnOc10` method
  tests/TestHelpers/OcisHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#5651 [tests-only][full-ci]Json drill suite `apiSpaces`
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/deleteSpaces.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5701 [tests-only][full-ci]Test for getting non existing group
  tests/acceptance/features/apiGraph/getGroup.feature
Labels: QA:team

#5693 [full-ci][tests-only] Extend tests coverage to add users in a group
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5789 [full-ci][tests-only]Refactor test for updating the share
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5788 [full-ci] [tests-only] Removed method isTestingOnOc10, and refactored code
  tests/TestHelpers/OcisHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#5780 [full-ci] [tests-only] Remove `isTestingOnOcis` method
  tests/TestHelpers/OcisHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#5808 [full-ci] [tests-only] Removed method `isTestingOnOcis`, and refactored code
  tests/TestHelpers/OcisHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#5691 [full-ci] [tests-only] Remove `runOcc` method from `SetupHelper`
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#5820 [full-ci] [tests-only] Remove `runOcc` method from `SetupHelper` master
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#5827 [docs-only] Syncing one frontend envvar description from backport
  services/frontend/pkg/config/config.go
Labels: Topic:Documentation

#5819 [tests-only][full-ci] Add tests for checking the end of expiration date
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5818 Forward port json drill `apispaces`
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/deleteSpaces.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
Labels: QA:team

#5760 [tests-only][full-ci]forward-port added test for getting details of a single group
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
Labels: QA:team

#5831 [tests-only][full-ci]Forward-port extend tests scenario to add users to a group at once
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5791 [tests-only][full-ci] Forward-port added test for getting group with UTF-8 characters in name
  tests/acceptance/features/apiGraph/getGroup.feature
Labels: QA:team

#5840 graph: Change so that educationUsers can be created without email.
  services/graph/pkg/service/v0/educationuser.go
  services/graph/pkg/service/v0/educationuser_test.go
Labels: Status:Needs-Review

#5838 [full-ci] [tests-only] Remove `runOcc` method from `FeatureContext`
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature
Labels: QA:team

#5834 [full-ci][tests-only][backport]Add tests to check the end of an expiration date
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5859 [docs-only] Fix edit path for port-ranges.md
  docs/services/port-ranges.md
Labels: Topic:Documentation

#5837 [full-ci] [tests-only] Remove log file related codes
  tests/TestHelpers/LoggingHelper.php
  tests/acceptance/config/behat-core.yml
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileUsingOldChunking.feature
Labels: QA:team

#5860 [full-ci] [tests-only] Remove log file related codes master
  tests/TestHelpers/LoggingHelper.php
  tests/acceptance/config/behat-core.yml
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/coreApiWebdavUpload2/uploadFileUsingOldChunking.feature
Labels: QA:team

#5870 Remove faulty enties in extended_vars.yaml
  helpers/extended_vars.yaml
Labels: Topic:Documentation

#5879 [docs-only] Fix extended_envvars.yaml has wrong referenced lineno in master
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#5880 [docs-only] Update docs/helpers/README.md
  docs/helpers/README.md
Labels: Topic:Documentation

#5856 [full-ci] [tests-only] Remove occ related leftovers
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiAuthWebDav/webDavDELETEAuth.feature
Labels: QA:team

#5725 [full-ci][tests-only]Expand tests coverage related to user with different role
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5884 [full-ci] [tests-only] Remove occ related leftovers `master`
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiAuthWebDav/webDavDELETEAuth.feature
Labels: QA:team

#5886 [docs-only] Update proxy _index.md for owncloud.dev
  docs/services/proxy/_index.md
Labels: Topic:Documentation

#5876 [full-ci] [tests-only] Revert ldap related code removed
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#5836 graph: Fix so that accountEnabled updates work for educationUser.
  services/graph/pkg/identity/ldap.go
  services/graph/pkg/identity/ldap_education_school_test.go
  services/graph/pkg/identity/ldap_education_user.go
  services/graph/pkg/identity/ldap_education_user_test.go
  services/graph/pkg/service/v0/educationuser_test.go
Labels: Status:Needs-Review

#5890 Fixed typo
  services/app-provider/pkg/config/config.go
Labels: Status:Needs-Review

#5891 graph: Hide ldap error on group membership patch.
  services/graph/pkg/identity/ldap_group.go
Labels: Status:Needs-Review

#5900 [docs-only] Update the ownCloud.dev main page
  docs/_index.md
Labels: Topic:Documentation

#5904 [docs-only] Clarify the description of the IDP_TLS envvar
  services/idp/pkg/config/http.go
Labels: Topic:Documentation

#5910 [full-ci][tests-only]Change web branch to master
  .drone.env
  services/web/Makefile
Labels: QA:team

#5898 [tests-only][full-ci] Test for adding users to a group using invalid JSON
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5920 [docs-only] Update new-service-checklist.md
  docs/services/new-service-checklist.md
Labels: Topic:Documentation

#5875 [tests-only][full-ci] Test for adding multiple member to a group using invalid host in host part of user-id
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5931 [tests-only][full-ci] Fordward-port test for adding users to a group using invalid JSON
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5854 [tests-only][full-ci] api test to set quota by users with different roles
  tests/acceptance/features/apiSpaces/setQuota.feature
Labels: QA:team

#5930 [docs-only] Fixed typos
  services/auth-basic/pkg/config/config.go
  services/graph/pkg/config/config.go
  services/groups/pkg/config/config.go
  services/idm/pkg/config/config.go
  services/idp/pkg/config/config.go
  services/idp/pkg/config/http.go
  services/nats/pkg/config/config.go
  services/proxy/pkg/config/http.go
  services/search/pkg/config/engine.go
  services/settings/pkg/config/config.go
  services/sharing/pkg/config/config.go
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/store/pkg/config/config.go
  services/thumbnails/pkg/config/config.go
  services/users/pkg/config/config.go
Labels: Status:Needs-Review

#5932 [tests-only][full-ci] Forwardport test for send wrong host for adding user in group
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5936 [tests-only]Unskip passing tests from CI
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
Labels: QA:team

#5742 [tests-only][full-ci]Extend tests coverage for different role capability for group
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/createGroup.feature
  tests/acceptance/features/apiGraph/deleteGroup.feature
  tests/acceptance/features/apiGraph/editGroup.feature
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5853 [tests-only][full-ci]Extend tests coverage for different role capability for spaces
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/createSpace.feature
  tests/acceptance/features/apiSpaces/deleteSpaces.feature
  tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5933 [tests-only][full-ci] Backport test for set quota for differnt users
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpaces/setQuota.feature
Labels: QA:team

#5861 [tests-only][full-ci] Added schema for key and value pair assertion
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#5957 [docs-only] Update example-realm.json
  services/invitations/md-sources/example-realm.json
Labels: Topic:Documentation

#5864 [tests-only][full-ci]Expand tests coverage for adding multiple members to a group at single request
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5963 [tests-only] [full-ci] Forward port 5864 PR
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#5971 [tests-only][full-ci]Link the correct issue to failing tests
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
Labels: QA:team
