Repository owncloud/ocis, pull requests merged in 2023-05, with the labels that each got.

#6193 [docs-only] Update the PROXY_TLS envvar description
  services/proxy/README.md
  services/proxy/pkg/config/http.go
Labels: Topic:Documentation

#6208 [docs-only] Add a readme descriton to webui option envvars
  services/web/README.md
Labels: Topic:Documentation

#6209 [docs-only] Typo fix in web service README.md
  services/web/README.md
Labels: Topic:Documentation

#6212 [docs-only] Adding a Identity Provider section in owncloud.dev
  docs/ocis/identity-provider/_index.md
  docs/ocis/identity-provider/ldap-active-directory.md
Labels: Topic:Documentation

#6210 [tests-only][full-ci]Bump web commit for the tests
  .drone.env
Labels: QA:team

#6189 cache special drive items until space root changes
  services/graph/pkg/config/defaults/defaultconfig.go
  services/graph/pkg/service/v0/driveitems.go
  services/graph/pkg/service/v0/drives.go
  services/graph/pkg/service/v0/graph.go
  services/graph/pkg/service/v0/graph_test.go
  services/graph/pkg/service/v0/service.go
Labels: Type:Bug, Type:Regression, Topic:Performance

#6216 [full-ci] bump reva to 2118139f5420
  go.mod
  go.sum
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  vendor/github.com/cs3org/reva/v2/internal/grpc/interceptors/auth/scope.go
  vendor/github.com/cs3org/reva/v2/internal/grpc/services/storageprovider/storageprovider.go
  vendor/github.com/cs3org/reva/v2/pkg/publicshare/manager/json/json.go
  vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/decomposedfs.go
  vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/permissions.go
  vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/spaces.go
  vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload.go
  vendor/modules.txt
Labels: Type:Bug

#6162 [tests-only]Refactor feature files to add correct description
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
  tests/acceptance/features/coreApiFavorites/favorites.feature
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiMain/main.feature
  tests/acceptance/features/coreApiMain/status.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiSharees/sharees.feature
Labels: QA:team

#6221 [docs-only] Fix missing _index.md for the frontend service
  docs/services/frontend/_index.md
Labels: Topic:Documentation

#6224 [docs-only] Add readme.md note to not use xattrs anymore
  services/storage-system/README.md
  services/storage-users/README.md
Labels: Topic:Documentation

#6225 [tests-only][full-ci]Remove core tags
  .drone.star
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareToShares.feature
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/restoreVersion.feature
  tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#6034 [tests-only] [full-ci] Refactor scenario related to checking json response
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpaces/setQuota.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6167 [tests-only][full-ci]Refactor feature files to add correct description
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
Labels: QA:team

#6235 [tests-only][full-ci]Add test to propfind the size of a folder
  tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#6236 [tests-only]Unskip the test related to expiration date
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
Labels: QA:team

#6241 [tests-only][full-ci] Remove duplication of steps and scenario name within a feature file
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavProperties2/getFileProperties.feature
  tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
Labels: QA:team

#6243 [docs-only] An envvar in the storage-users service needs separation by semicolon
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#6237 [tests-only][full-ci]Added GDPR export when user is added to a group
  tests/acceptance/features/apiGraph/userGDPRExport.feature
Labels: QA:team

#6244 [docs-only] Add note that uploads could be canceled when setting is too low
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#6207 [full-ci] [tests-only] Removed step and implementation of setting share auto accept
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiSpacesShares/checksum.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareToShares.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiWebdavLocks2/independentLocksShareToShares.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavProperties1/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties1/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
  tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
Labels: QA:team

#6229 [docs-only] Deprecate some web envvars
  services/web/README.md
  services/web/pkg/config/config.go
Labels: Topic:Documentation

#6239 [tests-only][full-ci]Add proper description to a feature file
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/deleteGroup.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareToShares.feature
  tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
Labels: QA:team

#6263 [tests-only] [full-ci] Cleanup code in TestHelpers
  tests/TestHelpers/Asserts/WebDav.php
  tests/TestHelpers/GraphHelper.php
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/OcisHelper.php
  tests/TestHelpers/OcsApiHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/TestHelpers/SharingHelper.php
  tests/TestHelpers/TranslationHelper.php
  tests/TestHelpers/UploadHelper.php
  tests/TestHelpers/UserHelper.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#6096 [tests-only][full-ci] removed steps related to share api occ commands
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/coreApiShareManagementToShares/acceptSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiSharees/sharees.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
Labels: QA:team

#6249 [tests-only][full-ci]Added GDPR export for quota update, export another users GDPR
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#6266 [tests-only] [full-ci] Update vendor-bin dependencies
  tests/acceptance/features/bootstrap/ArchiverContext.php
  tests/parallelDeployAcceptance/features/bootstrap/ParallelContext.php
  vendor-bin/behat/composer.json
  vendor-bin/owncloud-codestyle/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: QA:team

#6145 [tests-only] [full-ci] api test for email notification
  .drone.star
  docs/ocis/development/testing.md
  tests/TestHelpers/EmailHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiEmailNotification/emailNotification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6280 [docs-only] Fix typo in proxy readme yaml example
  services/proxy/README.md
Labels: Topic:Documentation

#6279 [tests-only] [full-ci] Add examples of more username combinations
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/createUser.feature
Labels: QA:team

#6270 [tests-only] [full-ci] Fix expected trashbin href for spaces
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
Labels: QA:team

#6287 [docs-only] Add Tika container link to search for dev purposes
  services/search/README.md
Labels: Topic:Documentation

#6293 [docs-only] Fix missed default metadata backend
  services/storage-users/pkg/config/defaults/defaultconfig.go
Labels: Topic:Documentation

#6030 [full-ci] [tests-only] unassign app role assignment of user
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/unassignRole.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#6306 [full-ci] update reva vendor files
  vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/spaces.go
  vendor/github.com/cs3org/reva/v2/pkg/storage/cache/cache.go
  vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/node.go
  vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node/xattrs.go
  vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/tree/tree.go
  vendor/modules.txt
Labels: QA:team

#6304 [docs-only ]Update search README.md
  services/search/README.md
Labels: Topic:Documentation

#6283 [docs-only] Document running tests using ociswrapper
  docs/ocis/development/testing.md
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/acceptance.yml
  tests/acceptance/docker/src/ocis-base.yml
  tests/acceptance/docker/src/ocis.Dockerfile
  tests/acceptance/docker/src/serve-ocis.sh
  tests/ociswrapper/README.md
Labels: QA:team

#6327 [docs-only] Use correct envvar caching names in service readme's
  services/eventhistory/README.md
  services/frontend/README.md
  services/gateway/README.md
  services/postprocessing/README.md
  services/userlog/README.md
Labels: Topic:Documentation

#6336 [docs-only] Fix settings typos
  services/settings/pkg/store/defaults/defaults.go
Labels: Topic:Documentation

#6346 [docs-only] Update testing docs
  docs/ocis/development/testing.md
Labels: QA:team

#6347 [docs-only] Add email service to the docker-compose setup for tests
  docs/ocis/development/testing.md
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/acceptance.yml
  tests/acceptance/docker/src/email.yml
  tests/acceptance/docker/src/ocis-base.yml
Labels: QA:team

#6364 [docs-only] Add new caching envvar to storage-users service
  services/storage-users/README.md
Labels: Topic:Documentation

#6040 [full-ci] [tests-only] Change user role
  tests/acceptance/features/apiGraph/changeRole.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#6360 [tests-only][full-ci]Added GDPR export for folder creation, sharing a file
  tests/acceptance/features/apiGraph/userGDPRExport.feature
Labels: QA:team

#6324 [full-ci][tests-only]Extend notification api tests
  .drone.star
  docs/ocis/development/testing.md
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#6385 [full-ci] Migrate pnpm-lock file version from 5.4 to 6
  services/idp/pnpm-lock.yaml
Labels: QA:team

#6383 [full-ci] [tests-only] Added GDPR report test for events.SpaceShared
  tests/acceptance/features/apiGraph/userGDPRExport.feature
Labels: QA:team

#6396 [tests-only][full-ci]Refactor feature files to add correct description
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/coreApiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
Labels: QA:team

#6397 [full-ci] [tests-only] Added GDPR report test for events.SpaceCreated
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team
