Repository owncloud/ocis, pull requests merged in 2023-07, with the labels that each got.

#6679 [tests-only] [full-ci] Refactoring unshare step definition code (#6608)
  tests/TestHelpers/SharingHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#6666 [tests-only][full-ci] added test for mail notification in diffrent languages when shared to group
  tests/acceptance/features/apiNotification/emailNotification.feature
Labels: QA:team

#6696 [tests-only][full-ci]Backport full search test
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6708 [tests-only][full-ci] update issue-product tag to ocis issue tag
  tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/restoreVersion.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
Labels: QA:team

#6694 [tests-only][full-ci] refactor scenario example table
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavCOPYAuth.feature
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiSharees/sharees.feature
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavLocks2/independentLocks.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#6711 [tests-only][full-ci] Backport refactor scenario example table
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaceObjects.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/coreApiAuthWebDav/webDavCOPYAuth.feature
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiSharees/sharees.feature
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavLocks2/independentLocks.feature
  tests/acceptance/features/coreApiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#6710 [tests-only] [full-ci] Backport update issue-product tag to ocis issue tag
  tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/restoreVersion.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
Labels: QA:team

#6657 [tests-only][full-ci] added test for mail notification if space admin delete access to space
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6699 [test-only][full-ci]ApiTests. purge trash bin tests
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/trashBin.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review

#6724 [docs-only] Increase readability for tracing values in the description
  services/app-provider/pkg/config/config.go
  services/app-registry/pkg/config/config.go
  services/audit/pkg/config/config.go
  services/auth-basic/pkg/config/config.go
  services/auth-bearer/pkg/config/config.go
  services/auth-machine/pkg/config/config.go
  services/eventhistory/pkg/config/config.go
  services/gateway/pkg/config/config.go
  services/graph/pkg/config/tracing.go
  services/groups/pkg/config/config.go
  services/idm/pkg/config/tracing.go
  services/idp/pkg/config/tracing.go
  services/invitations/pkg/config/tracing.go
  services/nats/pkg/config/config.go
  services/notifications/pkg/config/config.go
  services/ocdav/pkg/config/config.go
  services/ocs/pkg/config/tracing.go
  services/postprocessing/pkg/config/config.go
  services/proxy/pkg/config/tracing.go
  services/search/pkg/config/tracing.go
  services/settings/pkg/config/tracing.go
  services/sharing/pkg/config/config.go
  services/storage-publiclink/pkg/config/config.go
  services/storage-shares/pkg/config/config.go
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/store/pkg/config/tracing.go
  services/thumbnails/pkg/config/tracing.go
  services/userlog/pkg/config/config.go
  services/users/pkg/config/config.go
  services/web/pkg/config/tracing.go
  services/webdav/pkg/config/tracing.go
  services/webfinger/pkg/config/tracing.go
Labels: Topic:Documentation

#6723 [docs-only] Increase readability for log level values in the description
  services/antivirus/pkg/config/config.go
  services/app-provider/pkg/config/config.go
  services/app-registry/pkg/config/config.go
  services/audit/pkg/config/log.go
  services/auth-basic/pkg/config/config.go
  services/auth-bearer/pkg/config/config.go
  services/auth-machine/pkg/config/config.go
  services/eventhistory/pkg/config/log.go
  services/frontend/pkg/config/config.go
  services/gateway/pkg/config/config.go
  services/graph/pkg/config/log.go
  services/groups/pkg/config/config.go
  services/idm/pkg/config/log.go
  services/idp/pkg/config/log.go
  services/invitations/pkg/config/log.go
  services/nats/pkg/config/log.go
  services/notifications/pkg/config/log.go
  services/ocdav/pkg/config/config.go
  services/ocs/pkg/config/log.go
  services/policies/pkg/config/config.go
  services/postprocessing/pkg/config/log.go
  services/proxy/pkg/config/log.go
  services/search/pkg/config/log.go
  services/settings/pkg/config/log.go
  services/sharing/pkg/config/config.go
  services/storage-publiclink/pkg/config/config.go
  services/storage-shares/pkg/config/config.go
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/store/pkg/config/log.go
  services/thumbnails/pkg/config/log.go
  services/userlog/pkg/config/log.go
  services/users/pkg/config/config.go
  services/web/pkg/config/log.go
  services/webdav/pkg/config/log.go
  services/webfinger/pkg/config/log.go
Labels: Topic:Documentation

#6749 [full-ci][tests-only] Backport drone update
  .drone.star
Labels: QA:team

#6719 [tests-only][full-ci] added test for mail notification if space admin delete access to space
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6659 [tests-only][full-ci] Added API test to search shared items using a tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6754 [tests-only][full-ci][ci] Wait for fakeoffice to be ready
  .drone.star
Labels: QA:team

#6725 [tests-only][full-ci]add scenario for search folder tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6693 [tests-only][full-ci]Add test for preview of shared animated GIFs
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
Labels: QA:team

#6766 [full-ci][tests-only] Forward port preview test coverage
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
Labels: QA:team

#6768 [tests-only][full-ci] Retry ocis startup with ociswrapper
  tests/ociswrapper/cmd/cmd.go
  tests/ociswrapper/ocis/config/config.go
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#6660 [tests-only][full-ci]Test api search by deleted tag
  tests/acceptance/features/apiGraph/fullSearch.feature
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#6769 [tests-only][full-ci]Updated expected to failure for closed issue to new issue
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#6776 [tests-only][full-ci](ociswrapper): separate ociswrapper logs from ocis logs
  tests/ociswrapper/log/log.go
  tests/ociswrapper/ocis/ocis.go
  tests/ociswrapper/wrapper/wrapper.go
Labels: QA:team

#6718 [tests-only][full-ci]refactor for Intermittent test failures on coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: QA:team

#6765 [test-only] Api test. Checking X-Request-Id in response header
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiContract/copy.feature
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesReport.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: Status:Needs-Review

#6783 [tests-only]Remove GitHub comment
  .drone.star
Labels: QA:team

#6789 ci: bump hugo v0.115.2
  .bingo/Variables.mk
  .bingo/hugo.mod
  .bingo/hugo.sum
  .bingo/variables.env
Labels: QA:team

#6661 [tests-only][full-ci] Added API test to search for restored resources having tag
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6788 [tests-only][full-ci]Remove GitHub comment from ci stable 3.0
  .drone.star
Labels: QA:team

#6802 [tests-only][full-ci]Updated expected to failure for closed issue to new issue
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
Labels: QA:team

#6761 use correct config struct for jwt token
  services/search/pkg/command/server.go
Labels: Type:Bug

#6809 [tests-only][full-ci]add tag skipOnReva
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
Labels: QA:team

#6817 ci: split e2e test pipeline
  .drone.star
Labels: QA:team

#6823 [docs-only] Fix envvar descriptions in shared_types.go
  ocis-pkg/shared/shared_types.go
Labels: Topic:Documentation

#6822 ci: split e2e test pipeline (#6817)
  .drone.star
Labels: QA:team

#6678 [tests-only][full-ci]Search files by content
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6796 [tests-only][full-ci] refactored the acceptance test code
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6834 [tests-only][full-ci]Backport test api search tag by user
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6735 [tests-only][full-ci]Add tests for deleting notification
  tests/acceptance/features/apiNotification/deleteNotification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6833 [tests-only] [full-ci] retry on 409 - backport 6796 to stable-3.0
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6836 [tests-only][full-ci]Backport delete notification tests coverage
  tests/acceptance/features/apiNotification/deleteNotification.feature
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/apiNotification/spaceNotification.feature
  tests/acceptance/features/apiSpaces/notification.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6841 [tests-only][full-ci] Backport of add scenario for search folder tag
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6835 [tests-only] [full-ci] Retry if 409 is received when uploading in a Given step
  tests/TestHelpers/UploadHelper.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6844 [tests-only] Retry 409 for education 3.1
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/UploadHelper.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6843 [tests-only] Retry if 409 is received when uploading in a Given step
  tests/TestHelpers/UploadHelper.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#6845 [tests-only][full-ci]Backport of test for search by deleted tag
  tests/acceptance/features/apiGraph/fullSearch.feature
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#6698 [tests-only][full-ci]Search files through content by sharee
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6707 [tests-only][full-ci]Add test for search deleted files using content
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6790 [tests-only][full-ci] make user enable disable feature use graphapi
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
Labels: QA:team

#6683 [tests-only] [full-ci] add test for downloading space
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpaces/spaceDownload.feature
  tests/acceptance/features/bootstrap/ArchiverContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6857 [tests-only][full-ci]Backport test api search restore resource having tag
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiGraph/fullSearch.feature
Labels: QA:team

#6839 [tests-only][full-ci]Retry listing notifications
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6871 [tests-only][full-ci] Fix the syntax of the test step
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
Labels: QA:team

#6872 [tests-only][full-ci]Retry listing notifications (#6839)
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6854 [tests-only][full-ci] Extend space download tests coverage
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/apiDownloads/spaceDownload.feature
  tests/acceptance/features/apiSpaces/spaceDownload.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6873 [full-ci][tests-only][backport] Check id file owner in response
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6868 [tests-only][full-ci]Backport-search files using content
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6880 [full-ci][tests-only]Forward port download space
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/apiDownloads/spaceDownload.feature
  tests/acceptance/features/bootstrap/ArchiverContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#6709 [tests-only][full-ci]Add test for search restored files using content
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6882 [tests-only][full-ci]Backport search files through content by sharee
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6885 [docs-only] Replace double quotes with single quotes in envvar descriptions
  services/antivirus/pkg/config/config.go
  services/app-provider/pkg/config/config.go
  services/auth-basic/pkg/config/tracing.go
  services/idm/pkg/config/config.go
  services/idp/pkg/config/config.go
Labels: Topic:Documentation

#6675 [tests-only][full-ci] refactor check notification and delete it
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6889 [tests-only][full-ci]Backport search deleted using context
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6892 [tests-only][full-ci]Backport of search restored files using context
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiFullTextSearch/search.feature
Labels: QA:team

#6775 [tests-only][full-ci] refactored acceptance code to store the response data related to user or group shares on single store
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#6848 [tests-only][full-ci] refactored the test so that it logs the response every time it fails
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#6895 [tests-only][full-ci] Backport refactoring acceptance code to store response data of user or group shares on single store
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#6898 [tests-only][full-ci] Backport refactor check notification and delete it
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#6883 Separate out grpc client to package local for notifications service.
  services/notifications/pkg/command/server.go
Labels: Status:Needs-Review

#6903 [tests-only][full-ci] refactored the test so that it logs the response every time it fails
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#6905 Separate out grpc client to package local for userlog service.
  services/userlog/pkg/command/server.go
Labels: Status:Needs-Review

#6906 Separate out grpc client to package local for webdav service.
  services/webdav/pkg/command/server.go
  services/webdav/pkg/config/config.go
  services/webdav/pkg/service/v0/service.go
Labels: Status:Needs-Review

#6907 Separate out grpc client to package local for thumbnails service.
  ocis-pkg/service/grpc/service.go
  services/thumbnails/pkg/command/server.go
  services/thumbnails/pkg/config/config.go
  services/thumbnails/pkg/server/grpc/server.go
Labels: Status:Needs-Review

#6908 Separate out grpc client to package local for search service.
  services/search/pkg/command/index.go
  services/search/pkg/command/server.go
Labels: Status:Needs-Review

#6917 Separate out grpc client to package local for ocs service.
  services/ocs/pkg/command/server.go
  services/ocs/pkg/config/config.go
  services/ocs/pkg/service/v0/users.go
Labels: Status:Needs-Review

#6915 Remove grpc.DefaultClient() reference from policies and use only one grpc client in proxy.
  services/proxy/pkg/command/server.go
  services/proxy/pkg/config/config.go
  services/proxy/pkg/middleware/policies.go
Labels: Status:Needs-Review
