Repository owncloud/ocis, pull requests merged in 2024-08, with the labels that each got.

#9721 [docs-only] [chore] update env_vars.yaml
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#9713 [tests-only][ful-ci] adjust tests and expected failure list
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/FavoritesContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties/setFileProperties.feature
Labels: QA:team

#9729 [tests-only][full-ci] adjust tests and expected-failure list
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
Labels: QA:team

#9445 [tests-only][full-ci] added test coverage for sharing file between spaces via secure view role
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
Labels: QA:team

#9741 use less selectors
  changelog/unreleased/use-less-selectors.md
  services/proxy/pkg/command/server.go
  services/proxy/pkg/proxy/proxy_integration_test.go
  services/proxy/pkg/router/router.go
  services/proxy/pkg/router/router_test.go
  services/proxy/pkg/user/backend/cs3.go
Labels: Type:Bug

#9742 [tests-only][full-ci] added test for copying files between spaces with secure viewer role using old/new dav-path-versions
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
Labels: QA:team

#9740 Nats registry fixes
  changelog/unreleased/fix-natsjskv-registry-2.md
  ocis-pkg/natsjsregistry/registry.go
  ocis-pkg/natsjsregistry/watcher.go
  ocis-pkg/registry/service.go
Labels: Type:Bug

#9437 [tests-only][full-ci]extending test cases for copying file when shared with secure viewer
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
Labels: QA:team

#9732 [docs-only]adding documemtation for graph api (Permissions)
  docs/apis/http/graph/permissions.md
Labels: QA:team

#9705 [tests-only] [full-ci] Test for file deletion activity
  tests/acceptance/features/apiGraph/activities.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#9754 [tests-only] fix COPY to mountpoint tests
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/SharingNgContext.php
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
Labels: QA:team

#9769 [tests-only][full-ci] add test to list multiple shares
  tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9731 [tests-only] [full-ci] Test to check move activity of file
  tests/acceptance/features/apiGraph/activities.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#9786 [tests-only][full-ci] adjust tests and expected-failure list
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/FavoritesContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiAuth/webDavLOCKAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPOSTAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPUTAuth.feature
  tests/acceptance/features/coreApiFavorites/favorites.feature
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/coreApiWebdavOperations/search.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolder.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
Labels: QA:team

#9793 [docs-only] Text only, fix text defaults for ocis container (production/release)
  deployments/examples/ocis_full/.env
  docs/ocis/deployment/ocis_full.md
Labels: Topic:Documentation

#9743 [tests-only] [full-ci] Test for resource(file|folder) rename activity
  tests/acceptance/features/apiGraph/activities.feature
Labels: QA:team

#9807 [docs-only] Mini text only fix for .env
  deployments/examples/ocis_full/.env
Labels: Topic:Documentation

#9795 [full-ci][tests-only]add test for api activities after sharing a file
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiActivities/shareActivities.feature
Labels: QA:team

#9803 [test-only][full-ci] add test for api activities of a file after link creation and deletion
  tests/acceptance/features/apiActivities/shareActivities.feature
Labels: QA:team

#9811 Fix some deployment stuff
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/ocis.yml
  deployments/examples/ocis_full/onlyoffice.yml
Labels: Topic:Documentation

#9796 [tests-only] [full-ci] Test to check activities of a folder
  tests/acceptance/features/apiGraph/activities.feature
Labels: QA:team

#9804 [full-ci][tests-only] adding documemtation for graph api (Role)
  docs/apis/http/graph/role.md
Labels: QA:team

#9845 [docs-only] Document the expected location of the ocmproviders.json file
  services/ocm/README.md
Labels: Topic:Documentation

#9818 [test-only][full-ci] add test to check sharee activities
  tests/acceptance/features/apiActivities/shareActivities.feature
Labels: QA:team

#9846 [docs-only][chore] Regular envvar yaml maintenance
  docs/helpers/env_vars.yaml
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#9824 [tests-only][full-ci] add test to check add and remove member acivities
  tests/acceptance/features/apiActivities/shareActivities.feature
Labels: QA:team

#9847 [docs-only][stable-5.0] ocis_wopi deployment example, make data and config volumes configurable
  deployments/examples/ocis_wopi/.env
  deployments/examples/ocis_wopi/collabora.yml
  deployments/examples/ocis_wopi/ocis.yml
  deployments/examples/ocis_wopi/onlyoffice.yml
Labels: Topic:Documentation

#9848 [docs-only] Update ennvar text and readme in ocm
  services/ocm/README.md
  services/ocm/pkg/config/config.go
Labels: Topic:Documentation

#9857 Fix activitylog translations
  Makefile
  changelog/unreleased/fix-acitivity-translations.md
  services/activitylog/pkg/service/l10n/.tx/config
  services/activitylog/pkg/service/l10n/userlog.pot
Labels: Topic:Documentation

#9869 [docs-only] Fix dev docs release roadmap image link
  docs/ocis/release_roadmap.md
Labels: Topic:Documentation

#9877 [docs-only] Link fix for dev docs
  docs/ocis/release_roadmap.md
Labels: Topic:Documentation

#9882 [docs-only] Add a note in dev docs/build the docs
  docs/helpers/README.md
  docs/ocis/development/build-docs.md
Labels: Topic:Documentation

#9875 [tests-only][full-ci] add test to check activity after language translation
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#9889 [tests-only][full-ci] adjust the activity language translation
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#9894 [docs-only] Improve dev docs
  docs/ocis/development/beta-testplan.md
  docs/ocis/development/build-docs.md
  docs/ocis/development/build.md
  docs/ocis/development/continuous-integration.md
  docs/ocis/development/debugging.md
  docs/ocis/development/deprecating-variables.md
  docs/ocis/development/envvars.md
  docs/ocis/development/profiling.md
  docs/ocis/development/testing.md
  docs/ocis/development/unit-testing/_index.md
  docs/ocis/development/unit-testing/testing-pkg.md
  docs/services/general-info/deprecating-variables.md
  docs/services/general-info/envvar-scopes.md
  docs/services/general-info/new-service-checklist.md
  services/activitylog/README.md
Labels: Topic:Documentation

#9897 [docs-only][chore] Update envvars yaml
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#9901 [docs-only] Update add-translations.md
  docs/services/general-info/add-translations.md
Labels: Topic:Documentation

#9904 [docs-only] Forgotten revisions purge docs
  ocis/README.md
Labels: Topic:Documentation

#9864 [tests-only] adjust expected-failure list and archive related tests
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiArchiver/downloadById.feature
  tests/acceptance/features/apiArchiver/downloadByPath.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/bootstrap/ArchiverContext.php
  vendor-bin/behat/composer.json
Labels: QA:team

#9905 List OCM permissions as graph drive item permissions
  changelog/unreleased/list-ocm-permissions.md
  services/graph/pkg/service/v0/api_driveitem_permissions.go
  services/graph/pkg/service/v0/base.go
  services/graph/pkg/service/v0/utils.go
Labels: Type:Bug

#9907 [docs-only] Set the correct removal version
  services/notifications/pkg/config/config.go
  services/web/pkg/config/config.go
Labels: Topic:Documentation

#9861 [tests-only] [full-ci] Test for activity filters
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiActivities/activities.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#9885 [tests-only][full-ci]add test coverage for `/app/open` endpoint
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiCollaboration/wopi.feature
  tests/acceptance/features/bootstrap/WebDav.php
  tests/config/drone/app-registry.yaml
  tests/config/drone/hosting-discovery.xml
Labels: QA:team

#9918 [docs-only] Update README.md of the gateway service
  services/gateway/README.md
Labels: Topic:Documentation

#9911 [tests-only][full-ci] add test coverage to open text file with `/app/open` endpoint
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9916 [docs-only ] Add and correct registry related content.
  docs/services/general-info/registry.md
  ocis/README.md
  services/nats/README.md
Labels: Topic:Documentation

#9851 [tests-only] fix TUS upload checksums
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/optionsRequest.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
Labels: QA:team

#9924 [tests-only][full-ci] reorganize test folders within the acceptance directory
  .codacy.yml
  Makefile
  tests/acceptance/TestHelpers/Asserts/WebDav.php
  tests/acceptance/TestHelpers/CliHelper.php
  tests/acceptance/TestHelpers/EmailHelper.php
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/TestHelpers/HttpLogger.php
  tests/acceptance/TestHelpers/HttpRequestHelper.php
  tests/acceptance/TestHelpers/OcisConfigHelper.php
  tests/acceptance/TestHelpers/OcisHelper.php
  tests/acceptance/TestHelpers/OcmHelper.php
  tests/acceptance/TestHelpers/OcsApiHelper.php
  tests/acceptance/TestHelpers/SettingsHelper.php
  tests/acceptance/TestHelpers/SetupHelper.php
  tests/acceptance/TestHelpers/SharingHelper.php
  tests/acceptance/TestHelpers/SpaceNotFoundException.php
  tests/acceptance/TestHelpers/TranslationHelper.php
  tests/acceptance/TestHelpers/UploadHelper.php
  tests/acceptance/TestHelpers/UserHelper.php
  tests/acceptance/TestHelpers/WebDavHelper.php
  tests/acceptance/bootstrap/ArchiverContext.php
  tests/acceptance/bootstrap/AuthContext.php
  tests/acceptance/bootstrap/CapabilitiesContext.php
  tests/acceptance/bootstrap/ChecksumContext.php
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/bootstrap/FavoritesContext.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/FilesVersionsContext.php
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/bootstrap/NotificationContext.php
  tests/acceptance/bootstrap/OCSContext.php
  tests/acceptance/bootstrap/OcisConfigContext.php
  tests/acceptance/bootstrap/OcmContext.php
  tests/acceptance/bootstrap/Provisioning.php
  tests/acceptance/bootstrap/PublicWebDavContext.php
  tests/acceptance/bootstrap/SearchContext.php
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/bootstrap/ShareesContext.php
  tests/acceptance/bootstrap/Sharing.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/bootstrap/TUSContext.php
  tests/acceptance/bootstrap/TagContext.php
  tests/acceptance/bootstrap/TrashbinContext.php
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/bootstrap/WebDavLockingContext.php
  tests/acceptance/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/bootstrap/bootstrap.php
  tests/acceptance/config/behat-core.yml
  tests/acceptance/config/behat.yml
Labels: QA:team

#9922 [tests-only][full-ci]added test for sharee to open file with `/app/open` endpoint
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9937 [tests-only][full-ci] update path for ldap-user.ldif file for Reva
  tests/acceptance/config/behat-core.yml
  tests/acceptance/config/behat.yml
Labels: QA:team

#9912 [tests-only][full-ci]Added test for public user using `/app/open` endpoint
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9932 [tests-only] [full-ci] Add test coverage for copying file using file id from share space
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#9945 [tests-only][full-ci] added test to open file with unsupported file format
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9936 [tests-only][full-ci]Add tests for checking file info on fake office
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
Labels: QA:team
