Repository owncloud/ocis, pull requests merged in 2024-11, with the labels that each got.

#10460 [docs-only][chore] update env_vars.yaml
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10471 [docs-only] Add comment in ocis_full / onlyoffice.yml
  deployments/examples/ocis_full/onlyoffice.yml
Labels: Topic:Documentation

#10475 [docs-only] Update collaboration envvar descriptions
  services/collaboration/pkg/config/app.go
Labels: Topic:Documentation

#10478 [docs-only] SSE_KEEPALIVE_INTERVAL envvar version consistenty
  services/sse/pkg/config/config.go
Labels: Topic:Documentation

#10380 [tests-only][full-ci] listing permission with role Space Editor Without Version enabled
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
Labels: QA:team

#10477 [docs-only] Remove/fix deprecated items from env_vars.yaml
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10483 [docs-only] Adding OCIS_MAX_CONCURRENCY to storage_users service
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#10491 [docs-only] Update envvars.yaml based on recent changes
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10499 [docs-only] Create envvar delta files after v5 to master (v7.0.0)
  docs/helpers/changed_envvars.py
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-deprecated.adoc
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-removed.adoc
  docs/services/general-info/env-var-deltas/make-adoc-table-from-python.txt
Labels: Topic:Documentation

#10508 [docs-only] Update env_vars.yaml due to recent changes
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10509 [docs-only] Update added envvar table due to recent changes
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
Labels: Topic:Documentation

#10511 [docs-only] One more added envvar change found
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
Labels: Topic:Documentation

#10314 [tests-only][full-ci] adding test coverage for backup consistency
  tests/acceptance/features/cliCommands/backupConsistency.feature
Labels: QA:team

#10521 [docs-only] Add important comment to .env in ocis_full deployment
  deployments/examples/ocis_full/.env
Labels: Topic:Documentation

#10520 [docs-only] Helper readme update
  docs/helpers/README.md
  docs/services/general-info/env-var-deltas/make-adoc-and-md-files.txt
  docs/services/general-info/env-var-deltas/make-adoc-table-from-md.txt
  docs/services/general-info/env-var-deltas/make-adoc-table-from-python.txt
Labels: Topic:Documentation

#10418 [tests-only][full-ci] run cron job on both config, with and without `remote.php` in dav path
  .drone.star
  tests/acceptance/run.sh
Labels: QA:team

#10485 [tests-only][full-ci] add test to check copy activities of destination file and folder
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10537 [docs-only] Claim update process (proxy service readme)
  services/proxy/README.md
Labels: Topic:Documentation

#10556 [docs-only] Text fix in proxy readme
  services/proxy/README.md
Labels: Topic:Documentation

#10409 [tests-only][full-ci] add test to check activities of destination file and folder by moving a file using file-id
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiActivities/activitiesByFileId.feature
Labels: QA:team

#10566 [docs-only] Improve error messages for health command output
  ocis-pkg/shared/errors.go
Labels: Topic:Documentation

#10534 [tests-only][full-ci] add test to check activities of destination file and folder by copying a file using file-id
  tests/acceptance/features/apiActivities/activitiesByFileId.feature
Labels: QA:team

#10579 [docs-only][chore] Update env_vars.yaml
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10575 fix node cache ttl updates
  changelog/unreleased/fix-node-cache-ttl-updates.md
  go.mod
  go.sum
  vendor/go-micro.dev/v4/registry/cache/cache.go
  vendor/modules.txt
Labels: Type:Bug

#10581 [docs-only] Update the added envvars adoc table
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
Labels: Topic:Documentation

#10584 use gateway selector
  changelog/unreleased/collaboration-gateway-selector.md
  services/collaboration/pkg/service/grpc/v0/option.go
  services/collaboration/pkg/service/grpc/v0/service.go
  services/collaboration/pkg/service/grpc/v0/service_test.go
Labels: Type:Bug

#10583 reuse go-micro service clients
  changelog/unreleased/reuse-go-micro-service.md
  services/graph/pkg/service/v0/drives.go
  services/graph/pkg/service/v0/graph_test.go
Labels: Type:Bug

#10565 [tests-only][full-ci] adding test coverage for sharing file with ocm
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#10516 [tests-only][full-ci] extend webdav tests for old, new and spaces path
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature
  tests/acceptance/features/apiAccountsHashDifficulty/webDavPUTAuthInvalid.feature
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiDepthInfinity/propfind.feature
  tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
  tests/acceptance/features/coreApiAuth/webDavMOVEAuth.feature
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavDelete/deleteFile.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/restoreVersion.feature
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
  tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFileUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
Labels: QA:team

#10558 [tests-only][full-ci] refactor `When` steps and step defns while moving, copying and renaming files and folders
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#10610 [tests-only][full-ci] merge similar test scenraios in antivirus test
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#10597 [tests-only] add tests to check file uploads with same mtime and different content
  tests/acceptance/bootstrap/TUSContext.php
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtime.feature
Labels: QA:team

#10482 [tests-only][full-ci] web e2e with multiple storage-users services
  .drone.star
Labels: QA:team

#10415 [tests-only][full-ci] add test to upload file to a shared folder via TUS by federated user
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiOcm/share.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#10625 [docs-only] Update imgage versions for the ocis_full deployment example
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/onlyoffice.yml
Labels: Topic:Documentation

#10620 [docs-only] Describe CLI-API commands in auth-app to manage tokens
  services/auth-app/README.md
Labels: Topic:Documentation

#10622 [tests-only][full-ci]add scenarios to expected failure file while running without remote.php
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtime.feature
Labels: QA:team

#10628 [tests-only] cleanup unnecessary env variables
  .drone.star
  tests/acceptance/TestHelpers/BehatHelper.php
  tests/acceptance/TestHelpers/OcisHelper.php
  tests/acceptance/bootstrap/Provisioning.php
  tests/acceptance/bootstrap/PublicWebDavContext.php
  tests/acceptance/docker/src/run-tests.sh
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
Labels: QA:team

#10617 [tests-only][full-ci] Add test coverage for correct parent folder reference in activity messages
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10630 [docs-only] Fix ocis_full for services to be started manually
  deployments/examples/ocis_full/.env
  deployments/examples/ocis_full/clamav.yml
  deployments/examples/ocis_full/ocis.yml
Labels: Topic:Documentation

#10631 [docs-only] Fix capitalization of some curl commands
  services/auth-app/README.md
Labels: Topic:Documentation

#10636 add public link share feature to expected failure file
  tests/acceptance/expected-failures-without-remotephp.md
Labels: QA:team

#10644 [tests-only][full-ci] ci: cleanup drone config
  .drone.star
Labels: QA:team

#10653 [docs-only] Deprecate OCS related frontend envvars because the OCS API is deprecated
  docs/helpers/env_vars.yaml
  services/frontend/README.md
  services/frontend/pkg/config/config.go
  services/sharing/pkg/config/config.go
Labels: Topic:Documentation

#10659 [docs-only] The env_var.yaml file needs to be recreated
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10664 [docs-only] Update the added/removed/deprecated envvars adoc table
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-deprecated.adoc
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-removed.adoc
Labels: Topic:Documentation

#10668 [docs-only] Show more info in deprecation table
  docs/helpers/changed_envvars.py
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-added.adoc
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-deprecated.adoc
  docs/services/general-info/env-var-deltas/5.0.0-7.0.0-removed.adoc
Labels: Topic:Documentation

#10673 [docs-only] Update posixfs-storage-driver.md
  docs/architecture/posixfs-storage-driver.md
Labels: Topic:Documentation

#10618 [tests-only][full-ci] add tests to check activities of space's resource after updating it's share
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiActivities/shareActivities.feature
  tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
Labels: QA:team

#10651 [tests-only][full-ci] add tests to download thumbnail preview of a federated share image
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#10609 [tests-only][full-ci]Add test for template
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
  tests/acceptance/features/apiCollaboration/wopi.feature
  tests/acceptance/filesForUpload/template.dotx
  tests/acceptance/filesForUpload/template.ott
Labels: QA:team

#10523 [tests-only][full-ci] adding test for editing shared file(OCM) by the share receiver
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#10626 [tests-only][full-ci] refactor multiple when steps in OCM tests
  tests/acceptance/bootstrap/OcmContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiOcm/acceptInvitation.feature
  tests/acceptance/features/apiOcm/createInvitation.feature
  tests/acceptance/features/apiOcm/deleteFederatedConnections.feature
Labels: QA:team

#10351 [test-only] add test for checking service ready and health
  .drone.star
  tests/acceptance/TestHelpers/OcisHelper.php
  tests/acceptance/bootstrap/AuthContext.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAntivirus/serviceAvailabilityCheck.feature
  tests/acceptance/features/apiCollaboration/serviceAvailabilityCheck.feature
  tests/acceptance/features/apiNotification/serviceAvailabilityCheck.feature
  tests/acceptance/features/apiServiceAvailability/serviceAvailabilityCheck.feature
Labels: QA:team

#10679 [tests-only] do not use unnecessary array
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/bootstrap/NotificationContext.php
Labels: QA:team

#10681 [docs-only] Add memory considerations to the antivirus service
  services/antivirus/README.md
Labels: Topic:Documentation
