Repository owncloud/ocis, pull requests merged in 2024-01, with the labels that each got.

#8092 [full-ci] [tests-only] Added test for share invitation with expiration date
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8090 [tests-only] Retry space listing if required space is not found (#7521)
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#8095 [full-ci] [tests-only] Forward port of PR #8092
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8088 [tests-only][full-ci] added test to update a file with empty content
  tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
Labels: QA:team

#8097 [tests-only][full-ci] forward port added test to update file with empty content
  tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
Labels: QA:team

#8103 [tests-only][full-ci] Added test to update role and expiration date for share link (sharingNg)
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8093 [tests-only][full-ci] added issue tag `@issue-7257` on added scenarios
  tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
Labels: QA:team

#8108 [tests-only][full-ci] added issue-7257 tag on scenario
  tests/acceptance/features/coreApiWebdavUpload1/uploadFile.feature
Labels: QA:team

#8113 [tests-only] Extend API test coverage for MOVE between spaces
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
Labels: QA:team

#8098 [tests-only]tests: add tests for removing share permission
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/deletePermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8099 [tests-only]tests: add tests for removing share permission in group share
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/deletePermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8126 [tests-only] Extend API test coverage for MOVE between spaces using file-id
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#8079 [tests-only][full-ci]Added tests for setting password in a public share link
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8138 [tests-only][full-ci]Added tests for setting password in a public share (#8079)
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8145 [tests-only][full-ci] fixing json assertion in file addUserToGroup.feature
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
Labels: QA:team

#8146 [tests-only][full-ci] fixing json assertion in file removeUserFromGroup.feature
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
Labels: QA:team

#8142 fix idp cs3 backend session refresh
  changelog/unreleased/fix-cs3-backend.md
  services/idp/pkg/backends/cs3/identifier/cs3.go
  services/idp/pkg/backends/cs3/identifier/session.go
Labels: Type:Bug

#8148 [tests-only][full-ci] fixing json assertion in file listPpermissions.feature
  tests/acceptance/features/apiSharingNg/listPermissions.feature
Labels: QA:team

#8134 [tests-only] tests: refactor test script for removing permission from share
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8135 [tests-only] Added API tests coverage for MOVE within same folder with same filename
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
Labels: QA:team

#8159 [test-only] [back-port] Change naming in sharingNG api-tests
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/deletePermissions.feature
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8013 [tests-only][full-ci] Added tests for getting versions of a file after moving it to shared project folder
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#8139 [full-ci] [tests-only] Added test for sending share invitation to disabled user
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8130 [tests-only] tests: add tests for removing share permission
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/deletePermissions.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8174 [full-ci] [tests-only] Added test for sending share invitation to disabled user
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/deleteUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8179 [full-ci] [tests-only] Added test for sending share invitation to deleted user
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8172 [tests-only][full-ci] Added tests for getting versions of a file after moving it to shared project folder
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#8110 [full-ci] [tests-only] Backport of pr `8179`, `8166`
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/createUser.feature
  tests/acceptance/features/apiGraph/editUser.feature
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8128 [tests-only]tests: add tests for removing share permission in link share
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/deletePermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8183 [tests-only] Added test coverage for checking file versions after MOVE
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#8190 [tests-only][fordward-port] Add tests for remove permissions link share
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/deletePermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8191 [ci] Add step to show ocis logs in k6 pipeline
  .drone.star
  tests/config/drone/run_k6_tests.sh
Labels: QA:team

#8167 [tests-only][full-ci] added test to send share invitation to multiple groups at once
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8196 [tests-only][full-ci] backport added test to send share invitation to multiple groups at once
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8168 [tests-only][full-ci] added test to send share invitation to user and gruop at once
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8203 [tests-only][full-ci] backport added test to send share invitation to user and gruop at once
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8114 [tests-only][full-ci] added test to reshare a share invitation to other user
  tests/acceptance/features/apiSharingNg/reshare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8096 [tests-only][full-ci] Added tests for searching groups by a normal user
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8006 [tests-only][full-ci] Restructure the steps implementation for group delete to use graph API endpoint
  tests/TestHelpers/UserHelper.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: QA:team

#8094 [tests-only][full-ci] Added API tests for searching users by normal user using display name
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8240 [tests-only][full-ci] forward port user and group search tests
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/addUserToGroup.feature
  tests/acceptance/features/apiGraph/getGroup.feature
  tests/acceptance/features/apiGraph/getUser.feature
  tests/acceptance/features/apiGraph/removeUserFromGroup.feature
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8210 [tests-only][full-ci]Added type internal for share link (public)
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/linkShare.feature
Labels: QA:team

#8194 [tests-only][full-ci]Added test for banned password to create public link
  tests/acceptance/features/apiSharingNg/linkShare.feature
Labels: QA:team

#8227 [tests-only][full-ci] Backport Restructure the steps implementation for group deletion
  tests/TestHelpers/UserHelper.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: QA:team

#8245 [tests-only][full-ci]Forward port `setpassword` and `internallink`
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/linkShare.feature
Labels: QA:team

#8212 [tests-only][ci] split large API test suites
  .drone.star
  tests/acceptance/config/behat-core.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraphUserGroup/addUserToGroup.feature
  tests/acceptance/features/apiGraphUserGroup/changeOwnPassword.feature
  tests/acceptance/features/apiGraphUserGroup/createGroup.feature
  tests/acceptance/features/apiGraphUserGroup/createGroupCaseSensitive.feature
  tests/acceptance/features/apiGraphUserGroup/createUser.feature
  tests/acceptance/features/apiGraphUserGroup/deleteGroup.feature
  tests/acceptance/features/apiGraphUserGroup/deleteUser.feature
  tests/acceptance/features/apiGraphUserGroup/editGroup.feature
  tests/acceptance/features/apiGraphUserGroup/editUser.feature
  tests/acceptance/features/apiGraphUserGroup/getGroup.feature
  tests/acceptance/features/apiGraphUserGroup/getUser.feature
  tests/acceptance/features/apiGraphUserGroup/getUserOwnInformation.feature
  tests/acceptance/features/apiGraphUserGroup/removeUserFromGroup.feature
  tests/acceptance/features/apiSearch1/apiSpaceSearch.feature
  tests/acceptance/features/apiSearch1/dateSearch.feature
  tests/acceptance/features/apiSearch2/mediaTypeSearch.feature
  tests/acceptance/features/apiSearch2/tagSearch.feature
  tests/acceptance/features/apiSearchContent/contentSearch.feature
  tests/acceptance/features/coreApiAuth/ocsDELETEAuth.feature
  tests/acceptance/features/coreApiAuth/ocsGETAuth.feature
  tests/acceptance/features/coreApiAuth/ocsPOSTAuth.feature
  tests/acceptance/features/coreApiAuth/ocsPUTAuth.feature
  tests/acceptance/features/coreApiAuth/webDavCOPYAuth.feature
  tests/acceptance/features/coreApiAuth/webDavDELETEAuth.feature
  tests/acceptance/features/coreApiAuth/webDavLOCKAuth.feature
  tests/acceptance/features/coreApiAuth/webDavMKCOLAuth.feature
  tests/acceptance/features/coreApiAuth/webDavMOVEAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPOSTAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPROPFINDAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPROPPATCHAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPUTAuth.feature
  tests/acceptance/features/coreApiAuth/webDavSpecialURLs.feature
  tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShareChain.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareUpdate.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolder.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
  tests/acceptance/features/coreApiWebdavProperties/setFileProperties.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFileUsingOldChunking.feature
  tests/acceptance/run.sh
Labels: QA:team

#8105 [tests-only][full-ci] Extend API test coverage for replacing file with zero-byte file via TUS upload
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
Labels: QA:team

#8226 [full-ci] [tests-only] Modified tests so sharee can check for received shares
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8265 [tests-only][full-ci] fixing incorrect json format for json assertion steps
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/createSpace.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
Labels: QA:team

#8241 [tests-only][full-ci] Added API tests for searching users by normal user
  tests/acceptance/features/apiGraphUserGroup/getUser.feature
Labels: QA:team

#7000 [tests-only][full-ci] adding user quota using graph api instead of Provisioning api
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
Labels: QA:team

#8175 [tests-only][full-ci] added test to send share invitation to unknown group
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8181 [tests-only][full-ci]added test to share resource to an already shared group
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8275 [tests-only][full-ci] added test to reshare resources to other users SharingNg
  tests/acceptance/features/apiSharingNg/reshare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8188 [tests-only] Added API test coverage for checking file versions after multiple restores
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#8010 [tests-only]test: add test for shared with me
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8147 [tests-only][full-ci] Added test to reshare a resource to other users with higher roles
  tests/acceptance/features/apiSharingNg/reshare.feature
Labels: QA:team

#8129 [full-ci] [tests-only] Added test for sending share invitation to wrong objectId
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8234 chore: bump icap client which fixes defer error handling
  go.mod
  go.sum
  vendor/github.com/egirna/icap-client/client.go
  vendor/github.com/egirna/icap-client/request.go
  vendor/modules.txt
Labels: Type:Bug

#8136 [full-ci] [tests-only] Add test to send share invitation with wrong recipient type
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8137 [full-ci] [tests-only] Add test to send share invitation with empty recipient type
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8293 enhancement: add parent name and path to shared the shared by me endpoint
  services/graph/pkg/service/v0/driveitems.go
Labels: Status:Needs-Review, Category:Enhancement

#8308 [full-ci] [tests-only] Added test for sending share invitation to user already received share
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8316 [tests-only] Adjust MOVE tests to expect 502 and remove from expected failure
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
Labels: QA:team

#8290 [tests-only][full-ci] Make graph api default in test
  .drone.star
  docs/ocis/development/testing.md
  tests/TestHelpers/OcisHelper.php
  tests/acceptance/docker/src/acceptance.yml
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
Labels: QA:team

#8323 [tests-only][full-ci] updating step to use graph api when sharing resources
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#8319 [tests-only][full-ci] added test to share a disabled project space
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#8330 [tests-only] fix sharing sub-folder test scenario
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
Labels: QA:team
