Repository owncloud/ocis, pull requests merged in 2024-06, with the labels that each got.

#9295 [docs-only] Update thumbnails README.md
  services/thumbnails/README.md
Labels: Topic:Documentation

#9296 [docs-only] Update storage-users README.md
  services/storage-users/README.md
Labels: Topic:Documentation

#9298 [docs-only] fix two service readme's
  services/storage-users/README.md
  services/thumbnails/README.md
Labels: Topic:Documentation

#9300 [tests-only][full-ci]Add test for updating link of a folder in project-space using permissions endpoint.
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
Labels: QA:team

#9314 [docs] add docs for available ociswrapper serve sub-command options
  tests/ociswrapper/README.md
Labels: QA:team

#9325 [docs-only] Update thumbnail README.md with respect to SecureView
  services/thumbnails/README.md
Labels: Topic:Documentation

#9311 [tests-only][full-ci]adding test for sharing space via secure role
  tests/acceptance/features/apiSharingNg/listPermissions.feature
Labels: QA:team

#9297 [tests-only][full-CI] adding test for updating share link of a resource in project space.
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
Labels: QA:team

#9349 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
Labels: QA:team

#9351 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
Labels: QA:team

#9337 [tests-only][full-ci]adding secure view in apisharingNg feature file
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#9352 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiAuth/ocsPUTAuth.feature
Labels: QA:team

#9354 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiAuth/ocsDELETEAuth.feature
  tests/acceptance/features/coreApiAuth/ocsGETAuth.feature
  tests/acceptance/features/coreApiAuth/ocsPOSTAuth.feature
Labels: QA:team

#9343 [tests-only][full-ci] lint the gherkin feature files
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiContract/spacesReport.feature
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiGraphUserGroup/addUserToGroup.feature
  tests/acceptance/features/apiGraphUserGroup/changeOwnPassword.feature
  tests/acceptance/features/apiGraphUserGroup/createUser.feature
  tests/acceptance/features/apiGraphUserGroup/editUser.feature
  tests/acceptance/features/apiGraphUserGroup/getGroup.feature
  tests/acceptance/features/apiGraphUserGroup/getUser.feature
  tests/acceptance/features/apiGraphUserGroup/getUserOwnInformation.feature
  tests/acceptance/features/apiGraphUserGroup/removeUserFromGroup.feature
  tests/acceptance/features/apiGraphUserGroup/searchUserIncludingEmail.feature
  tests/acceptance/features/apiNotification/deprovisioningNotification.feature
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/apiReshare/resharing.feature
  tests/acceptance/features/apiSearch1/dateSearch.feature
  tests/acceptance/features/apiSearch1/search.feature
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature
  tests/acceptance/features/apiSharingNg/removeAccessToDriveItem.feature
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
  tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/createSpace.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/setQuota.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolder.feature
Labels: QA:team

#9357 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
Labels: QA:team

#9246 [tests-only][full-ci] adding test for removing link share of a project space using permissions endpoint
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9368 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
Labels: QA:team

#9370 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareManagementToShares/mergeShare.feature
Labels: QA:team

#9381 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
Labels: QA:team

#9362 [tests-only][full-ci] added tests for creating quickLink using permissions endpoint
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9356 [tests-only][full-ci] implement test for sharee trying to lock shared file/folder in secure view in lockFiles feature file
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiLocks/lockFiles.feature
Labels: QA:team

#9387 [docs-only] [5.0] Fix typo and rerun make docs-generate
  docs/helpers/extended_vars.yaml
  services/gateway/pkg/config/config.go
  services/graph/pkg/config/cache.go
  services/postprocessing/pkg/config/config.go
  services/proxy/pkg/config/config.go
  services/settings/pkg/config/config.go
  services/storage-system/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/userlog/pkg/config/config.go
Labels: Topic:Documentation

#9375 [tests-only][full-ci] add tests to create quick link of space drive using root endpoint
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9409 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
Labels: QA:team

#9410 [full-ci][tests-only] renaming step for sending invitation with all allowed permission
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9408 [tests-only][full-ci] downloading file shared via secure view role
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
Labels: QA:team

#9417 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
Labels: QA:team

#9420 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
Labels: QA:team

#9407 [full-ci][tests-only] renaming the scenario in linkShare to be more consistent
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
Labels: QA:team

#9406 [full-ci][tests-only] use correct parameters in listFolderAndReturnResponseXml method
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#9421 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: QA:team

#9423 [tests-only][full-ci] add test coverage for list permission for non-member user in project-space
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
Labels: QA:team

#9422 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: QA:team

#9418 [tests-only][full-ci] extend test for trying to move file/folder within shared folder with secure view role
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
Labels: QA:team

#9430 [full-ci][tests-only] fix status code check in theUserCreatesASpaceWithQuotaUsingTheGraphApi in SpacesContext
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9424 [tests-only][full-ci] extend test for trying to move file/folder within shares-personal drive with secure view role
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
Labels: QA:team

#9431 [full-ci][tests-only] Adjusted test as .htaccess is not a banned file
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFileToBlacklistedName.feature
Labels: QA:team

#9433 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
Labels: QA:team

#9435 [full-ci] [tests-only] Removed failing ocs scenarios
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
Labels: QA:team

#9438 fix(sharing-ng): permission listings for personal and virtual drive items
  changelog/unreleased/fix-sharingng-permission-listings.md
  services/graph/pkg/service/v0/api_driveitem_permissions.go
  services/graph/pkg/service/v0/drives.go
  services/graph/pkg/service/v0/educationuser.go
  services/graph/pkg/service/v0/users.go
  services/graph/pkg/service/v0/utils.go
  tests/acceptance/features/apiSharingNg/listPermissions.feature
Labels: Type:Bug, Status:Needs-Review, Priority:p2-high

#9454 [tests-only] add a Given step to check for the share sync status
  tests/acceptance/features/bootstrap/SharingNgContext.php
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
Labels: QA:team

#9459 [docs-only] Fix envvar description
  services/clientlog/pkg/config/config.go
  services/collaboration/pkg/config/cs3api.go
Labels: Topic:Documentation

#9457 [docs-only] [chore] Maintain envvar yaml file updates (doc helper stuff)
  docs/helpers/env_vars.yaml
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#9455 [tests-only][full-ci] remove unused index paramater in userTriesToDownloadFileVersions in spacesContext
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/apiOcm/ocm.feature
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9439 [test-only] add testing docs to ocm test
  .drone.star
  .vscode/launch.json
  docs/ocis/development/testing.md
  ocis/pkg/command/init.go
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiOcm/ocm.feature
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/config/drone/.env-federation
  tests/config/drone/providers.json
Labels: Status:Needs-Review

#9470 [full-ci][tests-only] Remove unused array_reverse() functions
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#9491 [tests-only][full-ci] wait and check for sync status before action
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#8909 SharingNG: initial OCM support
  changelog/unreleased/initial-ocm-support-for-graph.md
  services/graph/mocks/base_graph_provider.go
  services/graph/mocks/drives_drive_item_provider.go
  services/graph/pkg/config/config.go
  services/graph/pkg/identity/backend.go
  services/graph/pkg/identity/cache.go
  services/graph/pkg/service/v0/api_driveitem_permissions.go
  services/graph/pkg/service/v0/api_driveitem_permissions_links.go
  services/graph/pkg/service/v0/api_drives_drive_item.go
  services/graph/pkg/service/v0/api_drives_drive_item_ocm.go
  services/graph/pkg/service/v0/base.go
  services/graph/pkg/service/v0/sharedwithme.go
  services/graph/pkg/service/v0/users.go
  services/graph/pkg/service/v0/utils.go
Labels: Category:Enhancement

#8904 [tests-only][full-ci] adding test for listing permission of shares drive
  tests/acceptance/features/apiSharingNg/listPermissions.feature
Labels: QA:team

#9494 [tests-only][full-ci] wait and check for sync status before performing MOVE
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
Labels: QA:team
