Repository owncloud/ocis, pull requests merged in 2024-09, with the labels that each got.

#9931 [tests-only][full-ci] add test coverage to open open-document file with /app/open-with-web endpoint
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9959 [docs-only] Fix office365 texts
  services/collaboration/README.md
  services/collaboration/pkg/config/app.go
  services/collaboration/pkg/config/wopi.go
Labels: Topic:Documentation

#9953 [tests-only][full-ci]added test to open file with non-existing file id
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9965 [docs-only] Small ocm text fix
  services/ocm/README.md
  services/ocm/pkg/config/config.go
Labels: Topic:Documentation

#9939 [tests-only][full-ci] add test coverage to open text file with /app/open-with-web endpoint
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9954 [tests-only][full-ci]added test for open file using `/app/open` endpoint with different view mode
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9971 [docs-only] Small fix for ocm envvar description text
  services/ocm/README.md
  services/ocm/pkg/config/config.go
Labels: Topic:Documentation

#9973 [docs-only] Description + CLI for Unified Roles Management
  ocis/README.md
  services/graph/README.md
  services/graph/pkg/config/unified_roles.go
Labels: Topic:Documentation

#9968 [tests-only][full-ci] test: Add test coverage for opening .odt file by public user with /app/open-with-web endpoint
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9975 [docs-only] Update translation docs + transifex configuration (add resource_name)
  docs/services/general-info/add-translations.md
  services/activitylog/pkg/service/l10n/.tx/config
  services/graph/pkg/l10n/.tx/config
  services/notifications/pkg/email/l10n/.tx/config
  services/userlog/pkg/service/l10n/.tx/config
Labels: Topic:Documentation

#9940 [tests-only] [full-ci] Add test coverage for copying file using file id from `project space`
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
Labels: QA:team

#9941 [tests-only][full-ci] add test coverage to open shared open-document file with /app/open-with-web endpoint
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9987 [docs-only] Update the notification service readme
  services/notifications/README.md
Labels: Topic:Documentation

#9969 [tests-only][full-ci] test: add test coverage for opening file using /app/open-with-web endpoint with different view mode
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9989 [docs-only] Typo fix ocis.yml
  deployments/examples/ocis_full/ocis.yml
Labels: Topic:Documentation

#9921 [tests-only][full-ci]Add tests for CheckFileInfo related to wopi protocol
  .drone.star
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
  tests/config/drone/only-office.json
Labels: QA:team

#9995 [docs-only] Fix a typo in graph service readme
  services/graph/README.md
Labels: Topic:Documentation

#9984 [tests-only][full-ci] test: add test coverage for opening file with unsupported file fromat using /app/open-with-web endpoint
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9972 [tests-only][full-ci] add tests for new role space editor without versions
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/bootstrap/OcisConfigContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
Labels: QA:team

#9900 [tests-only][full-ci] cleanup ocis/oc10 parallel-deployment tests
  Makefile
  docs/ocis/development/testing.md
  tests/acceptance/TestHelpers/HttpRequestHelper.php
  tests/acceptance/TestHelpers/OcisHelper.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/Provisioning.php
  tests/parallelDeployAcceptance/.gitignore
  tests/parallelDeployAcceptance/config/behat.yml
  tests/parallelDeployAcceptance/config/ldap_users_groups.ldif
  tests/parallelDeployAcceptance/drone/ldap/ldif/10_owncloud_schema.ldif
  tests/parallelDeployAcceptance/drone/oc10/10-custom-config.sh
  tests/parallelDeployAcceptance/drone/oc10/ldap-config.tmpl.json
  tests/parallelDeployAcceptance/drone/oc10/oidc.config.php
  tests/parallelDeployAcceptance/drone/ocis/proxy.yaml
  tests/parallelDeployAcceptance/expected-failures-API.md
  tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
  tests/parallelDeployAcceptance/features/apiWebdavOperations/downloadFile.feature
  tests/parallelDeployAcceptance/features/bootstrap/ParallelContext.php
  tests/parallelDeployAcceptance/features/bootstrap/bootstrap.php
Labels: QA:team

#9982 [tests-only][full-ci] add tests to check versions of file in a space shared via link with viewer/editor role
  tests/acceptance/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
Labels: QA:team

#10029 [docs-only]updating test document
  docs/ocis/development/testing.md
Labels: QA:team

#9985 [tests-only][full-ci] test: add test coverage for opening file with non-existing fileId using /app/open-with-web endpoint
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#10047 [docs-only] Clarify introduction version when adding an envvar to an existing one
  docs/services/general-info/envvar-scopes.md
Labels: Topic:Documentation

#10043 [docs-only][chore] Update env_vars.yaml
  docs/helpers/env_vars.yaml
  services/gateway/pkg/config/config.go
Labels: Topic:Documentation

#10050 fix ocm token
  changelog/unreleased/fix-ocm-token.md
  services/ocm/pkg/config/config.go
  services/ocm/pkg/config/defaults/defaultconfig.go
  services/ocm/pkg/config/reva.go
  services/ocm/pkg/revaconfig/config.go
Labels: Type:Bug

#10024 [tests-only][full-ci] Add test coverage for checking file info with different view mode
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
Labels: QA:team

#9960 [tests-only][full-ci]added test to create text file with `/app/new` endpoint
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9964 [tests-only][full-ci] added test to create file with .odt extension using `/app/new` endpoint
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#9967 [tests-only][full-ci] added test to create .odt file inside shared folder using `/app/new` endpoint
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#10055 [tests-only][full-ci]Add test for sending request to check file info with invalid file id
  tests/acceptance/TestHelpers/CollaborationHelper.php
  tests/acceptance/TestHelpers/EmailHelper.php
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/TestHelpers/OcmHelper.php
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
Labels: QA:team

#10062 [tests-only] [full-ci] Add test for default depth activity filter
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10044 [tests-only][full-ci] refactor userSearchesUsingWebDavAPI function to update davPath for new and spaces dav versions
  tests/acceptance/bootstrap/SearchContext.php
Labels: QA:team

#10079 [docs-only] Fix typo in envvar
  services/activitylog/pkg/config/config.go
Labels: Topic:Documentation

#10080 [docs-only] graph(docs): More details for the README
  services/graph/README.md
Labels: Topic:Documentation

#10081 [docs-only] Update the "List Unified Roles" example output
  ocis/README.md
Labels: Topic:Documentation

#10083 [docs-only] Fix translatable text string in notifications
  services/notifications/pkg/email/templates.go
Labels: Topic:Documentation

#9978 [tests-only][full-ci] added test for public user to create .odt file inside public folder
  tests/acceptance/TestHelpers/CollaborationHelper.php
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#10064 [test-only][full-ci] added test to create odt file inside deleted parent folder
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#10094 [docs-only][chore] Update env_vars.yaml
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#9983 [tests-only][full-ci] added test for public user to create odt file inside public space
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team

#10115 [docs-only][chore] Update env_vars.yaml based on recent code changes
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10131 [tests-only] skip activity translation test
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10091 [tests-only][full-ci]add edge case for check file info
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
Labels: QA:team

#10134 [tests-only][full-ci] add test to download preview of an image with all available processors
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/fixtures/fill.png
  tests/acceptance/fixtures/fit.png
  tests/acceptance/fixtures/resize.png
  tests/acceptance/fixtures/thumbnail.png
Labels: QA:team

#9842 [tests-only][full-ci] add test to check acivities by sharee
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/features/apiActivities/activities.feature
  tests/acceptance/features/apiActivities/shareActivities.feature
Labels: QA:team

#10164 [tests-only] custom error message for json validation error
  tests/acceptance/bootstrap/FeatureContext.php
Labels: QA:team

#10178 [tests-only][full-ci]add issue tag in file creating scenarios for /app/new endpoint
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: QA:team
