Repository owncloud/ocis, pull requests merged in 2024-07, with the labels that each got.

#9469 Fix ocis wopi env settings
  deployments/examples/ocis_wopi/.env
  deployments/examples/ocis_wopi/README.md
Labels: Topic:Documentation

#9509 [tests-only][full-ci] split SharingNG link share test suite
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgLinkShare/createLinkShare.feature
  tests/acceptance/features/apiSharingNgLinkShare/updateLinkShare.feature
Labels: QA:team

#8891 [tests-only] retry if auto-sync is enabled but client.synchronize is false
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/SettingsHelper.php
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/NotificationContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/SettingsContext.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9503 [full-ci][tests-only] add CI pipeline for checking lint issues using gherlint
  .drone.star
  Makefile
  tests/acceptance/config/.gherlintrc.json
Labels: QA:team

#9519 [full-ci][tests-only] remove unused stepDef function related to download with range from WebDav.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#9367 [tests-only] [full-ci] Test coverage for audio prop
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSearchContent/propfindExtractedProps.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/filesForUpload/testaudio.mp3
  tests/acceptance/filesForUpload/testavatar.jpg
Labels: QA:team

#9446 [full-ci][tests-only] Remove @skipOnRevaMaster tag from ocis
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/coreApiAuth/webDavAuth.feature
  tests/acceptance/features/coreApiAuth/webDavCOPYAuth.feature
  tests/acceptance/features/coreApiAuth/webDavDELETEAuth.feature
  tests/acceptance/features/coreApiAuth/webDavLOCKAuth.feature
  tests/acceptance/features/coreApiAuth/webDavMKCOLAuth.feature
  tests/acceptance/features/coreApiAuth/webDavMOVEAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPOSTAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPROPFINDAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPROPPATCHAuth.feature
  tests/acceptance/features/coreApiAuth/webDavPUTAuth.feature
  tests/acceptance/features/coreApiAuth/webDavSpecialURLs.feature
  tests/acceptance/features/coreApiFavorites/favorites.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiWebdavDelete/deleteFile.feature
  tests/acceptance/features/coreApiWebdavDelete/deleteFolder.feature
  tests/acceptance/features/coreApiWebdavDelete/deleteFolderContents.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
  tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
  tests/acceptance/features/coreApiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/coreApiWebdavOperations/search.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolder.feature
  tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
  tests/acceptance/features/coreApiWebdavProperties/setFileProperties.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFileUsingOldChunking.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/creationWithUploadExtension.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/lowLevelCreationExtension.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/lowLevelUpload.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtime.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
Labels: QA:team

#9557 [tests-only][full-ci] remove unused When step definitions from WebDav.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#9466 [docs-only] update env_vars.yaml post Activitylog API merge
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#9565 [tests-only][full-ci] add TUS upload API test for invalid ".." path
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
Labels: QA:team

#9545 [tests-only][full-ci]adding test for uploading file to a public link of a project space
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
Labels: QA:team

#9564 [tests-only][full-ci] remove unused Then step definitions from WebDav.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#9563 [full-ci][tests-only] Extended the tests to cover profind by sharer to shared file
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
Labels: QA:team

#9570 ci: remove storage name from pipeline names
  .drone.star
Labels: QA:team

#9576 [docs-only] Make the envvar text for the banned pwd list more precise
  services/frontend/pkg/config/config.go
  services/sharing/pkg/config/config.go
Labels: Topic:Documentation

#9577 [docs-only] [5.0] Make the envvar text for the banned pwd list more precise
  services/frontend/pkg/config/config.go
  services/sharing/pkg/config/config.go
Labels: Topic:Documentation

#9575 [tests-only][full-ci] added cli test for changing password of non-existing user
  tests/acceptance/features/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/resetUserPassword.feature
Labels: QA:team

#9582 [docs-only] Just an update of the envvars yaml file for the docs helper
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#9592 [docs-only] Add page to dev docs with services per release
  docs/services/general-info/added-services.md
Labels: Topic:Documentation

#9598 [docs-only] Docs adoc template: make a space between deprecations and standard
  docs/templates/ADOC.tmpl
Labels: Topic:Documentation

#9599 [docs-only] [5.0] Docs adoc template: make a space between deprecations and standard
  docs/templates/ADOC.tmpl
Labels: Topic:Documentation

#9600 [docs-only] Update new-service-checklist.md
  docs/services/general-info/new-service-checklist.md
Labels: Topic:Documentation

#9603 [tests-only][full-ci] test: add test coverage for mail notification with comma(,) in display name of sender
  tests/acceptance/features/apiNotification/emailNotification.feature
Labels: QA:team

#9584 [tests-only][full-ci] adding test to remove old versions of resources using cli command
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/removeFileVersions.feature
Labels: QA:team

#9475 Log user agent and remote addr on auth errors
  changelog/unreleased/log-useragent-and-remoteaddr.md
  services/proxy/pkg/middleware/oidc_auth.go
Labels: Category:Enhancement

#9606 [tests-only] add test coverage for new props from personal space
  tests/acceptance/features/apiSearchContent/propfindExtractedProps.feature
Labels: QA:team

#9612 [tests-only][full-ci] adding test for listing drive items with new metadata in personal space
  tests/acceptance/features/apiSearchContent/extractedProps.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9627 [tests-only][full-ci] adding test to remove old versions of a file using file-id using cli command
  tests/acceptance/features/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/removeFileVersions.feature
Labels: QA:team

#9593 [tests-only][full-ci] added test for updating admin password via cli
  tests/acceptance/features/bootstrap/CliContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/cliCommands/resetUserPassword.feature
Labels: QA:team

#9614 [tests-only][full-ci] adding test for listing drive items with new metadata in project space
  tests/acceptance/features/apiSearchContent/extractedProps.feature
Labels: QA:team

#9630 [tests-only][full-ci] search: reindex command for spaces
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/searchReIndex.feature
Labels: QA:team

#9639 [tests-only][full-ci] adding test to remove old versions of files from a space using space-id using CLI
  tests/acceptance/features/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/removeFileVersions.feature
Labels: QA:team

#9655 [docs-only] Fix ADOC.tmpl and ADOC_global.tmpl (missing entry)
  docs/helpers/env_vars.yaml
  docs/helpers/extended_vars.yaml
  docs/templates/ADOC.tmpl
  docs/templates/ADOC_global.tmpl
Labels: Topic:Documentation

#9645 [tests-only][full-ci] extend test cases for non-admin actions to admin resources
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/changeRole.feature
  tests/acceptance/features/apiGraph/getAssignedRole.feature
  tests/acceptance/features/apiGraph/unassignRole.feature
  tests/acceptance/features/apiGraphUserGroup/addUserToGroup.feature
  tests/acceptance/features/apiGraphUserGroup/deleteGroup.feature
  tests/acceptance/features/apiGraphUserGroup/editGroup.feature
  tests/acceptance/features/apiGraphUserGroup/editUser.feature
  tests/acceptance/features/apiGraphUserGroup/getGroup.feature
  tests/acceptance/features/apiGraphUserGroup/getUser.feature
  tests/acceptance/features/apiGraphUserGroup/removeUserFromGroup.feature
  tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/SettingsContext.php
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
Labels: QA:team

#9616 [tests-only][full-ci] adding test for listing drive items with new metadatas in share space
  tests/acceptance/features/apiSearchContent/extractedProps.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9675 [test-ony][full-ci] adding tests for `invitation` property which was missing in permissions responses
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
Labels: QA:team

#9663 [tests-only][full-ci] ensure share is available
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
  tests/acceptance/features/coreApiWebdavProperties/setFileProperties.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
  tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
Labels: QA:team

#9617 [tests-only][full-ci] cli test for delete empty trash bin directory
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/CliContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/cliCommands/cleanupEmptyTrashBin.feature
Labels: QA:team

#9678 [tests-only] [full-ci] Add test to check activity after uploading a file
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiGraph/activities.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#9694 [tests-only][full-ci] ensure shares are ready before performing actions on them
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiArchiver/downloadById.feature
  tests/acceptance/features/apiArchiver/downloadByPath.feature
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiReshare/resharing.feature
  tests/acceptance/features/apiSearch1/dateSearch.feature
  tests/acceptance/features/apiSearch1/search.feature
  tests/acceptance/features/apiSearch2/mediaTypeSearch.feature
  tests/acceptance/features/apiSearch2/tagSearch.feature
  tests/acceptance/features/apiSearchContent/contentSearch.feature
  tests/acceptance/features/apiSearchContent/extractedProps.feature
  tests/acceptance/features/apiSharingNg1/enableDisableShareSync.feature
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
  tests/acceptance/features/apiSharingNg1/propfindShares.feature
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
  tests/acceptance/features/apiSpacesShares/checksum.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/createFileFolderWhenSharesSpaceExist.feature
  tests/acceptance/features/apiSpacesShares/etagPropagation.feature
  tests/acceptance/features/apiSpacesShares/favorite.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
Labels: QA:team

#9434 [tests-only][full-ci] adding test for creating internal link share by the member of a project drive
  tests/acceptance/features/apiSharingNgLinkSharePermission/createLinkShare.feature
Labels: QA:team

#9692 use bool type for web embed delegatedAuthentication
  changelog/unreleased/fix-web-delegatedauthentication-type.md
  services/web/pkg/config/defaults/defaultconfig.go
  services/web/pkg/config/options.go
Labels: Type:Bug

#9492 ignore addresses for kubernetes registry
  changelog/unreleased/ignore-address-for-kubernetes-registry.md
  ocis-pkg/registry/registry.go
Labels: Type:Bug

#9696 [docs-only] adding documemtation for graph api for adding members to drive
  docs/apis/http/graph/spaces.md
Labels: QA:team
