Repository owncloud/ocis, pull requests merged in 2024-03, with the labels that each got.

#8555 [docs-only] Updates the added envvar lists because of changes in the store service
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.md
Labels: Topic:Documentation

#8540 [tests-only][full-ci] Add option to check ocis connection by authenticating user
  .drone.star
  tests/ociswrapper/cmd/cmd.go
  tests/ociswrapper/ocis/config/config.go
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#8562 [tests-only] Port pr #8547 and #8540
  .drone.star
  tests/ociswrapper/cmd/cmd.go
  tests/ociswrapper/ocis/config/config.go
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#8551 [tests-only][full-ci] adding test for listing permission of a project space
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8577 [docs-only] Fix added envars table
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.md
Labels: Topic:Documentation

#8582 [docs-only] And more envvars that are added to the table
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.md
Labels: Topic:Documentation

#8588 [docs-only] More updates to the added envvar tables
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.md
Labels: Topic:Documentation

#8590 [docs-only] Finally fixed the added tables, 2 envvars were accidentially deleted
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.md
Labels: Topic:Documentation

#8633 [docs-only] Just a small text fix for an envvar in storage-users
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#8632 [tests-only][full-ci]Refactor check for no of items in json schema
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#8663 [docs-only] Update storage-users readme
  services/storage-users/README.md
Labels: Topic:Documentation

#8622 [full-ci] [tests-only] Added tests for PROPFIND as sharee
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiSharingNg/propfindShares.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#8671 [full-ci] [tests-only] Added tests for PROPFIND as sharee for folder
  tests/acceptance/features/apiSharingNg/propfindShares.feature
Labels: QA:team

#8676 [full-ci] [tests-only] Used kebab case for example table header name
  tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature
  tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature
Labels: QA:team

#8674 [full-ci] [tests-only] sharee PROPFINDs same name shares shared by multiple users
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiSharingNg/propfindShares.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#8689 [full-ci] [tests-only] Used kebab case for example table header name
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiNotification/deprovisioningNotification.feature
  tests/acceptance/features/apiReshare/disableReshare.feature
  tests/acceptance/features/apiReshare/resharing.feature
  tests/acceptance/features/apiSearch2/mediaTypeSearch.feature
  tests/acceptance/features/apiSharingNg/deletePermissions.feature
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
Labels: QA:team

#8690 [docs-only] Align web service readme with admin docs
  services/web/README.md
Labels: Topic:Documentation

#8675 [full-ci] [tests-only] sharee PROPFINDs on resource containing brackets
  tests/acceptance/features/apiSharingNg/propfindShares.feature
Labels: QA:team

#8511 [tests-only][full-ci] adding test for sharing personal space to user
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8698 [full-ci] [tests-only] Used kebab case for example table header name
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/createSpace.feature
  tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/apiSpaces/setQuota.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/trashBin.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/createFileFolderWhenSharesSpaceExist.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
Labels: QA:team

#8700 [full-ci] [tests-only] Used kebab case for example table header name
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiAuth/ocsPUTAuth.feature
  tests/acceptance/features/coreApiAuth/webDavAuth.feature
  tests/acceptance/features/coreApiAuth/webDavSpecialURLs.feature
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShareToShares.feature
  tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
  tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShare.feature
  tests/acceptance/features/coreApiShareReshareToShares1/reShareDisabled.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareUpdate.feature
  tests/acceptance/features/coreApiShareReshareToShares2/reShareWithExpiryDate.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiSharees/sharees.feature
  tests/acceptance/features/coreApiTrashbin/trashbinDelete.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavDelete/deleteFile.feature
  tests/acceptance/features/coreApiWebdavDelete/deleteFolder.feature
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
  tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolder.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
  tests/acceptance/features/coreApiWebdavProperties/setFileProperties.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
Labels: QA:team

#8630 [tests-only][full-ci] check same name resources shared by different users
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#8636 [tests-only][full-ci]added test for declining a share
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/mountOrUnmountShare.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8705 [tests-only][full-ci] adding tests for sending a share invitation to a user on virtual drive
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8716 enhancement: Make IDP cookies same site strict
  changelog/unreleased/enhancement-strict-same-site-cookie.md
  go.mod
  go.sum
  services/idp/pkg/backends/cs3/bootstrap/cs3.go
  services/idp/pkg/config/config.go
  services/idp/pkg/config/defaults/defaultconfig.go
  vendor/github.com/libregraph/lico/bootstrap/backends/ldap/ldap.go
  vendor/github.com/libregraph/lico/bootstrap/backends/libregraph/libregraph.go
  vendor/github.com/libregraph/lico/bootstrap/bootstrap.go
  vendor/github.com/libregraph/lico/bootstrap/config.go
  vendor/github.com/libregraph/lico/bootstrap/settings.go
  vendor/github.com/libregraph/lico/identifier/config.go
  vendor/github.com/libregraph/lico/identifier/cookie.go
  vendor/github.com/libregraph/lico/identifier/identifier.go
  vendor/github.com/libregraph/lico/oidc/provider/config.go
  vendor/github.com/libregraph/lico/oidc/provider/cookie.go
  vendor/github.com/libregraph/lico/oidc/provider/provider.go
  vendor/modules.txt
Labels: Topic:Security, Status:Needs-Review

#8646 [tests-only] add API test to check cors headers with OPTIONS request to tus upload endpoint
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: QA:team

#8623 [tests-only][full-ci]added test with step definition for mounting share when auto accept env set to false
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/mountOrUnmountShare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8739 [tests-only] increase e2e pipeline by 1
  .drone.star
Labels: QA:team

#8737 [tests-only][full-ci] Add test for downloading resouces by user when auto sync is disabled
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
Labels: QA:team
