Repository owncloud/ocis, pull requests merged in 2024-02, with the labels that each got.

#8285 [tests-only] Added test for sharingNg for endpoint sharedByMe from personal space
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8326 [tests-only] Add test to share deleted resource
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8306 [tests-only]Added tests for `SharingNg` test share by me from project
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
Labels: QA:team

#8327 [tests-only] Add test to share resource inside of space
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8338 [tests-only] remove tests related to resharing
  tests/acceptance/features/apiSharingNg/reshare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8345 [tests-only]Added test for list shared by me when shared to group
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
Labels: QA:team

#8347 [full-ci] [tests-only] Added more test coverage for invalid roles
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
Labels: QA:team

#8311 [tests-only] adding test for updating expiration date of a share
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8193 [docs-only] changed release template
  .github/release_template.md
Labels: Status:Needs-Review

#8348 [tests-only] extend share invite json response assertion
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#8366 [docs-only] Update new-service-checklist.md
  docs/services/general-info/new-service-checklist.md
Labels: Topic:Documentation

#8369 [ tests only ] [ full-ci] removed datatable for resource type row
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
Labels: QA:team

#8371 [full-ci] [tests-only] Added tests to lists file shared with them when sync is disabled
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/bootstrap/SettingsContext.php
Labels: QA:team

#8373 [full-ci] [tests-only] Add tests sharing with group when auto-sync is disabled
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#8375 [docs-only] Fix envvar descriptions with a trailing double dot
  services/audit/pkg/config/config.go
  services/clientlog/pkg/config/config.go
  services/eventhistory/pkg/config/config.go
  services/frontend/pkg/config/config.go
  services/graph/pkg/config/config.go
  services/nats/pkg/config/config.go
  services/notifications/pkg/config/config.go
  services/sharing/pkg/config/config.go
  services/storage-users/pkg/config/config.go
  services/userlog/pkg/config/config.go
Labels: Topic:Documentation

#8378 [tests-only] extend API test coverage for content-disposition header
  tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
Labels: QA:team

#8387 [docs-only] Fix unrelease text
  changelog/unreleased/fix-cs3-backend.md
Labels: Topic:Documentation

#8377 [docs-only] Add .adoc table version to env-var-deltas
  docs/env-var-deltas/4.0.5-5.0.0-added.adoc
  docs/env-var-deltas/4.0.5-5.0.0-added.md
  docs/env-var-deltas/make-adoc-table-from-md.txt
Labels: Topic:Documentation

#8390 [tests-only] API test coverage content-disposition header with filename having quotes
  tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
Labels: QA:team

#8295 [tests-only] add API test coverage for issue-8242
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
Labels: QA:team

#8346 [tests-only] adding test for sharing with user and group
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#8329 [tests-only] adding test for updating role of a share
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8407 [docs-only] Add missing added envvar to list
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.md
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-removed.adoc
Labels: Topic:Documentation

#8370 [tests-only][full-ci]resourcetype variable deleted from testcode
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/deletePermissions.feature
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8417 [docs-only] Add MICRO_REGISTRY_xxx to the added envars list
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.md
Labels: Topic:Documentation

#8411 [docs-only] Fixes the content of extended_envars.yaml
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#8421 Fix a typo
  services/_includes/adoc/storage-users_configvars.adoc
Labels: Topic:Documentation

#8376 [tests-only][full-ci]Strictly validate json scheme on tests steps
  tests/acceptance/features/apiSharingNg/listPermissions.feature
Labels: QA:team

#8422 [tests-only][full-ci] skip spacecontext subsitutions for reva
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#8437 [docs-only] Fixing changelog references pointing to the wrong PR
  CHANGELOG.md
  changelog/5.0.0-rc.1_2023-12-27/access-token-issuer.md
  changelog/5.0.0-rc.1_2023-12-27/allow-configuring-additional-routes.md
  changelog/5.0.0-rc.1_2023-12-27/passwod-policies-renaming.md
Labels: Topic:Documentation

#8438 [docs-only] Add more envvars to the removed table
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-removed.adoc
  docs/services/general-info/env-var-deltas/4.0.0-5.0.0-removed.md
Labels: Topic:Documentation

#8443 [tests-only][full-ci] Move auto-sync-disable related scenario in separate file
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Labels: QA:team

#8441 [tests-only] add API test coverage for trying to search with invalid pattern
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSearch1/search.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#8453 [docs-only] Fixes doc adoc table templates
  docs/templates/ADOC_extended.tmpl
  docs/templates/ADOC_global.tmpl
Labels: Topic:Documentation

#8406 [tests-only][full-ci] add tests to list space file shared with them when sync is disabled
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Labels: QA:team

#8388 [tests-only] [full-ci] adding tests for shareWithMe endpoint when resource is shared with a group
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#8446 [tests-only] extend search tests for mediatype filter
  tests/acceptance/features/apiSearch2/mediaTypeSearch.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#8459 [tests-only] add API test coverage for file MOVE to space-id as destination
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#8414 [tests-only][full-ci] add tests to list space files shared with group when auto sync is disable
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Labels: QA:team

#8450 [tests-only][full-ci]Added tests to lists shared by me after sharee is deleted
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#8470 [tests-only] extend tests: MOVE to Shares-space-id as destination
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#8460 [tests-only] fix MOVE with another user dav path scenarios
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiAuth/webDavCOPYAuth.feature
  tests/acceptance/features/coreApiAuth/webDavDELETEAuth.feature
  tests/acceptance/features/coreApiAuth/webDavMOVEAuth.feature
Labels: QA:team

#8485 [tests-only] add test to try to download public link using basic auth
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
Labels: QA:team

#8448 [full-ci] [tests-only] Added tests to list sharedWithMe for file with same name shared by multiple users
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#8397 [full-ci] [tests-only] Added tests for auto-sync disabled
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Labels: QA:team

#8449 Sharing resources with same name auto sync disabled
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Labels: QA:team

#8490 [full-ci][tests-only]add tests coverage for removing expiration date from shares
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8501 [tests-only] make json scheme assertion strict
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Labels: QA:team

#8503 [tests-only] use new json schema assertion lib that supports latest schema drafts
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiGraphUserGroup/editUser.feature
  tests/acceptance/features/apiGraphUserGroup/getGroup.feature
  tests/acceptance/features/apiGraphUserGroup/getUser.feature
  tests/acceptance/features/apiGraphUserGroup/getUserOwnInformation.feature
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  vendor-bin/behat/composer.json
Labels: QA:team

#8484 [tests-only][full-ci] Add tests to list space files shared with user who is also member of group
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Labels: QA:team

#8533 [tests-only] check for invalid schema validators
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/apiNotification/spaceNotification.feature
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#8516 [tests-only][full-ci] Add tests to list same name resources shared by user from two project-spaces with him/her
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
Labels: QA:team

#8546 verify all system accounts are set
  .vscode/launch.json
  ocis-pkg/shared/errors.go
  ocis/pkg/init/init.go
  services/auth-service/pkg/config/parser/parse.go
  services/clientlog/pkg/config/parser/parse.go
  services/frontend/pkg/config/parser/parse.go
  services/graph/pkg/config/parser/parse.go
  services/notifications/pkg/config/parser/parse.go
  services/ocm/pkg/config/parser/parse.go
  services/proxy/pkg/config/parser/parse.go
  services/search/pkg/config/parser/parse.go
  services/settings/pkg/config/parser/parse.go
  services/storage-users/pkg/config/parser/parse.go
  services/userlog/pkg/config/parser/parse.go
Labels: Type:Bug
