Repository owncloud/ocis, pull requests merged in 2024-05, with the labels that each got.

#9018 [tests-only] add API tests for file download and rename edge cases
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature
  tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
Labels: QA:team

#9027 [tests-only] [full-ci] Change given step for sharing space in apiDownloads
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/apiDownloads/spaceDownload.feature
Labels: QA:team

#9021 [tests-only][full-ci] removing usage of a stepdefination inside another stepdefinition in OcisConfigContext.php
  tests/acceptance/features/bootstrap/OcisConfigContext.php
Labels: QA:team

#9039 [tests-only][full-ci] make function's return type in drone file similar
  .drone.star
Labels: QA:team

#8892 [tests-only][full-ci] removing usage of a stepdefination inside another stepdefination in Provisioning.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/coreApiWebdavOperations/downloadFile.feature
Labels: QA:team

#9019 [tests-only][full-ci]changing given step of creating link share in feature file
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiDepthInfinity/propfind.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#9054 [tests-only][full-ci] backport make function's return type in drone file similar
  .drone.star
Labels: QA:team

#9056 [docs-only] Fix Collaboration readme
  services/collaboration/README.md
Labels: Topic:Documentation

#9045 [tests-only] [full-ci] Use sharingNG in given step for sharing in `sharesReport.feature` file
  tests/acceptance/features/apiContract/sharesReport.feature
Labels: QA:team

#9040 [full-ci] [tests-only] Use sharingNG for sharing in given step, refactored accordingly
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#9070 [docs-only] Typo in storage-users README.md
  services/storage-users/README.md
Labels: Topic:Documentation

#9026 [tests-only][full-ci] removing usage of a stepdefination defined inside OcisConfigContext.php from other functions and files
  tests/acceptance/features/bootstrap/GraphContext.php
Labels: QA:team

#9057 [full-ci] [tests-only] Use sharing ng in given steps api search1 suite
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSearch1/dateSearch.feature
  tests/acceptance/features/apiSearch1/search.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8999 [tests-only][full-ci]Added test for hide shared resources (personal and project space) in shares
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9053 [tests-only][full-ci] removing usage of a stepdefination inside another stepdef in FilesVersionsContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9044 [tests-only][full-ci] Add tests for create link on project spaces resources
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/linkShare.feature
Labels: QA:team

#9060 [full-ci] [tests-only] Use sharing ng in given steps api search2 suite
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSearch2/mediaTypeSearch.feature
  tests/acceptance/features/apiSearch2/tagSearch.feature
Labels: QA:team

#9061 [full-ci] [tests-only] Use sharing ng in given steps api search content suite
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSearchContent/contentSearch.feature
Labels: QA:team

#9022 [tests-only][full-ci] removing usage of a stepdefinition inside another stepdefinition in NotificationContext.php
  tests/acceptance/features/bootstrap/NotificationContext.php
Labels: QA:team

#9083 [tests-only] extend group sharing and MOVE api tests
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/coreApiWebdavMove2/moveFile.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
Labels: QA:team

#9063 [tests-only] [full-ci] updating given step for sharing in unlockFiles
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#9080 [full-ci] [tests-only] Used sharing-ng in given steps
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
  tests/acceptance/features/apiSpacesShares/checksum.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#9090 [full-ci] [tests-only] Used sharing-ng in given steps
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/etagPropagation.feature
  tests/acceptance/features/apiSpacesShares/favorite.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
Labels: QA:team

#8906 [tests-only][full-ci]Add tests for update shares using root endpoint
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9092 [tests-only][full-ci] changing given step of creating share in feature file
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
Labels: QA:team

#9097 [tests-only] separate different SharingNG share steps
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiArchiver/downloadById.feature
  tests/acceptance/features/apiArchiver/downloadByPath.feature
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
  tests/acceptance/features/apiDepthInfinity/propfind.feature
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/apiDownloads/spaceDownload.feature
  tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiGraphUserGroup/deleteGroup.feature
  tests/acceptance/features/apiGraphUserGroup/deleteUser.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiSearch1/dateSearch.feature
  tests/acceptance/features/apiSearch1/search.feature
  tests/acceptance/features/apiSearch2/mediaTypeSearch.feature
  tests/acceptance/features/apiSearch2/tagSearch.feature
  tests/acceptance/features/apiSearchContent/contentSearch.feature
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/apiSharingNg/propfindShares.feature
  tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature
  tests/acceptance/features/apiSharingNg/removeAccessToDriveItem.feature
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/apiSharingNg/sharedWithMeSyncDisabled.feature
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature
  tests/acceptance/features/apiSpacesDavOperation/updateFileByFileId.feature
  tests/acceptance/features/apiSpacesShares/changingFilesShare.feature
  tests/acceptance/features/apiSpacesShares/checksum.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/etagPropagation.feature
  tests/acceptance/features/apiSpacesShares/favorite.feature
  tests/acceptance/features/apiSpacesShares/moveSpaces.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9102 [tests-only] fix typo and data types (follow up #9097)
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9081 [tests-only][full-ci] updating given step for sharing and env in docs for starting email service
  docs/ocis/development/testing.md
  tests/acceptance/config/behat.yml
  tests/acceptance/docker/src/ocis-base.yml
  tests/acceptance/features/apiNotification/deleteNotification.feature
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/apiNotification/spaceNotification.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9013 [tests-only][full-ci] removing usage of a stepdefinition inside another stepdefinition in OCSContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9055 [tests-only][full-ci]updating given step for sharing in lockfiles
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#9082 [tests-only] [full-ci] Use sharing ng in api spaces
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/publicLink.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9105 [tests-only][full-ci] changing given step of creating share in feature file
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesDavOperation/moveByFileId.feature
Labels: QA:team

#9120 [full-ci] [tests-only] Used sharing-ng in given steps
  tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9076 [tests-only][full-ci]Add tests for create link using root endpoint
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9078 [tests-only][full-ci]Add tests for setting password on share link
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/linkShare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9123 [tests-only][full-ci]add tests for removing share link
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9126 [tests-only] extend trashbin restore API tests
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/coreApiTrashbinRestore/trashbinRestore.feature
Labels: QA:team

#9117 [tests-only][full-ci] removing usage of a stepdefination defined inside ChecksumContext.php from other functions and files
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9122 [tests-only] [full-ci] Use sharingNG in remaining feature file of apiSpaces folder
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/apiSpaces/setQuota.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/trashBin.feature
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
Labels: QA:team

#9121 [tests-only] extend delete API tests
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiWebdavDelete/deleteFile.feature
Labels: QA:team

#9118 [tests-only][full-ci]changing given from ocs to graph in favoritesSharingToShares feature
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiFavorites/favoritesSharingToShares.feature
Labels: QA:team

#8934 [tests-only][full-ci] backport e2e runner implementation
  .drone.star
Labels: QA:team

#9160 [full-ci] [tests-only] Adjusted the json schema
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#9140 [full-ci] [tests-only] Use sharing ng in given steps api spaces shares suite
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9125 [tests-only][full-ci]extend list permission tests coverage for root endpoint
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9143 [full-ci] [tests-only] Use sharing ng in given steps api spaces shares suite
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
Labels: QA:team

#9162 [tests-only] [full-ci] Use sharingNg in coreApiShareOperationsToShares1
  tests/acceptance/config/behat-core.yml
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature
Labels: QA:team

#9173 [tests-only][full-ci] removing the usage of a stepdef inside another stepdef in ShareesContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
Labels: QA:team

#9174 [full-ci] [tests-only] Use `sharing-ng` in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
Labels: QA:team

#9175 [tests-only][full-ci]Bump latest commit from web stable-8.0
  .drone.env
Labels: QA:team

#9158 [tests-only][full-ci] divide shareNg test suite into multiple parts
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
  tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
  tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
Labels: QA:team

#9172 [docs-only] Update ocis_wopi docker-compose.yml --> add staging for letsencrypt
  deployments/examples/ocis_wopi/.env
  deployments/examples/ocis_wopi/docker-compose.yml
Labels: Topic:Documentation, Category:Enhancement

#9179 [tests-only][full-ci]remove the usage of a stepdefinition inside another stepdefinition in SpacesTUSContext.php
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
Labels: QA:team

#9186 [docs-only] Backport of #9172 (add staging for letsencrypt in ocis_wopi)
  deployments/examples/ocis_wopi/.env
  deployments/examples/ocis_wopi/docker-compose.yml
Labels: Backport

#9142 [tests-only][full-ci]changing given from ocs to graph in feature file
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
Labels: QA:team

#9150 [tests-only] add file/folder creation and list sharedByMe of link shares
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavProperties/createFileFolder.feature
Labels: QA:team

#9202 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
  tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
Labels: QA:team

#9191 [tests-only] [full-ci] Use sharingNG in coreApiShareOperationsToShares2
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
Labels: QA:team

#9203 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
Labels: QA:team

#9204 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavMove2/moveShareOnOcis.feature
Labels: QA:team

#9207 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
Labels: QA:team

#9206 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
Labels: QA:team

#9213 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
  tests/acceptance/features/coreApiWebdavProperties/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
  tests/acceptance/features/coreApiWebdavProperties/setFileProperties.feature
Labels: QA:team

#9218 [tests-only] [full-ci] Update given step using sharingNg in coreApiShareUpdateToShares
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
Labels: QA:team

#9215 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiTrashbin/trashbinSharingToShares.feature
Labels: QA:team

#9184 [tests-only][full-ci]changing given from ocs to graph in feature file
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptSharesToSharesFolder.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveShareInsideAnotherShare.feature
Labels: QA:team

#9190 [tests-only][full-ci] removing the usage of a stepDefinition inside another stepDefinition in SpacesContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#9216 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiVersions/fileVersionAuthor.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
Labels: QA:team

#9217 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/features/coreApiMain/checksums.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/coreApiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
Labels: QA:team

#9221 [full-ci] [tests-only] Use sharing-ng in given steps for sharing
  tests/acceptance/config/behat-core.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiReshare/resharing.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/createFileFolderWhenSharesSpaceExist.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/coreApiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
  tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature
Labels: QA:team

#9189 [tests-only][full-ci] removing the usage of a stepdef inside another stepdef in Sharing.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#9200 [tests-only][full-ci] adding skip-on-reva tag for test related to sharing link
  tests/acceptance/config/behat-core.yml
  tests/acceptance/features/bootstrap/SharingNgContext.php
  tests/acceptance/features/coreApiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/coreApiVersions/fileVersions.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
  tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
Labels: QA:team

#9149 fix service names for userlog, graph, invitations, sse and web
  services/graph/pkg/config/defaults/defaultconfig.go
  services/graph/pkg/server/http/server.go
  services/invitations/pkg/config/defaults/defaultconfig.go
  services/proxy/pkg/config/defaults/defaultconfig.go
  services/sse/pkg/server/http/server.go
  services/userlog/pkg/config/defaults/defaultconfig.go
  services/userlog/pkg/server/http/server.go
  services/web/pkg/server/http/server.go
Labels: Type:Bug

#8992 [full-ci] [tests-only] Add test for disable sync with non-existing resource
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9256 [tests-only][full-ci] adding tests for multiple enable disable share
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
Labels: QA:team

#9064 [tests-only][full-ci] removing usage of a stepdef inside another stepdef in FeatureContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#9250 [tests-only][full-ci] adding test for creating link space share via permission endpoint
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9233 [tests-only][full-ci] adding test for deleting/removing share link of a project space using permission endpoint
  tests/acceptance/features/apiSharingNg/removeAccessToDrive.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#9205 [tests-only][full-ci] removing usage of a stepdef inside another stepdef in WedDav.php
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#9251 [tests-only][full-ci] adding test for updating share link of a project space using permission endpoint
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgLinkShare/linkShare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team
