Repository owncloud/ocis, pull requests merged in 2024-10, with the labels that each got.

#10207 [docs-only][chore] Update env_vars.yaml
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10135 [tests-only][full-ci]configure custom translation for tests
  .drone.star
  tests/acceptance/features/apiActivities/activities.feature
  tests/config/translations/de/LC_MESSAGES/activitylog.po
  tests/config/translations/de/LC_MESSAGES/notifications.po
  tests/config/translations/de/LC_MESSAGES/userlog.po
  tests/config/translations/es/LC_MESSAGES/notifications.po
  tests/config/translations/es/LC_MESSAGES/userlog.po
Labels: QA:team

#10205 [tests-only][full-ci] fix shares propfind tests
  tests/acceptance/TestHelpers/CollaborationHelper.php
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/TestHelpers/HttpRequestHelper.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiContract/copy.feature
  tests/acceptance/features/apiContract/propfind.feature
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiContract/spacesReport.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiSearchContent/extractedProps.feature
  tests/acceptance/features/apiSharingNg1/propfindShares.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpacesDavOperation/propfindByFileId.feature
Labels: QA:team

#10217 bump reva to v2.25.1-0.20241002085034-fcd567b4c0ce
  changelog/unreleased/bump-reva.md
  go.mod
  go.sum
  vendor/github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/upload/upload.go
  vendor/modules.txt
Labels: Type:Bug

#10218 [tests-only][full-ci] add test coverage for #9933
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiSharingNg1/propfindShares.feature
Labels: QA:team

#10201 [tests-only][full-ci] add tests to check activities after public actions
  tests/acceptance/bootstrap/PublicWebDavContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiActivities/shareActivities.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
Labels: QA:team

#10160 [tests-only][full-ci] add tests to check activites of space after updating public share link
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/features/apiActivities/shareActivities.feature
Labels: QA:team

#10087 [test-only][full-ci] removing SPACE_ID_FROM_OCIS from test code
  tests/acceptance/TestHelpers/OcisHelper.php
  tests/acceptance/TestHelpers/UploadHelper.php
  tests/acceptance/TestHelpers/WebDavHelper.php
  tests/acceptance/bootstrap/ChecksumContext.php
  tests/acceptance/bootstrap/FavoritesContext.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/FilesVersionsContext.php
  tests/acceptance/bootstrap/SearchContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/bootstrap/TUSContext.php
  tests/acceptance/bootstrap/TrashbinContext.php
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/bootstrap/WebDavLockingContext.php
  tests/acceptance/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#10230 [tests-only][full-ci] add test to check edit activity for a file
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10196 [tests-only][full-ci]add tests for check project drive file info
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
Labels: QA:team

#10233 [docs-only] Update ocis_full.md in dev docs, add an important note
  docs/ocis/deployment/ocis_full.md
Labels: Topic:Documentation

#10232 [docs-only] Update deployment examples ocis_full README.md
  deployments/examples/ocis_full/README.md
Labels: Topic:Documentation

#10226 [tests-only] add test coverage for #8804
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/bootstrap/TUSContext.php
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
Labels: QA:team

#10235 [tests-only][full-ci] add test to check api activities with sort filter
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10249 [tests-only] use existing method to get space
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/bootstrap/WebDavLockingContext.php
Labels: QA:team

#10229 [tests-only][full-ci] add tests for CLI command uploads sessions
  .drone.star
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#10255 [tests-only][full-ci] get necessary contexts properly
  tests/acceptance/TestHelpers/BehatHelper.php
  tests/acceptance/bootstrap/ArchiverContext.php
  tests/acceptance/bootstrap/AuthContext.php
  tests/acceptance/bootstrap/CapabilitiesContext.php
  tests/acceptance/bootstrap/ChecksumContext.php
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/bootstrap/FavoritesContext.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/FilesVersionsContext.php
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/bootstrap/NotificationContext.php
  tests/acceptance/bootstrap/OCSContext.php
  tests/acceptance/bootstrap/OcmContext.php
  tests/acceptance/bootstrap/PublicWebDavContext.php
  tests/acceptance/bootstrap/SearchContext.php
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/bootstrap/ShareesContext.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/bootstrap/TUSContext.php
  tests/acceptance/bootstrap/TagContext.php
  tests/acceptance/bootstrap/TrashbinContext.php
  tests/acceptance/bootstrap/WebDavLockingContext.php
  tests/acceptance/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/config/behat.yml
Labels: QA:team

#10234 [tests-only][full-ci] add test to check api activities with limit and sort filter
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10265 [docs-only[chore] env_vars.yaml update
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10273 [docs-only] Add short description in dev docs for services
  docs/helpers/env_vars.yaml
  docs/services/_index.md
Labels: Topic:Documentation

#10275 [docs-only] Describe the storage-system service purpose
  services/storage-system/README.md
Labels: Topic:Documentation

#10119 [tests-only][full-ci] test: extend test coverage for searching a file
  tests/acceptance/bootstrap/SearchContext.php
  tests/acceptance/features/apiSearch1/search.feature
Labels: QA:team

#10278 [docs-only] Update traefik image in ocis_full deployment
  deployments/examples/ocis_full/docker-compose.yml
Labels: Topic:Documentation

#10299 [docs-only][chore] Regular env_vars.yaml update
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10256 [tests-only][full-ci] added test to restart upload sessions using CLI command
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#10307 use secure config defaults for OCM
  changelog/unreleased/secure-ocm-by-default.md
  services/ocm/pkg/config/defaults/defaultconfig.go
Labels: Type:Bug

#10290 [tests-only][full-ci] add test to list shares shared to federated user
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#10322 [docs-only] Update helpers/README.md
  docs/helpers/README.md
Labels: Topic:Documentation

#10325 [tests-only] ci: enable e2e pipelines
  .drone.star
Labels: QA:team

#10294 [tests-only][full-ci] add test to list permissions of a resource shared to a federated user
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#10332 [tests-only][full-ci] test: Check absence of application/octet-stream MIME Type in app/list
  tests/acceptance/bootstrap/CollaborationContext.php
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
Labels: QA:team

#10370 [docs-only] Fix envvar name in collaboration service readme
  services/collaboration/README.md
Labels: Topic:Documentation

#10170 [tests-only][full-ci] Add tests for version disable config
  tests/acceptance/bootstrap/FilesVersionsContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/coreApiVersions/disableFileVersioning.feature
Labels: QA:team

#10349 [tests-only][full-ci] add test to list shares sharedByMe/sharedWithMe being member of a group
  tests/acceptance/features/apiSharingNg1/sharedByMe.feature
  tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
Labels: QA:team

#10260 [tests-only][full-ci] add test to clean upload sessions that are not processing using CLI command
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#10371 [docs-only][chore] Update envvars.yaml and extended_vars.yaml
  docs/helpers/env_vars.yaml
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#10264 [tests-only][full-ci] add test to share project drive's resource to a federated user
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#10362 [docs-only] ADDING 2 envvars to existing ones in settings service
  services/settings/pkg/config/config.go
Labels: Topic:Documentation

#10324 [tests-only][full-ci] adding test for editing space with role space editor without version
  tests/acceptance/features/apiSpaces/changeSpaces.feature
Labels: QA:team

#10379 [tests-only][full-ci] refactor test to add federated user as a member of a project space using permissions endpoint
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#10312 [tests-only][full-ci] add test to check add, edit, rename & move activities for a file using file-id path
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/features/apiActivities/activitiesByFileId.feature
Labels: QA:team

#10386 Fix envvar deprecations for 7.0.0
  changelog/unreleased/fix_deprecations.md
  services/collaboration/pkg/config/cs3api.go
  services/graph/pkg/config/config.go
Labels: Type:Bug

#10375 [docs-only] Update gateway readme
  services/gateway/README.md
Labels: Topic:Documentation

#10408 [tests-only][full-ci] added test to clean upload sessions that are not in postprocessing and not infected by virus
  tests/acceptance/config/behat.yml
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#10413 [tests-only][full-ci]Add environment needed for ocm
  .vscode/launch.json
  tests/config/drone/.env-federation
Labels: QA:team

#10395 [tests-only][full-ci] add test to check activities of a folder after renaming
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10348 [tests-only][full-ci] running secure viewer role with ocis wrapper instead of running ocis with GRAPH_AVAILABLE_ROLES
  .drone.star
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiContract/sharesReport.feature
  tests/acceptance/features/apiGraph/roleManagementEndpoint.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
  tests/acceptance/features/apiSharingNg1/sharedByMe.feature
  tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpacesDavOperation/copyByFileId.feature
  tests/acceptance/features/apiSpacesShares/copySpaces.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiWebdavProperties/copyFile.feature
Labels: QA:team

#10424 [tests-only]removed to do comment inside Trashbin
  tests/acceptance/bootstrap/TrashbinContext.php
Labels: QA:team

#10426 [docs-only] Add libvips build dependencies for macOS
  services/thumbnails/README.md
Labels: Topic:Documentation

#10434 [tests-only][full-ci]removed to do comment-in-behat-config
  tests/acceptance/TestHelpers/SetupHelper.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/config/behat.yml
Labels: QA:team

#10407 [tests-only][full-ci] add test to check move activities of destination file and folder
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#10437 [docs-only] Update the added services per release table
  docs/services/general-info/added-services.md
  docs/services/general-info/added-services.xlsx
Labels: Topic:Documentation

#10443 [tests-only][full-ci]fix expected failures files line number
  tests/acceptance/expected-failures-without-remotephp.md
Labels: QA:team
