Repository owncloud/ocis, pull requests merged in 2024-04, with the labels that each got.

#8754 [tests-only][full-ci] Add test for downloading resources by group user when auto sync is disable
  tests/acceptance/features/apiSpacesDavOperation/getFileByFileId.feature
Labels: QA:team

#8746 [tests-only][full-ci]removing usage of a stepdefination inside another stepdefination in WebDavLockingContext
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#8714 [docs-only] Update the docs helper readme and other related files
  docs/README.md
  docs/helpers/README.md
  docs/helpers/env_vars.yaml
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#8776 [docs-only] Updates doc process related env_var yaml files
  docs/helpers/env_vars.yaml
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#8780 [docs-only] Fixes the app-registry readme and dev docs
  docs/helpers/env_vars.yaml
  docs/services/app-registry/_index.md
  services/app-registry/README.md
Labels: Topic:Documentation

#8767 [tests-only][full-ci] added test to check id from shareWithMe and PROPFIND response
  tests/acceptance/features/apiSharingNg/propfindShares.feature
  tests/acceptance/features/bootstrap/SpacesContext.php
Labels: QA:team

#8753 [tests-only][full-ci]removing usage of a stepdefination inside another stepdefination in TUSContext
  tests/acceptance/features/bootstrap/SpacesTUSContext.php
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: QA:team

#8734 [tests-only][full-ci]adding scenerio for enable and disable sync feature in group share
  tests/acceptance/features/apiSharingNg/mountOrUnmountShare.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8791 [docs-only] Fix envvar description (storage-users)
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#8797 [docs-only] Add a how to in dev docs for translations in ocis
  docs/services/general-info/add-translations.md
Labels: Topic:Documentation

#8792 [docs-only] [5.0] Fix envvar description (storage-users)
  services/storage-users/pkg/config/config.go
Labels: Topic:Documentation

#8786 [tests-only][full-ci] changed wording of mount unmount to enable and disable sync
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8809 [docs-only]Update docs outdated content
  docs/apis/http/authorization.md
  docs/ocis/development/testing.md
  docs/ocis/identity-provider/oidc.md
Labels: QA:team

#8755 [tests-only][full-ci] removing usage of a Stepdefinition inside another Stepdefinition in TrashbinContext
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: QA:team

#8758 [tests-only][full-ci] removing usage of a stepdefination inside another stepdefination in TagContext
  tests/acceptance/features/bootstrap/TagContext.php
Labels: QA:team

#8801 [docs-only] [chore] Autogenerated updates from 'make -C docs docs-generate'
  docs/helpers/env_vars.yaml
  docs/services/app-registry/_index.md
Labels: Topic:Documentation

#8821 [docs-only] fix two services readme to be inline with admin docs
  services/postprocessing/README.md
  services/storage-users/README.md
Labels: Topic:Documentation

#8832 [tests-only][full-ci] notify chat also on nightly success
  .drone.star
Labels: QA:team

#8789 [tests-only][full-ci]Enable disable sync from project space
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
Labels: QA:team

#8838 [docs-only] Make a frontend envvar description more clear
  services/frontend/pkg/config/config.go
Labels: Topic:Documentation

#8840 [docs-only] Backport of "Make a frontend envvar description more clear"
  services/frontend/pkg/config/config.go
Labels: Topic:Documentation

#8836 [docs-only] Update the frontent service readme adding more password descriptions
  services/frontend/README.md
Labels: Topic:Documentation

#8849 [docs-only] Remove EXPERIMENTAL from envvar text
  services/frontend/pkg/config/config.go
Labels: Topic:Documentation

#8796 [tests-only][full-ci]added test for enable disable share shared by project space to group
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
Labels: QA:team

#8823 [tests-only][full-ci] updated drone file to display pipeline in order by trigger
  .drone.star
Labels: QA:team

#8852 [tests-only][full-ci] backport notify chat on nightly success also
  .drone.star
Labels: QA:team

#8851 [tests-only][full-ci] backport updated drone file to display pipeline in order by trigger (#8823)
  .drone.star
Labels: QA:team

#8869 [docs-only] Update new-service-checklist in dev docs
  docs/services/general-info/new-service-checklist.md
Labels: Topic:Documentation

#8867 [tests-only][full-ci]rename e2e test suite
  .drone.star
Labels: QA:team

#8872 [docs-only] Update the docs helpers readme
  docs/helpers/README.md
Labels: Topic:Documentation

#8866 [tests-only][full-ci]send nightly notification to builds channel
  .drone.star
Labels: QA:team

#8874 [tests-only][full-ci] backport send nightly notification to builds channel
  .drone.star
Labels: QA:team

#8745 [tests-only][full-ci] removing usage of a stepdefination inside another stepdefination in WebDavPropertiesContext
  tests/acceptance/features/bootstrap/FavoritesContext.php
  tests/acceptance/features/bootstrap/SpacesContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#8813 [tests-only][full-ci] removing usage of a stepdefination inside another stepdefination in PublicWebDavContext
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
Labels: QA:team

#8824 [tests-only][full-ci]Add tests for listing drive root permission
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8886 [tests-only] do not try to delete already deleted groups
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
  tests/acceptance/features/bootstrap/GraphContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/SharingNgContext.php
  tests/acceptance/features/coreApiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/coreApiTrashbin/trashbinFilesFolders.feature
Labels: QA:team

#8896 [docs-only] updating the ocis-wopi deployment readme's
  deployments/examples/ocis_wopi/README.md
  docs/ocis/deployment/ocis_wopi.md
Labels: Topic:Documentation

#8889 [tests-only] [full-ci] changed php version
  .drone.star
  composer.json
  vendor-bin/behat/composer.json
Labels: QA:team

#8900 [tests-only][full-ci]changed php version
  .drone.star
  composer.json
  tests/acceptance/docker/src/acceptance.yml
  vendor-bin/behat/composer.json
Labels: QA:team

#8875 [tests-only][full-ci] adding test for enabling sync of non-existent resource
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8929 [tests-only] [full-ci] remove web smoke tests from nightly and full ci
  .drone.star
Labels: QA:team

#8933 [tests-only][full-ci] adding tests for sharing a file inside project space with all allowed roles from list permissions response
  tests/acceptance/features/apiSharingNg/listPermissions.feature
Labels: QA:team

#8941 [tests-only][full-ci]backport remove web smoke tests from nightly and full-ci
  .drone.star
Labels: QA:team

#8927 [tests-only][full-ci] add test for listing permissions of a project space by a non-member user
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8910 [tests-only][full-ci] adding test for listing permission of a project drive by a member with viewer permission
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8964 [tests-only] extend list sharedbyme API tests coverage
  tests/acceptance/features/apiSharingNg/sharedByMe.feature
Labels: QA:team

#8850 [tests-only][full-ci]Add tests for share invite on drives root
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/shareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8979 chore: code cleanup service/webfinger
  services/webfinger/pkg/command/server.go
  services/webfinger/pkg/config/parser/parse.go
  services/webfinger/pkg/relations/openid_discovery.go
  services/webfinger/pkg/server/debug/server.go
  services/webfinger/pkg/server/http/option.go
  services/webfinger/pkg/server/http/server.go
  services/webfinger/pkg/service/v0/service.go
Labels: Status:Needs-Review

#8940 [tests-only][full-ci]adding tests for sharing a folder inside project space with all allowed roles from list permissions response
  tests/acceptance/features/apiSharingNg/listPermissions.feature
Labels: QA:team

#8959 [tests-only][full-ci] List permission and share a project space with allowed roles
  tests/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNg/listPermissions.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8991 [full-ci] [tests-only] Added tests for enabling share sync with not shared resource id
  tests/acceptance/features/apiSharingNg/enableDisableShareSync.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8990 [tests-only] [full-ci] Change given step using SharingNG for share in apiArchiver/downloadByPath.feature file
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiArchiver/downloadByPath.feature
Labels: QA:team

#8913 [tests-only][full-ci]Extend ShareNg test for updating share permission for project space
  tests/acceptance/features/apiSharingNg/updateShareInvitations.feature
  tests/acceptance/features/bootstrap/SharingNgContext.php
Labels: QA:team

#8932 [tests-only][full-ci] adding test for listing permission of personal drive by a diffrent user
  tests/acceptance/features/apiSharingNg/listPermissions.feature
Labels: QA:team

#8914 [tests-only][full-ci] changed given statement of sharing link in api antivirus feature file
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: QA:team

#8967 [tests-only] extend list sharedwithme API tests coverage
  tests/acceptance/features/apiSharingNg/sharedWithMe.feature
Labels: QA:team

#9015 [tests-only] add API tests to search user/group with special chars
  tests/acceptance/features/apiGraphUserGroup/getGroup.feature
  tests/acceptance/features/apiGraphUserGroup/getUser.feature
Labels: QA:team

#9024 [tests-only][full-ci]updating antivirus feature file
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: QA:team

#9017 [tests-only][full-ci]change given step from ocs to graph
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiContract/propfind.feature
Labels: QA:team
