Repository owncloud/ocis, pull requests merged in 2025-05, with the labels that each got.

#11281 [docs-only] test(wrapper): bring back log
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#11282 [full-ci][test-only] ci: add cache server and bucket varaibles
  .drone.star
Labels: QA:team

#11285 [full-ci][tests-only] Check datetime format in json response
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiActivities/activities.feature
  tests/acceptance/features/apiActivities/activitiesByFileId.feature
  tests/acceptance/features/apiActivities/shareActivities.feature
  tests/acceptance/features/apiOcm/share.feature
  tests/acceptance/features/apiSharingNgAdditionalShareRole/editorWithVersions.feature
  tests/acceptance/features/apiSharingNgAdditionalShareRole/listGrantsShareRole.feature
  tests/acceptance/features/apiSharingNgItemInvitation/itemShareInvitations.feature
  tests/acceptance/features/apiSharingNgItemLinkShare/createItemLinkShare.feature
  tests/acceptance/features/apiSharingNgItemLinkShare/updateItemLinkShare.feature
  tests/acceptance/features/apiSharingNgShares/sharedByMe.feature
  tests/acceptance/features/apiSharingNgShares/sharedWithMe.feature
Labels: QA:team

#11288 [docs-only] Update OCIS_CLAIM_xxx envvar texts
  services/proxy/pkg/config/config.go
Labels: Topic:Documentation

#11289 [full-ci][tests-only] read concurrently from command running in pseudo-terminal
  tests/acceptance/bootstrap/EmailContext.php
  tests/acceptance/features/apiSettings/notificationSetting.feature
  tests/ociswrapper/ocis/ocis.go
Labels: QA:team

#11275 [tests-only][full-ci] Extend notification tests for `User Light` role
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/apiNotification/spaceNotification.feature
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#8576 [tests-only][full-ci] Add test for the user who is also a group member having edit permisson can overwrite
  tests/acceptance/TestHelpers/WebDavHelper.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgShares/sharedWithMe.feature
Labels: QA:team

#11309 [chore][docs-only] Update env_vars.yaml and extended_vars.yaml
  docs/helpers/env_vars.yaml
  docs/helpers/extended_vars.yaml
Labels: Topic:Documentation

#11311 [tests-only][full-ci] check resource creation with share creation
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgShares/sharedWithMe.feature
Labels: QA:team

#11301 [docs-only] Add a minimalistic docker run example
  README.md
  docs/ocis/guides/_index.md
  docs/ocis/guides/migrate-data-rclone.md
  docs/ocis/guides/ocis-mini-eval.md
Labels: Topic:Documentation

#11306 [full-ci][tests-only]Add tests for searching user
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraphUser/getUser.feature
Labels: QA:team

#11317 [tests-only][full-ci]Add tests for exceeding tags amount
  tests/acceptance/bootstrap/TagContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiSpaces/tag.feature
Labels: QA:team

#10896 [tests-only][full-ci] adding test for disabling in-app notifications for space deleted event
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#10990 [full-ci][tests-only] Add step for checking the status code and headers in TUS upload
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/bootstrap/TUSContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-API-on-OCIS-storage.md
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/creationWithUploadExtension.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtime.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
Labels: QA:team

#11319 [docs-only] Update the ocis_full example for new image versions
  changelog/unreleased/update-ocis_full_images.md
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/onlyoffice.yml
Labels: Topic:Documentation

#11315 [docs-only] Update the Python script which creates adoc delta envvar tables
  docs/helpers/changed_envvars.py
Labels: Topic:Documentation

#11324 [tests-only[full-ci] skip flaky share test
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgShares/sharedWithMe.feature
Labels: QA:team

#11330 [full-ci] chore: bump Web to 11.3.2
  .drone.env
  changelog/unreleased/bump-web-to-11.3.2.md
  services/web/Makefile
Labels: Platform:Web, Topic:Dependencies, dependencies

#11321 [tests-only][full-ci]Add tests for listing trashed resources
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/cleanupEmptyTrashBin.feature
  tests/acceptance/features/cliCommands/trashBin.feature
Labels: QA:team

#11340 [full-ci][tests-only]Add tests for restoring specific and all trashed resources of specific space at once
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/cliCommands/trashBin.feature
Labels: QA:team

#11345 [test-ony][full-ci] add test for list single permission for resources
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgPermissions/listPermissions.feature
Labels: QA:team

#11351 [full-ci][tests-only] check personal settings value after update
  tests/acceptance/TestHelpers/SettingsHelper.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSettings/settings.feature
Labels: QA:team

#11360 [full-ci] Fixed the matrix notification script file
  tests/config/drone/notification.sh
Labels: QA:team

#11370 [full-ci] Backport: Add matrix notification
  .drone.star
  tests/config/drone/notification.sh
Labels: QA:team

#11378 [full-ci] Show build source (branch, tag, or cron) in Matrix notification
  tests/config/drone/notification.sh
Labels: QA:team

#11379 [tests-only][full-ci] Check activities after copying 0 byte file
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiActivities/activities.feature
  tests/acceptance/features/apiActivities/activitiesByFileId.feature
Labels: QA:team
