Repository owncloud/ocis, pull requests merged in 2025-01, with the labels that each got.

#10703 [tests-only][full-ci] Tests for checking share access after changing share role to and from "Denied"
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiSharingNg1/sharedWithMe.feature
Labels: QA:team

#10697 [tests-only][full-ci] Add tests for zero-byte file upload on public share
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiSharingNgLinkSharePermission/createLinkShare.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
Labels: QA:team

#10756 [tests-only][full-ci]added test to list drives after the share role has been disabled
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiSharingNg1/enableDisablePermissionsRole.feature
Labels: QA:team

#10810 [tests-only][full-ci]Add list permission tests with query dedicated to ocm
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/TestHelpers/HttpRequestHelper.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/features/apiOcm/listPermissions.feature
  tests/acceptance/features/apiOcm/share.feature
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
Labels: QA:team

#10811 [tests-only][full-ci] test: check if share creation date is not missing in share invite response
  tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
Labels: QA:team

#10829 [tests-only][full-ci] add test to try listing permissions of a disabled project space
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
Labels: QA:team

#10836 [docs-only] Update image versions for ocis-full
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/web_extensions/drawio.yml
  deployments/examples/ocis_full/web_extensions/externalsites.yml
  deployments/examples/ocis_full/web_extensions/jsonviewer.yml
  deployments/examples/ocis_full/web_extensions/progressbars.yml
  deployments/examples/ocis_full/web_extensions/unzip.yml
Labels: Topic:Documentation

#10835 [docs-only] Update settings source strings for translation
  services/settings/pkg/store/defaults/defaults.go
  services/settings/pkg/store/defaults/templates.go
Labels: Topic:Documentation

#10837 [docs-only][stable-7.0] ocis_full: point ocis to production and not to rolling
  deployments/examples/ocis_full/.env
Labels: Topic:Documentation

#10827 [tests-only][full-ci] add tests to check settings api response
  .drone.star
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature
  tests/acceptance/features/apiGraph/getAssignedRole.feature
  tests/acceptance/features/apiSettings/settings.feature
Labels: QA:team

#10840 [docs-only][7.0] Update image versions for ocis-full
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/web_extensions/drawio.yml
  deployments/examples/ocis_full/web_extensions/externalsites.yml
  deployments/examples/ocis_full/web_extensions/jsonviewer.yml
  deployments/examples/ocis_full/web_extensions/progressbars.yml
  deployments/examples/ocis_full/web_extensions/unzip.yml
Labels: Topic:Documentation

#10844 [docs-only] Add a note to translation docs how to manual start syncing.
  docs/services/general-info/add-translations.md
Labels: Topic:Documentation

#10845 [docs-only] Add how to document cli commands
  docs/services/general-info/document-cli-commands.md
Labels: Topic:Documentation

#10733 [tests-only][full-ci] add test for creating auth token for an app using impersonation api
  tests/acceptance/TestHelpers/AuthAppHelper.php
  tests/acceptance/bootstrap/AuthAppContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAuthApp/token.feature
Labels: QA:team

#10839 [tests-only][full-ci] add test to try creating folder link share with denied role
  tests/acceptance/features/apiSharingNgLinkSharePermission/createLinkShare.feature
Labels: QA:team

#10852 [docs-only] Update envvars.yaml with latest changes
  docs/helpers/env_vars.yaml
Labels: Topic:Documentation

#10854 [docs-only] Add new tables for added/deprecated/removed envvars for 7.1
  docs/helpers/changed_envvars.py
  docs/services/general-info/env-var-deltas/7.0.0-7.1.0-added.adoc
  docs/services/general-info/env-var-deltas/7.0.0-7.1.0-deprecated.adoc
  docs/services/general-info/env-var-deltas/7.0.0-7.1.0-removed.adoc
Labels: Topic:Documentation

#10820 [tests-only][full-ci] adding test for disabling mail notifications
  .drone.star
  tests/acceptance/bootstrap/NotificationContext.php
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#10863 [tests-only][full-ci]Update go version for wrapper
  tests/ociswrapper/go.mod
  tests/ociswrapper/go.sum
  tests/ociswrapper/vendor/github.com/creack/pty/README.md
  tests/ociswrapper/vendor/github.com/creack/pty/pty_unsupported.go
  tests/ociswrapper/vendor/github.com/creack/pty/pty_zos.go
  tests/ociswrapper/vendor/github.com/creack/pty/ztypes_openbsd_32bit_int.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/.golangci.yml
  tests/ociswrapper/vendor/github.com/spf13/cobra/README.md
  tests/ociswrapper/vendor/github.com/spf13/cobra/active_help.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/active_help.md
  tests/ociswrapper/vendor/github.com/spf13/cobra/args.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/bash_completions.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/bash_completions.md
  tests/ociswrapper/vendor/github.com/spf13/cobra/bash_completionsV2.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/cobra.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/command.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/completions.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/fish_completions.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/fish_completions.md
  tests/ociswrapper/vendor/github.com/spf13/cobra/flag_groups.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/powershell_completions.go
  tests/ociswrapper/vendor/github.com/spf13/cobra/powershell_completions.md
  tests/ociswrapper/vendor/github.com/spf13/cobra/projects_using_cobra.md
  tests/ociswrapper/vendor/github.com/spf13/cobra/shell_completions.md
  tests/ociswrapper/vendor/github.com/spf13/cobra/user_guide.md
  tests/ociswrapper/vendor/github.com/spf13/cobra/zsh_completions.md
  tests/ociswrapper/vendor/modules.txt
Labels: QA:team

#10871 Rename role for consistency (leftover from change in v3)
  changelog/unreleased/consistenly-name-roles.md
  services/proxy/pkg/userroles/defaultrole.go
  services/settings/pkg/service/v0/settings.go
  services/settings/pkg/store/defaults/defaults.go
Labels: Type:Bug

#10760 [tests-only][full-ci] added test to update share role to existing role after the assigned share role is disabled
  tests/acceptance/features/apiSharingNg1/enableDisablePermissionsRole.feature
Labels: QA:team

#10817 [tests-only][full-ci]Add tests for lists permission with query for personal space
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/features/apiSharingNg1/filterPermissions.feature
Labels: QA:team

#10841 [tests-only][full-ci] shift existing settings api test scenarios to `apiSettings` test suite
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiGraph/getAssignedRole.feature
  tests/acceptance/features/apiSettings/settings.feature
Labels: QA:team

#10876 [docs-only] update PR number in `fix-graph-invite-createddatetime.md` changelog
  changelog/7.1.0-rc.1_2025-01-10/fix-graph-invite-createddatetime.md
Labels: QA:team

#10850 [tests-only][full-ci] use displayname of permissions role in resource link share creation step
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/features/apiActivities/shareActivities.feature
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiCollaboration/wopi.feature
  tests/acceptance/features/apiDepthInfinity/propfind.feature
  tests/acceptance/features/apiGraph/enforcePasswordPublicLink.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
  tests/acceptance/features/apiSharingNg1/sharedByMe.feature
  tests/acceptance/features/apiSharingNg2/removeAccessToDriveItemInLinkShare.feature
  tests/acceptance/features/apiSharingNgLinkSharePermission/createLinkShare.feature
  tests/acceptance/features/apiSharingNgLinkSharePermission/updateLinkShare.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/deletePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/coreApiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/coreApiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/coreApiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/coreApiWebdavOperations/listFiles.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
  tests/acceptance/features/coreApiWebdavPreviews/linkSharePreviews.feature
  tests/acceptance/features/coreApiWebdavProperties/getFileProperties.feature
Labels: QA:team

#10894 [tests-only][full-ci]Remove os enviroment duplication from ocis wrapper
  tests/ociswrapper/wrapper/handlers/handler.go
Labels: QA:team

#10899 [tests-only][full-ci] use displayname of permissions role in space link share creation step
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/features/apiActivities/shareActivities.feature
  tests/acceptance/features/apiCollaboration/wopi.feature
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
  tests/acceptance/features/apiSharingNg1/removeAccessToDrive.feature
  tests/acceptance/features/apiSharingNg1/sharedByMe.feature
  tests/acceptance/features/apiSharingNgLinkSharePermission/createLinkShare.feature
  tests/acceptance/features/apiSharingNgLinkSharePermission/updateLinkShare.feature
  tests/acceptance/features/apiSharingNgLinkShareRoot/createLinkShare.feature
  tests/acceptance/features/apiSharingNgLinkShareRoot/updateLinkShare.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/publicLink.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesDavOperation/fileVersionByFileID.feature
  tests/acceptance/features/apiSpacesShares/publicLinkDownload.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/coreApiWebdavUpload/uploadFile.feature
Labels: QA:team

#10900 [tests-only][full-ci] fixing body for disabling email notification
  tests/acceptance/bootstrap/SettingsContext.php
Labels: QA:team

#10893 [full-ci][tests-only] add test to disable in-app notification for `Share Removed` event
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#10901 [full-ci][tests-only] check mails with wait if the mailbox is empty
  tests/acceptance/TestHelpers/EmailHelper.php
Labels: QA:team

#10911 [docs-only] update PR number in `fix-mail-notifications-for-user-light.md` changelog
  changelog/7.1.0-rc.2_2025-01-17/fix-mail-notifications-for-user-light.md
Labels: QA:team

#10721 [tests-only][full-ci] Tests for availability of resources shared with Denied role while listing all drives
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
Labels: QA:team

#10877 [tests-only][full-ci] Add tests for filtering permission on project space resource
  tests/acceptance/bootstrap/OcisConfigContext.php
  tests/acceptance/features/apiSharingNg1/filterPermissions.feature
Labels: QA:team

#10922 [docs-only] Update ocis_full collabora image version
  deployments/examples/ocis_full/collabora.yml
Labels: Topic:Documentation

#10925 [tests-only][full-ci] refactor scenario to disable mail notification for `Share removed` event
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team
