Repository owncloud/ocis, pull requests merged in 2025-06, with the labels that each got.

#11353 [tests-only][full-ci] Add tests related to purge expired trash resources
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/trashBin.feature
Labels: QA:team

#11393 [full-ci][tests-only] port quota fixes
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/TestHelpers/HttpRequestHelper.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/bootstrap/Provisioning.php
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiArchiver/downloadByPath.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiGraphUserGroup/editUser.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
Labels: QA:team

#11403 [tests-only][full-ci] check share sync status before actions
  tests/acceptance/features/coreApiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/coreApiShareOperationsToShares1/accessToShare.feature
Labels: QA:team

#11391 feat: add SpaceEditorWithoutTrashbin role
  changelog/unreleased/add-space-editor-without-trashbin-role.md
  services/graph/README.md
  services/graph/pkg/config/defaults/defaultconfig.go
  services/graph/pkg/unifiedrole/conversion.go
  services/graph/pkg/unifiedrole/export_test.go
  services/graph/pkg/unifiedrole/filter.go
  services/graph/pkg/unifiedrole/roles.go
  services/graph/pkg/unifiedrole/roles_test.go
  services/web/pkg/theme/theme.go
Labels: Category:Enhancement

#11396 [full-ci][tests-only] re-organize test suites for better execution time
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/ocis-base.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiAccountsHashDifficulty/addUser.feature
  tests/acceptance/features/apiAccountsHashDifficulty/assignRole.feature
  tests/acceptance/features/apiAccountsHashDifficulty/createShareToSharesFolder.feature
  tests/acceptance/features/apiAccountsHashDifficulty/uploadFile.feature
  tests/acceptance/features/apiAccountsHashDifficulty/webDavPUTAuthInvalid.feature
  tests/acceptance/features/apiContract/spacesSharesReport.feature
  tests/acceptance/features/apiDownloads/download.feature
  tests/acceptance/features/apiGraphUser/createUser.feature
  tests/acceptance/features/apiGraphUser/deleteUser.feature
  tests/acceptance/features/apiGraphUser/editUser.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/disableAndDeleteSpaces.feature
  tests/acceptance/features/apiSpaces/editPublicLinkOfSpace.feature
  tests/acceptance/features/apiSpaces/filePreviews.feature
  tests/acceptance/features/apiSpaces/listSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/removeSpaceObjects.feature
  tests/acceptance/features/apiSpaces/restoreSpaces.feature
  tests/acceptance/features/apiSpaces/spaceManagement.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/trashBin.feature
  tests/acceptance/features/apiSpaces/uploadSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpaces.feature
  tests/acceptance/features/apiSpacesShares/shareSpacesViaLink.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpace.feature
  tests/acceptance/features/apiSpacesShares/shareSubItemOfSpaceViaPublicLink.feature
Labels: QA:team

#11427 [docs-only] Update ocis_full image versions
  deployments/examples/ocis_full/.env
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/mailserver.yml
Labels: Topic:Documentation

#11428 [tests-only][full-ci] fix search reindexing cli tests
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/features/cliCommands/searchReIndex.feature
Labels: QA:team

#11410 [tests-only][full-ci] split large test suites
  .drone.star
  tests/acceptance/bootstrap/Sharing.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSharingNgDriveLinkShare/createDriveLinkShare.feature
  tests/acceptance/features/apiSharingNgDriveLinkShare/createInternalLinkShare.feature
  tests/acceptance/features/apiSharingNgItemLinkShare/createInternalLinkShare.feature
  tests/acceptance/features/apiSharingNgItemLinkShare/createItemLinkShare.feature
  tests/acceptance/features/apiSharingNgItemLinkShare/createLinkShareBannedPassword.feature
  tests/acceptance/features/apiSharingNgItemLinkShare/createLinkShareWithoutPasswordEnforce.feature
  tests/acceptance/features/apiSharingNgItemLinkShare/enforcePasswordPublicLink.feature
  tests/acceptance/features/apiSharingNgLinkShareManagement/deleteLinkShare.feature
  tests/acceptance/features/apiSharingNgLinkShareManagement/passwordPolicy.feature
  tests/acceptance/features/apiSharingNgLinkShareManagement/updateItemLinkShare.feature
  tests/acceptance/features/apiSharingNgLinkShareManagement/writableShareEnforcePassword.feature
Labels: QA:team

#11307 [tests-only][full-ci] added test to resume all uploads sessions
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#11440 [docs-only] Update the search service README
  services/search/README.md
Labels: Topic:Documentation

#11438 [full-ci][tests-only] refactor(wrapper): handle empty service name
  tests/ociswrapper/ocis/ocis.go
  tests/ociswrapper/wrapper/handlers/handler.go
Labels: QA:team

#11439 [tests-only] Fix post processing test scenarios
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/cliCommands/trashBin.feature
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#11425 [tests-only] fix upload expired cli test scenario
  tests/acceptance/TestHelpers/UploadHelper.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/bootstrap/WebDav.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#11450 [docs-only] Updating ocis_full web-extensions image versions
  deployments/examples/ocis_full/web_extensions/drawio.yml
  deployments/examples/ocis_full/web_extensions/externalsites.yml
  deployments/examples/ocis_full/web_extensions/jsonviewer.yml
  deployments/examples/ocis_full/web_extensions/progressbars.yml
  deployments/examples/ocis_full/web_extensions/unzip.yml
Labels: Topic:Documentation

#11436 [tests-only][full-ci] restart upload sessions of unfinished uploads
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/features/cliCommands/uploadSessions.feature
Labels: QA:team

#11463 [full-ci] Fix changelog issue in drone.star
  .drone.star
Labels: Addams

#11448 [tests-only][full-ci] add test for SpaceEditorWithoutTrashbin role
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/features/apiSharingNgAdditionalShareRole/SpaceEditorWithoutTrashbin.feature
Labels: QA:team

#11472 [full-ci][tests-only] add step to try to restore trashed file
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiSharingNgAdditionalShareRole/SpaceEditorWithoutTrashbin.feature
Labels: QA:team

#11336 [tests-only][full-ci] add API test to enable share sync after disabling
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiSettings/settings.feature
Labels: QA:team
