Repository owncloud/ocis, pull requests merged in 2025-02, with the labels that each got.

#10955 [tests-only][full-ci] cleanup inbucket emails of all created users after test
  tests/acceptance/bootstrap/NotificationContext.php
Labels: QA:team

#10959 [tests-only][full-ci] Re-order tests step to avoid post processing flakiness
  tests/acceptance/features/apiSharingNg1/filterPermissions.feature
Labels: QA:team

#10960 [tests-only][full-ci] skip changelog pipeline in nightly ci run
  .drone.star
Labels: QA:team

#10958 [tests-only][full-ci] add test to check mail notification for user with role `User Light`
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#10902 [tests-only][full-ci] add test to disable notifications for `Added as space member` event
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#10929 [tests-only][full-ci]added test for checking share-types property of shared resource shared to federated user
  tests/acceptance/features/apiOcm/propfind.feature
Labels: QA:team

#10928 [tests-only][full-ci] add test to set receiving email intervals to never
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#10969 [tests-only][full-ci] refactor scenarios to remove multiple `listAllNotifications` request in steps
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#10905 [tests-only][full-ci] add test to disable notification for `Removed as space member` event
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#10814 [tests-only][full-ci] adding test for deleting auth-app token using the token received from auth-app list request
  tests/acceptance/bootstrap/AuthAppContext.php
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAuthApp/token.feature
  tests/acceptance/features/cliCommands/authAppToken.feature
Labels: QA:team

#10807 [tests-only][full-ci] add tests for checking the header location for tus upload
  tests/acceptance/TestHelpers/TusClient.php
  tests/acceptance/bootstrap/SpacesTUSContext.php
  tests/acceptance/bootstrap/TUSContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiOcm/share.feature
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/apiSpacesShares/shareUploadTUS.feature
Labels: QA:team

#10961 [tests-only][full-ci]Add tests for filtering permission of project resource
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/features/apiOcm/listPermissions.feature
  tests/acceptance/features/apiSharingNg1/filterPermissions.feature
Labels: QA:team

#10972 [tests-only][full-ci] Fix notification cleanup and retry
  tests/acceptance/bootstrap/NotificationContext.php
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/features/apiNotification/deleteNotification.feature
  tests/acceptance/features/apiNotification/deprovisioningNotification.feature
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/apiNotification/notification.feature
  tests/acceptance/features/apiNotification/serviceAvailabilityCheck.feature
  tests/acceptance/features/apiNotification/spaceNotification.feature
  tests/acceptance/features/apiOcm/createInvitation.feature
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team, p1-urgent

#10991 [docs-only] Update the release roadmap document in dev docs
  docs/ocis/release_roadmap.md
Labels: Topic:Documentation

#11006 [docs-only] Update images for ocis_full deployment example
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/onlyoffice.yml
Labels: Topic:Documentation

#11009 [tests-only][full-ci] backport skip changelog pipeline in nightly ci run
  .drone.star
Labels: QA:team

#11007 [docs-only][7.0] Update images for ocis_full deployment example
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/onlyoffice.yml
Labels: Topic:Documentation, Backport

#10995 [tests-only][full-ci] added test to delete ocm shares
  tests/acceptance/features/apiOcm/deleteShare.feature
Labels: QA:team

#10973 [tests-only][full-ci] add test to disable mail and in-app notifications when receiving a federated share
  tests/acceptance/features/apiOcm/acceptInvitation.feature
  tests/acceptance/features/apiOcm/deleteFederatedConnections.feature
  tests/acceptance/features/apiOcm/listPermissions.feature
  tests/acceptance/features/apiOcm/ocmNotifications.feature
Labels: QA:team

#11015 [tests-only][full-ci]added test for user trying to accept federation share invitation from same instance
  tests/acceptance/bootstrap/OcmContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiOcm/acceptInvitation.feature
Labels: QA:team

#10994 [tests-only][full-ci] Store share invite response
  tests/acceptance/bootstrap/Sharing.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/bootstrap/SpacesContext.php
Labels: QA:team

#10981 [full-ci][tests-only] adding test for trying to create auth app-token without expiry
  tests/acceptance/bootstrap/AuthAppContext.php
  tests/acceptance/features/apiAuthApp/token.feature
Labels: QA:team

#11018 [tests-only][full-ci] When file or folder is unshared user received an email notification
  tests/acceptance/features/apiNotification/emailNotification.feature
Labels: QA:team

#11000 [tests-only][full-ci] use store for drives
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/TestHelpers/HttpRequestHelper.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/bootstrap/NotificationContext.php
  tests/acceptance/bootstrap/Provisioning.php
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiArchiver/downloadByPath.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiGraphUserGroup/editUser.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
Labels: QA:team

#11034 [tests-only][full-ci]Add test for ocm share expiry
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#11043 [tests-only][full-ci] skip spaces that are marked as deleted
  tests/acceptance/bootstrap/SpacesContext.php
Labels: QA:team

#11040 [tests-only][full-ci] Replace inbucket with mailpit
  .drone.star
  docs/ocis/development/testing.md
  tests/acceptance/TestHelpers/CliHelper.php
  tests/acceptance/TestHelpers/EmailHelper.php
  tests/acceptance/TestHelpers/OcisConfigHelper.php
  tests/acceptance/TestHelpers/SettingsHelper.php
  tests/acceptance/bootstrap/EmailContext.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/NotificationContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiOcm/createInvitation.feature
  tests/acceptance/run.sh
Labels: QA:team, QA:p2

#11048 [docs-only] update `NOTIFICATIONS_SMTP_PORT` for mailpit email service in `testing.md`
  docs/ocis/development/testing.md
Labels: QA:team

#11044 [tests-only][full-ci] port quota update fix
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/TestHelpers/HttpRequestHelper.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/bootstrap/Provisioning.php
  tests/acceptance/bootstrap/SettingsContext.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiArchiver/downloadByPath.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiGraphUserGroup/editUser.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
Labels: QA:team

#11050 [docs-only]Replace docker inbucket with mailpit
  docs/ocis/development/testing.md
  tests/acceptance/docker/src/acceptance.yml
  tests/acceptance/docker/src/email.yml
  tests/acceptance/docker/src/ocis-base.yml
Labels: QA:team

#11045 [tests-only][full-ci]Remove notification and email tag from unrelated scenario
  tests/acceptance/features/apiNotification/emailNotification.feature
  tests/acceptance/features/apiNotification/serviceAvailabilityCheck.feature
  tests/acceptance/features/apiOcm/acceptInvitation.feature
  tests/acceptance/features/apiOcm/createInvitation.feature
  tests/acceptance/features/apiOcm/deleteFederatedConnections.feature
  tests/acceptance/features/apiOcm/listPermissions.feature
  tests/acceptance/features/apiOcm/ocmNotifications.feature
  tests/acceptance/features/apiSettings/notificationSetting.feature
Labels: QA:team

#11024 [tests-only][full-ci] add test to hide federated shared resource
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#10823 [tests-only][full-ci] added test to enable disable Secure Viewer permissions role for federated shares
  tests/acceptance/bootstrap/ArchiverContext.php
  tests/acceptance/bootstrap/OcmContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiOcm/enableDisablePermissionsRole.feature
Labels: QA:team

#11074 [tests-only][full-ci]added test to share resources after the permissions role is disabled
  tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
Labels: QA:team

#11002 [tests-only][full-ci] add test to create folder inside federated share
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiOcm/share.feature
Labels: QA:team

#11075 [tests-only][full-ci] Add test to delete user containing `+` character in the username
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiGraphUserGroup/deleteUser.feature
Labels: QA:team
