Repository owncloud/ocis, pull requests merged in 2025-07, with the labels that each got.

#11486 [docs-only] Fix missing patch number in introduction version
  docs/helpers/env_vars.yaml
  services/frontend/pkg/config/config.go
  services/notifications/pkg/config/config.go
  services/settings/pkg/config/config.go
Labels: Topic:Documentation

#11513 Update Discover OCIS with Docker Documentation
  docs/ocis/guides/ocis-local-docker.md
Labels: Topic:Docker, Topic:Documentation

#11501 [tests-only] [full-ci] Add test for checking activities with limit filters applied
  tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md
  tests/acceptance/features/apiActivities/activities.feature
Labels: QA:team

#11506 [docs-only] Update envvar description
  Makefile
  docs/helpers/README.md
  docs/helpers/env_vars.yaml
  docs/ocis/development/envvars.md
  docs/services/general-info/.gitignore
  docs/services/general-info/added-services.md
  docs/services/general-info/added-services.xlsx
  docs/services/general-info/env-var-deltas/make-adoc-and-md-files.txt
  docs/services/general-info/envvars/_index.md
  docs/services/general-info/envvars/deprecating-variables.md
  docs/services/general-info/envvars/env-var-deltas/4.0.0-5.0.0-added.adoc
  docs/services/general-info/envvars/env-var-deltas/4.0.0-5.0.0-added.md
  docs/services/general-info/envvars/env-var-deltas/4.0.0-5.0.0-removed.adoc
  docs/services/general-info/envvars/env-var-deltas/4.0.0-5.0.0-removed.md
  docs/services/general-info/envvars/env-var-deltas/5.0.0-7.0.0-added.adoc
  docs/services/general-info/envvars/env-var-deltas/5.0.0-7.0.0-added.md
  docs/services/general-info/envvars/env-var-deltas/5.0.0-7.0.0-deprecated.adoc
  docs/services/general-info/envvars/env-var-deltas/5.0.0-7.0.0-deprecated.md
  docs/services/general-info/envvars/env-var-deltas/5.0.0-7.0.0-removed.adoc
  docs/services/general-info/envvars/env-var-deltas/5.0.0-7.0.0-removed.md
  docs/services/general-info/envvars/env-var-deltas/7.0.0-7.1.0-added.adoc
  docs/services/general-info/envvars/env-var-deltas/7.0.0-7.1.0-added.md
  docs/services/general-info/envvars/env-var-deltas/7.0.0-7.1.0-deprecated.adoc
  docs/services/general-info/envvars/env-var-deltas/7.0.0-7.1.0-deprecated.md
  docs/services/general-info/envvars/env-var-deltas/7.0.0-7.1.0-removed.adoc
  docs/services/general-info/envvars/env-var-deltas/7.0.0-7.1.0-removed.md
  docs/services/general-info/envvars/env-var-deltas/7.1.0-7.2.0-added.adoc
  docs/services/general-info/envvars/env-var-deltas/7.1.0-7.2.0-added.md
  docs/services/general-info/envvars/env-var-deltas/7.1.0-7.2.0-deprecated.adoc
  docs/services/general-info/envvars/env-var-deltas/7.1.0-7.2.0-deprecated.md
  docs/services/general-info/envvars/env-var-deltas/7.1.0-7.2.0-removed.adoc
  docs/services/general-info/envvars/env-var-deltas/7.1.0-7.2.0-removed.md
  docs/services/general-info/envvars/env-var-deltas/_index.md
  docs/services/general-info/envvars/envvar-naming-scopes.md
  docs/services/general-info/envvars/new-release-process.md
  docs/services/general-info/envvars/special-envvars.md
Labels: Topic:Documentation

#11519 [full-ci][k6-test] Release 7.2.0-rc.2
  changelog/7.2.0-rc.2_2025-07-09/fix-cli-upload.md
  changelog/7.2.0-rc.2_2025-07-09/fix-roles-label.md
  changelog/7.2.0-rc.2_2025-07-09/fix-watermark-viewer-role.md
  ocis-pkg/version/version.go
  sonar-project.properties
Labels: Addams

#11529 [docs-only] Update the search service readme
  services/search/README.md
Labels: Topic:Documentation

#11534 [tests-only][full-ci] update expiration date time in test scenraios
  tests/acceptance/features/apiSharingNgDriveInvitation/updateDriveShareInvitations.feature
  tests/acceptance/features/apiSharingNgItemInvitation/updateItemShareInvitations.feature
Labels: QA:team

#11536 [tests-only][full-ci] update expiration date time in test scenraios
  tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
Labels: QA:team

#11535 [tests-only][full-ci] update expiration date time in test scenraios
  tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
Labels: QA:team

#11551 [tests-only][full-ci] CI: Replace hardcoded repo in wget URL with dynamic ctx.repo.slug
  .drone.star
Labels: QA:team

#11549 [tests-only][full-ci] Backport 7.1/disable clone on notification
  .drone.star
Labels: QA:team

#11563 [docs-only] Fix chat link in dev docs
  docs/_index.md
Labels: Topic:Documentation
