Repository owncloud/ocis, pull requests merged in 2025-09, with the labels that each got.

#11625 chore: bump Web to v12.0.4
  .drone.env
  changelog/unreleased/enhancement-bump-web-to-v12.0.4.md
  services/web/Makefile
Labels: dependencies

#11650 [tests-only][full-ci] Backport 7.1/ fix the correct regex on test script
  tests/acceptance/run.sh
Labels: QA:team

#11666 [docs-only] Update the ocis_full deployment example
  changelog/unreleased/update_ocis_full.md
  deployments/examples/ocis_full/.env
  deployments/examples/ocis_full/collabora.yml
  deployments/examples/ocis_full/docker-compose.yml
  deployments/examples/ocis_full/onlyoffice.yml
Labels: Topic:Documentation

#11665 fix: [OCISDEV-330] add OCS v2 capabilities endpoint to public paths
  changelog/unreleased/fix-capabilities-public-path.md
  services/proxy/pkg/middleware/authentication.go
Labels: Type:Bug

#11677 [full-ci] fix(proxy): [OCISDEV-330] add webdav without trailing slash
  changelog/unreleased/fix-add-webdav-without-trailing-slash-into-proxy-default-config.md
  services/proxy/pkg/config/defaults/defaultconfig.go
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/coreApiAuth/webDavAuth.feature
  tests/acceptance/features/coreApiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/coreApiWebdavOperations/propfind.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/creationWithUploadExtension.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtime.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/coreApiWebdavUploadTUS/uploadToShare.feature
Labels: Type:Bug
